### ISSUE TITLE
Yarp randomly facing  "The SSL connection could not be established" 

### ISSUE THREAD

**Issue by DureSameen** [microsoft/reverse-proxy#1499] opened 2022-01-06 16:24 UTC
### Describe the bug
My 10% calls are failing, that made via the Yarp. It was working fine before December 2021.

### To Reproduce
The faulty behavior is random.

### Further technical details

- Yarp 1.0.0.0
- The platform (Linux/macOS/Windows)

**Comment by samsp-msft** [comment] 2022-01-06 17:24
Can you provide logs from YARP for the failed requests?

**Comment by Tratcher** [comment] 2022-01-06 22:31
You'll want https://docs.microsoft.com/en-us/aspnet/core/fundamentals/logging/?view=aspnetcore-6.0#configure-logging with everything turned up to Debug level.

**Comment by karelz** [comment] 2022-01-18 19:12
@DureSameen any update on logs? The issue is unfortunately not actionable for us without more info.
Thanks!

**Comment by DureSameen** [comment] 2022-01-19 12:28
I added logging to my code, but there are no failed requests though. our IT managed did looked upon this issue and checked ssl certificates, it seems some issue is at certificate level. There are some problem but I can't share logs and urls publicly.

**Comment by karelz** [comment] 2022-01-20 18:18
OK, looks like there is nothing we can do here. Closing. If you have something actionable, feel free to reopen or open new issue.

**Closed by karelz** 2022-01-20 18:18 UTC
Labels: Type: Bug, needs more info
