### ISSUE TITLE
Issues targeting .NET Core 3.1

### ISSUE THREAD

**Issue by freemstr** [microsoft/reverse-proxy#837] opened 2021-03-13 03:42 UTC
When creating direct proxy and setting timeout
var requestOptions = new RequestProxyOptions() { Timeout = TimeSpan.FromSeconds(100) };

The error is  CS8400 Feature 'init-only setters' is not available in C# 8.0. Please use language version 9.0 or greater.

This is not an option for MVC projects targeting LTS 3.1
Please consider compatible constructor.

Thank you

**Comment by Tratcher** [comment] 2021-03-14 20:15
C#9 features do work on 3.1 provided you use the 5.0 SDK. Using the latest SDK is recommended even when targeting older runtimes. Are you able to try that?

For init-only setters on 3.1 you do need a copy of this file, but we've been told to make that `public` which _should_ reduce the duplication.
https://github.com/microsoft/reverse-proxy/blob/b5cbc1677c4990882177b5486d11ff194c67f6cd/src/ReverseProxy/Utilities/IsExternalInit.cs

We can look at adding extra constructors here as well. (#838)

**Comment by freemstr** [comment] 2021-03-15 03:30
@Tratcher 
Thank you

**Comment by Tratcher** [comment] 2021-03-15 15:43
@freemstr Do you plan to use the 5.0 SDK or the new constructors?

**Comment by freemstr** [comment] 2021-03-19 17:33
@Tratcher
I will not be using 5.0 in production, currently on 3.1 LTS
Waiting for 6.* LTS

Thank you for the fix

**Comment by Tratcher** [comment] 2021-03-19 17:53
Re-opening since the triage decision was not to add the constructors unless we confirmed someone was blocked. It sounds like you would be blocked without them.

**Comment by freemstr** [comment] 2021-03-22 16:38
Thank you,
I would prefer not to resort to reflection to set the value.

**Comment by karelz** [comment] 2021-03-23 19:22
@freemstr can you please explain why you cannot use 5.0 SDK -- i.e. NOT in production, just at build time. Is that truly a problem for you?
If yes, why?

**Comment by freemstr** [comment] 2021-03-24 20:01
@karelz 
Not that I CANNOT on my machine, why should a user be forced to do that?
I am not writing a hello wolrd project, I am evaluating this product for future use in production. Internal guidelines etc...
The question is why is 5.0 requirement when 3.1 is the LTS currently. Will this change after 1.0 release?
Imagine having to move multiple LOB code bases and train developers to C#9 just to reference one package.
This falls under cost/benefit and time constraints.
I appreciate the effort that goes into expanding Microsoft code offerings, but it seems to cater to greenfield exclusively with expectation of all latest versions of everything.
My point is that anything that comes out of beta (realizing that this project is still in beta) should be available to all LTS platfoms or LTS becomes a pointless designation.
I am just trying to understand why you hesitate to make this library usable from 3.1 code base, it would presumably simplify adoption.

**Comment by Tratcher** [comment] 2021-03-24 21:13
YARP is independent of .NET Core and its support lifecycles, LTS is about patching, not new features. After 1.0 we anticipate shifting our development efforts from .NET Core 3.1 to .NET 6, the next LTS release. If people can use the 5.0 SDK for YARP 1.0 then that saves us the effort of temporarily enabling the 3.1 SDK, and allows us to invest more in other YARP features.

**Comment by freemstr** [comment] 2021-03-25 02:53
@Tratcher 
I understand your position and will wait until release to see what happens with the project.
Maybe someone seconds this request.
In my understaing a constructor overload was not a big ask that would have to be reverted but it is up to your team to decide.

**Comment by karelz** [comment] 2021-03-30 08:34
@freemstr 
> In my understaing a constructor overload was not a big ask that would have to be reverted but it is up to your team to decide.

We also want to optimize for not polluting public API with constructs which won't be relevant in ~6 months. If there is strong business need (more customers considering it a blocker), we can reconsider in future.
Moving to Backlog for now, waiting for more upvotes on the top post ...

**Comment by leastprivilege** [comment] 2021-04-06 12:34
I am using the 5.0 SDK but still get this error:

`StructuredTransformer.cs(74, 17): [CS8400] Feature 'init-only setters' is not available in C# 8.0. Please use language version 9.0 or greater.`

This happens when newing up a `RequestTransformContext`.

Copying the `IsExternalInit` to my project didn't help. Am I missing something?

**Comment by Tratcher** [comment] 2021-04-06 13:28
C#9 is still opt-in, you need to set the language version in your projects.
https://github.com/microsoft/reverse-proxy/blob/28f748a0836f826b1f0ccd5404e0e23873fb744e/Directory.Build.props#L9

**Comment by jaketyb** [comment] 2021-05-21 08:31
> @karelz
> Not that I CANNOT on my machine, why should a user be forced to do that?
> I am not writing a hello world project, I am evaluating this product for future use in production. Internal guidelines etc...
> The question is why is 5.0 requirement when 3.1 is the LTS currently. Will this change after 1.0 release?
> Imagine having to move multiple LOB code bases and train developers to C#9 just to reference one package.
> This falls under cost/benefit and time constraints.
> I appreciate the effort that goes into expanding Microsoft code offerings, but it seems to cater to greenfield exclusively with expectation of all latest versions of everything.
> My point is that anything that comes out of beta (realizing that this project is still in beta) should be available to all LTS platfoms or LTS becomes a pointless designation.
> I am just trying to understand why you hesitate to make this library usable from 3.1 code base, it would presumably simplify adoption.

We've just come up against this due to someone updating their visual studio, and we take your stance on this. We target 3.1 in production as it's LTS, and don't believe we should be forced to install a different version of the SDK on our build servers. So for now we're having to use an older VS version which doesn't force us to add the `<LangVersion>9.0</LangVersion>` tag into the csproj.

If you support 3.1 then it should not use C# 9.0 language features.

**Comment by karelz** [comment] 2021-07-20 18:22
Triage: This would mean large API surface changes. Given that we do not have large demand, we don't plan to do it.
Workarounds are available.

**Closed by karelz** 2021-07-20 18:22 UTC
Labels: Triage: Info Needed, Type: Bug
