### ISSUE TITLE
Refactoring to enable better A/B type scenarios

### ISSUE THREAD

**Issue by samsp-msft** [microsoft/reverse-proxy#809] opened 2021-03-03 18:56 UTC
Today Route, Cluster and Destination are sealed. They have a metadata collection which can be used to add dictionary data, but its not very good for more structured data #121.

Cluster Scenarios to consider:
1. Multiple clusters of destinations, where only a percentage of the traffic should be directed to the B cluster (or multiple clusters to handle different experiments)
2. Multiple clusters that traffic is routed to based on a factor in the request - often based on an indirect lookup such as customer in a database (with a local cache)

Destination scenarios to consider
1. Not all destinations are equal - some should get more load than others. Prioritization should be made based on geographic distance, pre-determined factors etc.
2. Backup destinations that should only be loaded if all other destinations have problems.

This means we need to be able to have multiple clusters for a route, and then have secondary data associated with that cluster to help choose - does this belong to the cluster and would apply across all routes, or as part of the route:cluster relationship

Destinations need to be able to have the metadata attached to the,

The current record types for the above are sealed and its not easy to replace the config file->memory serialization to be able to handle derivatives. Ideally you'd extend the config types, and the factory methods used to create them from config.

**Comment by Tratcher** [comment] 2021-03-03 19:38
Related: A/B https://github.com/microsoft/reverse-proxy/issues/126, and https://github.com/microsoft/reverse-proxy/issues/121 friendlier metadata.

How does this scale? E.g. How can A/B provide derived types for their scenarios, and another component like session affinity or load balancing provide their own types?

**Comment by samsp-msft** [comment] 2021-03-04 02:42
> How does this scale? E.g. How can A/B provide derived types for their scenarios, and another component like session affinity or load balancing provide their own types?

I would assume that all customization is done in the context of the proxy app, and so it's code can coordinate the changes across all the types - we shouldn't need a mixin capability for multiple independent additions.

**Comment by Tratcher** [comment] 2021-03-09 01:14
Design notes:
- Clusters already create a logical grouping of destinations, so it would be convenient to use them as the unit of A/B testing. You may also want to change settings like load balancing and protocol versions between groups.
- In config you'd keep the current cluster id field for simplicity, but add the ability to list alternate clusters by id.
- These additional clusters would want some metadata associated with them as input into the selection algorithm.

```
                    proxyPipeline.Use((context, next) =>
                    {
                        var proxyFeature = context.Features.Get<IReverseProxyFeature>();
                        var route = proxyFeature.RouteSnapshot;
                        // IReadOnlyDictionary<ClusterInfo, IDictionary<string, string>> alternates = route.AlternateClusters;

                        ClusterInfo cluster = PickCluster(context, route);

                        // Update ProxyFeature
                        proxyFeature.ClusterSnapshot = cluster.Config;
                        var state = cluster.DynamicState;
                        proxyFeature.AllDestinations = state.AllDestinations;
                        proxyFeature.AvailableDestinations = state.HealthyDestinations;

                        return next();
                    });
```

This could be built as a middleware where PickCluster was abstracted out as an interface like we do for load balancing.

**Comment by samsp-msft** [comment] 2021-03-15 17:15
@Tratcher - Can this be closed by #814?

**Comment by Tratcher** [comment] 2021-03-15 17:39
See https://github.com/microsoft/reverse-proxy/issues/809#issuecomment-793233000 for design notes from our last discussion. I think we should keep this open until we have real support for at least that model since it proposes config changes.

**Comment by karelz** [comment] 2021-03-22 19:50
Duplicate of #126

**Closed by karelz** 2021-03-22 19:50 UTC
Labels: Type: Idea
