### ISSUE TITLE
YARP with SignalR

### ISSUE THREAD

**Issue by TechAspirant** [microsoft/reverse-proxy#1170] opened 2021-07-29 12:00 UTC
I am using 'BasicYarpSample' to route to my AspNet core (.net 5.0) application with SignalR. The problem I am facing is I am getting 404 error for negotiate version. Below is the configuration file for reference.
When I change Path from '/Session1' to '{**catch-all}' everything works well.
I want to achieve scenario such as
http://x.x.x.x:5001/Session1 => http://y.y.y.y:6001/
http://x.x.x.x:5001/Session2 => http://z.z.z.z:6002/
I am working on windows platform with YARP package version 1.0.0-preview.12.*
```
{
  "Urls": "http://localhost:5000;https://localhost:5001",
  "Logging": {
    "LogLevel": {
      "Default": "Information",
      "Microsoft.Hosting.Lifetime": "Information"
    }
  },
  "ReverseProxy": {
    "Routes": {
      "minimumroute": {
        "ClusterId": "minimumcluster",
        "Match": {
           //"Path": "{**catch-all}"
           "Path": "/Session1"
        },
        "Transforms": [
          { "PathRemovePrefix": "/Session1" }
        ]
      }
    },
    "Clusters": {
      "minimumcluster": {
        "Destinations": {
          "example.com": {
            "Address": "http://x.x.x.x:6001/"
          }
        }
      }
    }
  }
}
```
![image](https://user-images.githubusercontent.com/40688461/127487564-e1c6e11f-ffbe-4c4f-a404-6965a3175f69.png)
![image](https://user-images.githubusercontent.com/40688461/127494015-ffc25624-1dc9-41ee-b1ad-e67355dfd1bf.png)

**Comment by Tratcher** [comment] 2021-07-29 15:45
Looks like your destination app doesn't know about the /session1 prefix so it generates links without it.

The recommendation is to pass the prefix to the destination as a header (X-Forwarded-Prefix) and to update the request PathBase in the destination app so that it can correctly generate links. See these examples:
https://docs.microsoft.com/en-us/aspnet/core/host-and-deploy/proxy-load-balancer?view=aspnetcore-5.0#deal-with-path-base-and-proxies-that-change-the-request-path

**Comment by TechAspirant** [comment] 2021-07-29 20:03
Thanks for the quick response.
I don't want /Session1 at the destination.
I have single aspnet core web application with signal R and I am starting multiple sessions of it with different port number.
I want to configure YARP such a way that If client 1 requests to proxy server http://x.x.x.x:5000/Session1 it should be forwarded to instance 1 http://y.y.y.y:6001 of my application.
If client 2 requests to proxy server http://x.x.x.x:5000/Session2 it should be forwarded to instance 2 http://z.z.z.z:6002 of my application.

What would be the configuration for such use case in YARP ? As in my case I have single application and I am running multiple instances of It.

**Comment by Tratcher** [comment] 2021-07-29 20:08
The problem is that after the first the request to /session1 the destination generates a url for /negotiate, which isn't a url you're proxying because it doesn't start with /session1. It needs to be /session1/negotiate.

The destination needs to generate urls that include /session1 in order for them to be routable through the proxy. The doc above explains how to do that by re-writing HttpContext.Request.PathBase to /Session1 on the destination.

**Comment by TechAspirant** [comment] 2021-07-29 20:12
So If I understood right I have to use and add Pathbase in my aspnet core signal R application right ?
Is their any way I can make this Pathbase dynamic such that at port 6001 Pathbase should be Session1 and for port 6002 Pathbase should be Session2.

**Comment by Tratcher** [comment] 2021-07-29 20:16
That's what the X-Forwarded-Prefix header is for. The proxy can set it to a different value on each route and the app can read it and update PathBase.

**Comment by TechAspirant** [comment] 2021-07-29 20:18
Ok, Thanks will give it a try and will revert you with my results.

**Comment by TechAspirant** [comment] 2021-07-29 20:31
Can you tell me how my YARP configuratiin will look like. Is my above shown configuration correct ?

**Comment by TechAspirant** [comment] 2021-07-30 10:23
With below appsettings.json in YARP I checked but It results into same error as above
```
{
  "Urls": "http://localhost:5000;https://localhost:5001",
  "Logging": {
    "LogLevel": {
      "Default": "Debug",
      "Microsoft.Hosting.Lifetime": "Debug"
    }
  },
  "ReverseProxy": {
    "Routes": {
      "Route1": {
        "ClusterId": "Cluster_01",
        "Match": {
           "Path": "/Session1"
        },
        "Transforms": [
          { "PathRemovePrefix": "/Session1" },
          {
            "RequestHeader": "X-Forwarded-Prefix",
            "Set": "Session1"
          }
        ]
      }
    },
    "Clusters": {
      "Cluster_01": {
        "Destinations": {
          "SignalRApplication": {
            "Address": "http://x.x.x.x:6001/"
          }
        }
      }
    }
  }
}
```

At application end I did something like this
```
        public void Configure(IApplicationBuilder app)
        {
            app.UseStaticFiles();

            app.Use(async (context, next) =>
            {
                if (context.Request.Headers.TryGetValue("X-Forwarded-Prefix", out var pathBase))
                {
                    context.Request.PathBase = new Microsoft.AspNetCore.Http.PathString(pathBase);

                    if (context.Request.Path.StartsWithSegments(context.Request.PathBase, out var path))
                    {
                        context.Request.Path = path;
                    }
                }

                await next();
            });

            app.UseRouting();

            app.UseEndpoints(endpoints =>
            {
                endpoints.MapRazorPages();
                endpoints.MapHub<Chat>($"/{nameof(Chat)}");
            });
        }
```

Can you tell me what mistake I made ?

**Comment by Tratcher** [comment] 2021-07-30 19:40
Try this:

```
{
  "Urls": "http://localhost:5000;https://localhost:5001",
  "Logging": {
    "LogLevel": {
      "Default": "Debug",
      "Microsoft.Hosting.Lifetime": "Debug"
    }
  },
  "ReverseProxy": {
    "Routes": {
      "Route1": {
        "ClusterId": "Cluster_01",
        "Match": {
           "Path": "/Session1/{**catch-all}"
        },
        "Transforms": [
          { "PathRemovePrefix": "/Session1" },
          {
            "RequestHeader": "X-Forwarded-Prefix",
            "Set": "/Session1"
          }
        ]
      }
    },
    "Clusters": {
      "Cluster_01": {
        "Destinations": {
          "SignalRApplication": {
            "Address": "http://x.x.x.x:6001/"
          }
        }
      }
    }
  }
}
```

At application end I did something like this
```
        public void Configure(IApplicationBuilder app)
        {
            app.UseStaticFiles();

            app.Use((context, next) =>
            {
                if (context.Request.Headers.TryGetValue("X-Forwarded-Prefix", out var pathBase))
                {
                    context.Request.PathBase = pathBase.ToString();
                }

                return next();
            });

            app.UseRouting();

            app.UseEndpoints(endpoints =>
            {
                endpoints.MapRazorPages();
                endpoints.MapHub<Chat>($"/{nameof(Chat)}");
            });
        }
```

**Comment by TechAspirant** [comment] 2021-07-31 06:36
@Tratcher Same Issue. Seems header is not added in the request.
Below image is for the reference.

![image](https://user-images.githubusercontent.com/40688461/127731016-0d800f50-5d46-47cd-9d19-ca03bf86811d.png)

![image](https://user-images.githubusercontent.com/40688461/127731055-9ce70f9d-afb0-430b-be1a-cedcb894401d.png)

Also, I am attaching a link to my application to reproduce the issue
YARP Application : https://drive.google.com/file/d/1KxZAnQWBW0roXXwxziXyeTE_PIhjVBg_/view?usp=sharing
SignalR Application : https://drive.google.com/file/d/1L06WayboeAj4oOA3Vwje5pKCjpeHAjsE/view?usp=sharing

**Comment by TechAspirant** [comment] 2021-08-02 10:25
@Tratcher It was reproduced with the sample application I shared ?

**Comment by Tratcher** [comment] 2021-08-02 16:07
Request headers added by the proxy would not show up in the client dev tools, the browser can only see the headers the request client originally added. You'd have to log the headers as received by the destination server.

**Comment by TechAspirant** [comment] 2021-08-02 16:13
Means x-forwarded-* header are comming by the proxy at destination server or application but are not logged.
Can you give an example how can I log the x forwarded headers at destinaton and use it in JavaScript for signalR client connection builder

**Comment by Tratcher** [comment] 2021-08-02 16:19
Start with the troubleshooting steps for getting the right headers and paths on the destination server:
https://docs.microsoft.com/en-us/aspnet/core/host-and-deploy/proxy-load-balancer?view=aspnetcore-5.0#troubleshoot

**Comment by TechAspirant** [comment] 2021-08-02 16:22
Ok, this changes I have to do at my aspnet core signalR  application side make sure that x forwarded headers are logged at the application end right ?

**Comment by samsp-msft** [comment] 2021-08-02 19:27
Yes. The problem you are facing is that the URLs sent by the client are different from what will be seen by the server. Although YARP will massage the incoming URLs for requests, it doesn't modify the body that is returned to the client that may include subsequent URLs. If they are relative paths, it should be ok, if they are absolute then they need to be correct to pass through the proxy.

What @Tratcher is suggesting is that in the SignalR app, for it to know the correct URLs to pass back to the client, to use the X-Forwarded-Prefix to tell it that the URL prefix that is needed. That will then need to be programmatically added (by you) to any URLs that are sent back to the client. 

If you are using the console logger in your signalR app, then putting 

```JSON
  //Sets the Logging level for ASP.NET
  "Logging": {
    "LogLevel": {
      "Default": "Information",
      // Uncomment to hide diagnostic messages from runtime and proxy
      // "Microsoft": "Warning",
      "Microsoft.Hosting.Lifetime": "Information"
    }
  },
``` 
in your appsettings.json for the SignalR project should mean that it'll show the incoming URLs as part of the log.

**Comment by TechAspirant** [comment] 2021-08-03 12:54
@Tratcher and @samsp-msft I was able to log the x-forwarded-* header at the destination side.
In order to change the SignalR client connection url dynamically from the value of x-forwarded-* header. I did something like below at signalR application side. Is this a good idea ? Or we can do something else ?
```
			app.Use((context, next) =>
			{
				if (context.Request.Headers.TryGetValue("X-Forwarded-For", out var originalIpAddress))
				{
					context.Response.Headers.Add("IpAddress", originalIpAddress);
				}
				if (context.Request.Headers.TryGetValue("X-Forwarded-Port", out var originalPortNumber))
				{
					context.Response.Headers.Add("PortNumber", originalPortNumber);
				}
				return next();
			});
```
```
<script>
    var host = window.location.host;
	var req = new XMLHttpRequest();
	req.open('GET', document.location, false);
	req.send(null);
	var headers = getResponseHeaderMap(req);
	var url = "http://" + headers['ipaddress'] + ":" + headers['portnumber'];
    const connection = new signalR.HubConnectionBuilder()
        .withUrl(url + "/Chat")
        .configureLogging(signalR.LogLevel.Information)
        .build();
    connection.start().catch(err => console.error(err.toString()));
</script>
```

**Comment by Tratcher** [comment] 2021-08-03 16:20
@BrennanConroy Shouldn't the original host and port already be accessible from the client?

@TechAspirant the rest of this thread had been about fixing the request path. Was the path not your problem?

**Comment by TechAspirant** [comment] 2021-08-03 16:27
@Tratcher  error 404 was resolved once I passed absolute path insted of relative path at signal r client connection.
Is the above approach correct ?
(Binding x forwarded headers to context response)

**Comment by BrennanConroy** [comment] 2021-08-03 16:41
> Shouldn't the original host and port already be accessible from the client?

Not sure I understand the question, the user passes us a URL so they know the original host and port, we don't expose any API to get that information back from the client.

**Comment by Tratcher** [comment] 2021-08-03 16:43
Shouldn't they be able to get the url of the current page from the browser and use the host and port from that?

**Comment by TechAspirant** [comment] 2021-08-03 17:04
I my case, signalR client connection builder expects th original IP address not the current url which is nothing but of proxy.

**Comment by BrennanConroy** [comment] 2021-08-05 17:22
Looking at your network trace screenshot, it seems like you're missing the /Session1 path segment from the SignalR requests, do you just need to put "/Session1/Chat" as the url in the HubConnectionBuilder?

**Comment by TechAspirant** [comment] 2021-08-06 12:19
@BrennanConroy I managed to put "/Session1/Chat" as the url in the HubConnectionBuilder using x-forwarded-prefix header.

**Comment by samsp-msft** [comment] 2021-08-19 16:50
> @BrennanConroy I managed to put "/Session1/Chat" as the url in the HubConnectionBuilder using x-forwarded-prefix header.

It looks like you have resolved the problem, closing. Please re-open if there is still a problem.

**Closed by samsp-msft** 2021-08-19 16:50 UTC
Labels: Type: Discussion
