### ISSUE TITLE
Static files/directory config for appsettings.json

### ISSUE THREAD

**Issue by xXBuilderBXx** [microsoft/reverse-proxy#904] opened 2021-04-09 03:43 UTC
Add support for configuring static files/directories with appsettings.json just like how nginx allows it.

The key can be default `Address` or it could be named `Path` to seperate it.
Nginx also allows to specify an index file like `index index.html;` this could also be used as another value `"Index": "index.html"`

```json
"ReverseProxy": {
    "Routes": [
      {
        "RouteId": "route1",
        "ClusterId": "cluster1",
        "Match": {
          "Path": "{**catch-all}"
        }
      }
    ],
    "Clusters": {
      "cluster1": {
        "Destinations": {
          "cluster1/destination1": {
            "Address": "/linux/path/here/"
          }
        }
      }
    }
  }
```

**Comment by Tratcher** [comment] 2021-04-09 16:40
Duplicate of #187

This is tangential to YARP's primarily concern as a library for routing to external sources. We do consider static file config important in the pre-built exe scenario that would be comparable to nginx.

I don't envision this as being part of the cluster config, none of the cluster settings make sense for static assets. I expect it would use a different config section entirely.

**Comment by samsp-msft** [comment] 2021-04-09 19:15
What is missing here (possibly more from asp.net than Yarp) is a standard config section for configuring static files. In the same way that you add the config provider to Yarp, it would nice to be able to specify a config section that would map to a [StaticFileOptions](https://docs.microsoft.com/en-us/dotnet/api/microsoft.aspnetcore.builder.staticfileoptions?view=aspnetcore-5.0) instance enabling the configuration of folders, headers, auth, content types etc from config rather than code.

Not that difficult to write, but probably not a high priority for Yarp v1.

**Comment by karelz** [comment] 2021-04-22 17:19
Duplicate of #187

**Closed by karelz** 2021-04-22 17:19 UTC
Labels: Type: Idea
