### ISSUE TITLE
Custom TLS cert validation when connecting to Destinations

### ISSUE THREAD

**Issue by davidni** [microsoft/reverse-proxy#253] opened 2020-06-18 18:36 UTC
### What should we add or change to make your life better?
High-stakes deployments of YARP require explicit control of TLS cert validation policies when communicating to a Backend's endpoint (aka `Cluster`'s `Destination` after https://github.com/microsoft/reverse-proxy/issues/128).

#### Requirements:
* Ability to specify `SocketsHttpHandler.SslClientAuthenticationOptions.RemoteCertificateValidationCallback` per backend
* Ability for that to be set up to depend on Backend config. Internally, we have an implementation that works efficiently using `Signals`
   * When a backend's config changes, a derived signal produces a new cert validation callback lambda
    * In the hot-path, cert validation just calls the latest validation lambda produced by the signal, which always tracks the backend config

### Why is this important to you?
Compliance requirement. YARP isn't an option for us without this.

**Comment by Tratcher** [comment] 2020-06-18 19:24
This is tracked as part of https://github.com/microsoft/reverse-proxy/issues/137. I'll copy your comments over and close this.

**Closed** 2020-06-18 23:00 UTC
Labels: Type: Idea

**Comment by karelz** [comment] 2021-03-24 20:22
Duplicate of #137
