### ISSUE TITLE
Add annotation for Methods match

### ISSUE THREAD

**Issue by witskeeper** [microsoft/reverse-proxy#2378] opened 2024-01-18 06:51 UTC
### What should we add or change to make your life better?

Ingress Controller support Host, Path, Header but Methods match.

see: <https://github.com/microsoft/reverse-proxy/blob/main/src/Kubernetes.Controller/Converters/YarpParser.cs#L133>

### Why is this important to you?

add Methods match will make the functionality more comprehensive.

**Comment by MihaZupan** [comment] 2024-01-18 15:05
Looks like a duplicate of #1828?

**Comment by adityamandaleeka** [comment] 2024-01-23 18:18
Yup, closing this as a duplicate.

**Closed by adityamandaleeka** 2024-01-23 18:18 UTC
Labels: Type: Idea, Kubernetes Ingress Controller
