### ISSUE TITLE
Policy for what to do if all destinations are unhealthy

### ISSUE THREAD

**Issue by samsp-msft** [microsoft/reverse-proxy#992] opened 2021-05-11 04:38 UTC
If the result of health checks is that all destinations are unhealthy, then what should YARP do?

Currently we reject the request
An alternative would be to have panic routing and to pick a destination.

Should we have the concept of backup destinations which are used when the primary(ies) are unhealthy?

**Comment by karelz** [comment] 2021-05-13 17:29
Duplicate of #83

**Closed by karelz** 2021-05-13 17:29 UTC
Labels: Type: Feedback
