### ISSUE TITLE
Unknown transform: ResponseHeaderRemove

### ISSUE THREAD

**Issue by heikkilamarko** [microsoft/reverse-proxy#1141] opened 2021-07-06 06:19 UTC
```
// appsettings.json

"ReverseProxy": {
  "Routes": {
    "TodoApp": {
      "ClusterId": "TodoApp",
      "Match": {
        "Path": "{**catch-all}",
        "Methods": [
          "GET",
          "POST",
          "PUT",
          "DELETE"
        ]
      },
      "Transforms": [
        {
          "ResponseHeaderRemove": "Server",
          "When": "Always"
        }
      ]
    },
```

The above configuration gives the following exception (Unknown transform: ResponseHeaderRemove):

`System.InvalidOperationException: Unable to load or apply the proxy configuration.\n ---> System.ArgumentException: Unknown transform: ResponseHeaderRemove;When\n   at Yarp.ReverseProxy.Transforms.Builder.TransformBuilder.BuildInternal(RouteConfig route, ClusterConfig cluster)\n   at Yarp.ReverseProxy.Transforms.Builder.TransformBuilder.Build(RouteConfig route, ClusterConfig cluster)\n   at Yarp.ReverseProxy.Management.ProxyConfigManager.BuildRouteModel(RouteConfig source, ClusterState cluster)\n   at Yarp.ReverseProxy.Management.ProxyConfigManager.UpdateRuntimeRoutes(IList1 incomingRoutes)\n   at Yarp.ReverseProxy.Management.ProxyConfigManager.ApplyConfigAsync(IProxyConfig config)\n   at Yarp.ReverseProxy.Management.ProxyConfigManager.InitialLoadAsync()\n   --- End of inner exception stack trace ---\n   at Yarp.ReverseProxy.Management.ProxyConfigManager.InitialLoadAsync()\n   at Microsoft.AspNetCore.Builder.ReverseProxyIEndpointRouteBuilderExtensions.GetOrCreateDataSource(IEndpointRouteBuilder endpoints)\n   at Microsoft.AspNetCore.Builder.ReverseProxyIEndpointRouteBuilderExtensions.MapReverseProxy(IEndpointRouteBuilder endpoints, Action1 configureApp)\n   at Microsoft.AspNetCore.Builder.ReverseProxyIEndpointRouteBuilderExtensions.MapReverseProxy(IEndpointRouteBuilder endpoints)\n   at ApiGateway.Startup.<>c.<Configure>b__5_0(IEndpointRouteBuilder endpoints) in /src/ApiGateway/Startup.cs:line 68\n   at Microsoft.AspNetCore.Builder.EndpointRoutingApplicationBuilderExtensions.UseEndpoints(IApplicationBuilder builder, Action1 configure)\n   at ApiGateway.Startup.Configure(IApplicationBuilder app, IWebHostEnvironment env) in /src/ApiGateway/Startup.cs:line 68\n   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor, Boolean wrapExceptions)\n   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)\n   at Microsoft.AspNetCore.Hosting.ConfigureBuilder.Invoke(Object instance, IApplicationBuilder builder)\n   at Microsoft.AspNetCore.Hosting.ConfigureBuilder.<>c__DisplayClass4_0.<Build>b__0(IApplicationBuilder builder)\n   at Microsoft.AspNetCore.Hosting.GenericWebHostBuilder.<>c__DisplayClass15_0.<UseStartup>b__1(IApplicationBuilder app)\n   at Microsoft.AspNetCore.HostFilteringStartupFilter.<>c__DisplayClass0_0.<Configure>b__0(IApplicationBuilder app)\n   at Microsoft.AspNetCore.Hosting.GenericWebHostService.StartAsync(CancellationToken cancellationToken)\n   at Microsoft.Extensions.Hosting.Internal.Host.StartAsync(CancellationToken cancellationToken)\n   at Microsoft.Extensions.Hosting.HostingAbstractionsHostExtensions.RunAsync(IHost host, CancellationToken token)\n   at Microsoft.Extensions.Hosting.HostingAbstractionsHostExtensions.RunAsync(IHost host, CancellationToken token)\n   at Microsoft.Extensions.Hosting.HostingAbstractionsHostExtensions.Run(IHost host)\n   at ApiGateway.Program.Main(String[] args) in /src/ApiGateway/Program.cs:line 24`

Version:

```
<PackageReference Include="Yarp.ReverseProxy" Version="1.0.0-preview.12.21328.2" />
```

**Comment by mkeenanpaycor** [comment] 2021-07-06 13:06
The problem is line 184 in this file:

https://github.com/microsoft/reverse-proxy/blob/release/1.0.0-preview12/src/ReverseProxy/Transforms/ResponseTransformFactory.cs

The if check should be on "ResponseHeaderRemoveKey" instead of "ResponseHeaderKey" (which is in the `if` statement on line 132).

Workaround:  Use the old configuration format of setting the response header to empty string.

**Comment by Tratcher** [comment] 2021-07-06 15:47
Thanks, this is being fixed by https://github.com/microsoft/reverse-proxy/pull/1137/files#diff-15d50e771fee2b0178b4042b91f5415cb90f6c40f4b0a0161f258c8b36dfe86dR194.

**Comment by eric-jiang** [comment] 2021-07-14 15:37
I'm getting the same error. Hope this can be released soon.

**Comment by Tratcher** [comment] 2021-07-14 20:29
The fix has been merged and should be available from our rolling builds:
https://github.com/microsoft/reverse-proxy/blob/main/docs/DailyBuilds.md

**Closed by Tratcher** 2021-07-14 20:29 UTC
Labels: Type: Bug
