### ISSUE TITLE
W3C Trace propagation via ReverseProxy

### ISSUE THREAD

**Issue by chandramouleswaran** [microsoft/reverse-proxy#351] opened 2020-07-27 16:51 UTC
### What should we add or change to make your life better?
To start off - this project is awesome. I have been experimenting with this and GRPC bi-directional streaming works like a charm. For our use case, we would like to get the distributed traces emitted correctly. Today, ASP .NET Core + HttpClient make this happen seamlessly.

I think the problem is the client factory is using SocketsHttpHandler and it does not support passing trace context automatically.
https://github.com/dotnet/runtime/issues/31261

Instead, if this changes to HttpClientHandler - we would end up getting the headers injected to visualize an E2E trace via the Reverse proxy. (May be - I am not very familiar with the code but this was the one which stood out)

### Why is this important to you?
This is important for cases where we have to understand the calling pattern across multiple microservices in our environment.

Please let me know if this is a good idea to try out - if so, I can help out with the PR to make this change as well.

**Comment by Tratcher** [comment] 2020-07-27 18:01
Yeah, we'll get this sorted out either as part of https://github.com/microsoft/reverse-proxy/issues/137, or by directly fixing dotnet/runtime#31261.

**Comment by samsp-msft** [comment] 2020-07-29 19:07
Duplicate of #292

**Closed by samsp-msft** 2020-07-29 19:07 UTC
Labels: Type: Idea
