### ISSUE TITLE
Kubernetes Controller Nuget Package

### ISSUE THREAD

**Issue by HappyCodeSloth** [microsoft/reverse-proxy#2233] opened 2023-08-29 14:41 UTC
### What should we add or change to make your life better?

Publish the Yarp.Kubernetes.Controller as a Nuget Package. 

### Why is this important to you?

It will enable me to consumer this within my application.

**Comment by MihaZupan** [comment] 2023-08-30 16:25
Related (duplicate of): #2134, #1640, #1254

Would you be okay with consuming builds from the nightly feed for the time being? (assuming we fix #2134 soon)

**Closed by MihaZupan** 2023-08-30 16:25 UTC
Labels: Type: Idea, Kubernetes Ingress Controller
