### ISSUE TITLE
[WebMethod] can't be invoked when body is empty

### ISSUE THREAD

**Issue by rayao** [microsoft/reverse-proxy#875] opened 2021-03-25 02:31 UTC
### Describe the bug

I'm not sure if this is a bug, but it does break existing usage.
When client invokes [WebMethod] in an aspx page, the request is HTTP POST, client side set Content-Type header to "application/json" which is required to invoke WebMethod, but client side send an empty body, in which case the YARP proxy HttpRequestMessage omit the Content-Type header, but this will make the WebMethod invocation return aspx page itself (instead of actually call the WebMethod), which breaks client.
If the body is not empty, everything works fine.
I don't know if this is by design, seems to me HTTP POST without a body and Content-Type set to "application/json" is kind of violating protocol.

Currently I use a transformer to workaround:
```
        public static HttpRequestMessage WorkaroundEmptyContentWebMethod(this HttpRequestMessage obj, HttpRequest request)
        {
            if (obj.Content == null && obj.Method == HttpMethod.Post)
            {
                if (request.ContentType != null)
                {
                    // MUST set ContentType null, so YARP will copy it from original request
                    obj.Content = new StringContent(string.Empty);
                    obj.Content.Headers.ContentType = null;
                }
            }

            return obj;
        }
```

### To Reproduce
Just HTTP POST (proxy it with YARP of course) to a [WebMethod] in an aspx page, and with no body.

### Further technical details

- 1.0.0-preview.8.21065.1
- Windows x64

**Comment by karelz** [comment] 2021-03-29 18:53
Duplicate of #618

**Closed by karelz** 2021-03-29 18:53 UTC
Labels: Type: Bug

**Comment by Tratcher** [comment] 2021-03-29 22:01
> I don't know if this is by design, seems to me HTTP POST without a body and Content-Type set to "application/json" is kind of violating protocol.

It is a little weird for an application/json body to not include at least the bounding brackets `{ }`. Regardless, this is a situation we should handle better.
