### ISSUE TITLE
YARP to combine with load balancing

### ISSUE THREAD

**Issue by VenkateshSrini** [microsoft/reverse-proxy#656] opened 2021-01-10 02:55 UTC
### What should we add or change to make your life better?
I would like YARP to add a Load balancing facility. It can be thought of in two format
1) One is Canary deployment, where we can say we need 80% traffic to the old route and 20% to the new one.
2) Unirfomly distribute load using round-robin method across routes

### Why is this important to you?
1) In Kubernetes deployment we can use this easily. Otherwise, just for such a small requirement, we need to install cluster wide service mesh. As we all understand Service Mesh is complex.

**Comment by Tratcher** [comment] 2021-01-11 04:09
> 1. One is Canary deployment, where we can say we need 80% traffic to the old route and 20% to the new one.

This is tracked under A/B testing at https://github.com/microsoft/reverse-proxy/issues/126

> 2\. Unirfomly distribute load using round-robin method across routes

Load balancing is enabled by default, and round-robin is one of the options. The default load balancing algorithm is PowerOfTwoChoices since it is both very quick and simple but still quite good at distributing load. Round-robin assumes all requests are of equal cost, it doesn't take into account any backlog that builds up on a given node.

https://github.com/microsoft/reverse-proxy/blob/58da96ac17d6cb7a236983f8aec54be9cbf7f396/src/ReverseProxy/Service/LoadBalancing/PowerOfTwoChoicesLoadBalancingPolicy.cs#L30-L31

**Comment by karelz** [comment] 2021-02-11 18:23
Duplicate of #126

**Closed by karelz** 2021-02-11 18:23 UTC
Labels: Type: Idea
