### ISSUE TITLE
Claims mapping in YARP

### ISSUE THREAD

**Issue by jmezach** [microsoft/reverse-proxy#610] opened 2020-12-09 15:52 UTC
### What should we add or change to make your life better?
We've been using YARP as an API Gateway in production for a couple of weeks now and it is going great so far. One of the additions we've been making is adding some infrastructure to allow the mapping of incoming claims to some other format or structure before the request is forwarded to the downstream service. We took some inspiration from the policy based authorization in ASP.NET Core in that you can configure a claims mapping policy at the cluster level (currently as metadata there) and then configure that policy to perform various mappings. It is still very early in development, but we were wondering if this is something that could benefit YARP.

### Why is this important to you?
One of our main reasons for building an API Gateway using YARP is to be able to switch out our current rather old authentication mechanism for something more modern. This will also require us to do some mapping of an old authorization model to a new one, hence why we are building this. We also believe that it makes sense for various services to have different requirements in how they receive claims, etc.

**Comment by Tratcher** [comment] 2020-12-15 18:16
Related: https://github.com/microsoft/reverse-proxy/discussions/375

**Comment by karelz** [comment] 2020-12-17 18:08
Triage: We need cookbook for auth demonstrating how to do things.

**Comment by karelz** [comment] 2020-12-17 18:09
Duplicate of #416

**Closed by karelz** 2020-12-17 18:09 UTC
Labels: Type: Idea

**Comment by Tratcher** [comment] 2021-02-08 17:43
See https://github.com/microsoft/reverse-proxy/issues/416#issuecomment-775318003 for updates here.
