### ISSUE TITLE
Proxy configuration is extensible for custom metadata on routes, destinations etc

### ISSUE THREAD

**Issue by alnikola** [microsoft/reverse-proxy#485] opened 2020-10-22 13:00 UTC
There are several `*Options` types specifying parameters of different providers and policies like `CookieSessionAffinityProviderOptions`, `ConsecutiveFailuresHealthPolicyOptions`, `TransportFailureRateHealthPolicyOptions` etc. In the essence, they are part of the YARP configuration, but currently it's not possible to define them through the generic config provider mechanism. They can be set and changed through code only. There are some ad hoc workarounds to this issue created for some scenarios (e.g. health check policies), but there is a solid need for a well designed `*Options` configuration mechanism.

We should design and implement a proper `*Options` configuration subsystem.

**Comment by davidfowl** [comment] 2020-10-22 13:02
Right, configuration metadata is a bit of a hack in how it gets manifested as a strongly typed object. We should have a system where configuration metadata is properly represented as a strongly typed object for consumption when various components are manifested.

**Comment by samsp-msft** [comment] 2022-05-17 19:56
Duplicate of #1709

**Closed by samsp-msft** 2022-05-17 19:56 UTC
Labels: Type: Enhancement, Type: Idea, User Story, Priority:1
