### ISSUE TITLE
[Investigation] Reducing allocations in HttpClient

### ISSUE THREAD

**Issue by anurse** [microsoft/reverse-proxy#64] opened 2020-04-16 16:10 UTC
We believe there are some gains to be found in reducing allocations in HttpClient, particularly for proxy scenarios where it may be reasonable to bypass header validation and other HttpClient features designed for more general-purpose use cases.

**Comment by anurse** [comment] 2020-04-16 16:11
@stephentoub I created this to track the work you're looking at. Feel free to edit/adjust as desired to appropriately match what you're looking at!

**Comment by karelz** [comment] 2021-03-24 19:33
Duplicate of https://github.com/dotnet/runtime/issues/35126

**Closed by karelz** 2021-03-24 19:33 UTC
