### ISSUE TITLE
Replace ProxyHttpClientFactory and ProxyHttpClientFactoryFactory implementations

### ISSUE THREAD

**Issue by DaneRushton** [microsoft/reverse-proxy#283] opened 2020-07-02 00:27 UTC
Hi,

I'd like to provide custom DelegatingHandler's into the HttpMessageInvoker chain used by the Proxy.
Easiest way would be for me to provide my own implementations of ProxyHttpClientFactory and ProxyHttpClientFactoryFactory which wrap the SocketsHttpHandler in whatever I need, however they are both marked as internal. Has there been any thought to making these public, or providing a mechanism for registering a Handler Factory?

Thanks
Dane

**Comment by Tratcher** [comment] 2020-07-02 01:05
Yes, we need to make the outgoing client more configurable. That's tracked by https://github.com/microsoft/reverse-proxy/issues/137, and I've added a note about DelegatingHandlers.

What did you plan on doing in the DelegatingHandler? Is it something that could be handled by Transforms instead? https://microsoft.github.io/reverse-proxy/articles/transforms.html

**Comment by samsp-msft** [comment] 2020-07-02 18:40
Duplicate of #137

**Closed by samsp-msft** 2020-07-02 18:40 UTC
Labels: Resolution: Duplicate
