### ISSUE TITLE
Possibillity to implement custom logic to decide the backend for a request.

### ISSUE THREAD

**Issue by saithis** [microsoft/reverse-proxy#135] opened 2020-05-02 21:30 UTC
### What should we add or change to make your life better?

The possibillity to implement custom logic to decide the backend for a request. 

### Why is this important to you?

We currently have a custom build reverse proxy, which proxies urls in the format https://{customer-slug}.our-domain.com/{product-name}/{some-path} to our backend servers. The proxy looks up which customer has this {customer-slug} and which version of the product the customer has. Then it looks up under which url this product and version combination is available and calls this url with {some-path} (but without {product-name}, that is only forwarded in a header) and also appends the customer id and some other stuff as a header.

We cache the lookup which version of the product the customer has, but one requiredment is, that we can bust this cache anytime and also circumvent this cache for specific requests.

We could solve the product part by adding a new backend per product version. But from looking at the other issues and discussions I wasn't sure if the rest would be possible.

The reason why it could be interesting for us to use YARP insteand of our custom reverse proxy is, that our proxy can't load balance. Currently we need to have a load balancer between the proxy and the backends.

**Comment by Tratcher** [comment] 2020-05-02 22:27
This sounds a lot like #8.

**Comment by saithis** [comment] 2020-05-03 12:08
#8 sounds more like a way to create routes outside of a request context, which the proxy then uses for all requests. 

What we would need is a way to intercept a request and modify the proxy config before the request would be processed. Because while updating a customer to a new version the update script makes some api calls and there is a specific point between 2 requests where we have to make sure, that all following api calls go to the new backend. But now that I think about it a bit more, this could maybe be done in a middleware before the proxy, if the proxy has a method that triggers a config update and can be awaited.

**Comment by Tratcher** [comment] 2020-05-04 17:08
Ah, I'd been doing more research and prototyping around #8 but hand't posted my notes yet. They're posted now. Yes, we do need a variant that can look up routes from a database per request, and it would likely be a separate middleware that would replace routing.

**Comment by karelz** [comment] 2020-05-07 18:48
Duplicate of #8

**Closed by karelz** 2020-05-07 18:48 UTC
Labels: Type: Idea
