### ISSUE TITLE
System.NotSupportedException: Unsupported request method 'CONNECT'. after switching to .net 7

### ISSUE THREAD

**Issue by vmachacek** [microsoft/reverse-proxy#1973] opened 2022-12-21 05:04 UTC
### Describe the bug
I'm proxying angular dev server to simulate production environment during development. After switching to .net 7 websocket exception stopped working. When I revert it and target .net 6 it starts to work again

### To Reproduce
Setup Yarp to proxy angular dev server version 13.3.3
Run the project with .net 6, everything works 
Switch project to .net 7
See the exception and web-socket connection stops working

Got Exceptions? Include both the message and the stack trace
```
Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware[1]
      An unhandled exception has occurred while executing the request.
      System.NotSupportedException: Unsupported request method 'CONNECT'.
         at Yarp.ReverseProxy.Forwarder.RequestUtilities.GetHttpMethod(String method)
         at Yarp.ReverseProxy.Forwarder.HttpForwarder.CreateRequestMessageAsync(HttpContext context, String destinationPrefix, HttpTransformer transformer, ForwarderRequestConfig requestConfig, Boolean isStreamingRequest, ActivityCancellationTokenSource activity
Token)
         at Yarp.ReverseProxy.Forwarder.HttpForwarder.SendAsync(HttpContext context, String destinationPrefix, HttpMessageInvoker httpClient, ForwarderRequestConfig requestConfig, HttpTransformer transformer)
         at Yarp.ReverseProxy.Forwarder.ForwarderMiddleware.Invoke(HttpContext context)
         at Yarp.ReverseProxy.Health.PassiveHealthCheckMiddleware.Invoke(HttpContext context)
         at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
         at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
         at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddlewareImpl.Invoke(HttpContext context)

```

### Further technical details
- Yarp.ReverseProxy version 1.1.1
- Windows platform

**Comment by Tratcher** [comment] 2022-12-21 17:25
Duplicate of https://github.com/microsoft/reverse-proxy/issues/1375#issuecomment-1312688381, see the linked issue for a workaround.

**Closed by Tratcher** 2022-12-21 17:25 UTC
Labels: Type: Bug
