### ISSUE TITLE
Proxy fails with HPackEncodingException: "The given buffer was too small to encode any headers"

### ISSUE THREAD

**Issue by davidni** [microsoft/reverse-proxy#693] opened 2021-01-25 22:24 UTC
### Describe the bug
Proxy fails and an `HPackEncodingException` bubbles out with message `"The given buffer was too small to encode any headers"`.

### Expectation
Any response that can be successfully received by YARP from a destination, should also be forwarded successfully to the client. If there are cases where this is deliberately not supported, perhaps due to HTTP/2 settings affecting each hop, it would help to document what those cases are and what constraints are sufficient for successful proxying.

### To Reproduce
No live repro unfortunately. This is likely caused by attempting to proxy a large response header and/or response trailer.

### Further technical details
The exception is thrown from here: https://github.com/dotnet/aspnetcore/blob/v3.1.11/src/Servers/Kestrel/Core/src/Internal/Http2/HPack/HPackEncoder.cs#L48

- Include the version of the packages you are using: .NET Core 3.1.402
- The platform: Windows

**Comment by Tratcher** [comment] 2021-01-25 22:47
- Needs a repro
- Does this also repro on 5.0? The Kestrel encoder code has changed.
- That error probably indicates that one response header was larger than the client's HTTP/2 frame size limit. The encoder could adapt to this but it adds complexity and hasn't been an issue to date.
- Possible reasons for a mismatch between receiving the header from HttpClient and sending it with Kestrel:
  - Different frame size limits for the client and destination. This is a hop-by-hop client setting.
  - Compression differences. HttpClient supports all decompression types but Kestrel 3.1 did minimal response header compression.
  - The proxy request to the destination was using HTTP/1.1 (probably not in this environment)

**Comment by sreejit-a** [comment] 2021-01-26 17:36
From what we could observe, this error is also causing all concurrent executions on the same connection with the client to be dropped. We have a grpc client and all concurrent requests receive a "Stream Removed" message.

So, a single back end returning a large response trailer can cause the entire client connection to be dropped. Is this expected? Shouldn't the error impact only that particular call?

**Comment by Tratcher** [comment] 2021-01-26 17:40
This is expected because the error affected header encoding. Header encoding is shared state across the connection, not just request state, so the entire connection is aborted.

**Comment by karelz** [comment] 2021-01-28 09:16
How often does it happen? Is there a chance to get more details about the root cause as laid out by @Tratcher above?

**Comment by karelz** [comment] 2021-02-16 19:41
Triage: We need more info. Closing as there is not data. Feel free to reopen once there is more info available.

**Closed by karelz** 2021-02-16 19:41 UTC
Labels: Triage: Info Needed, Type: Bug

**Comment by davidni** [comment] 2021-02-25 08:17
@sreejit-a did you end up building a PoC repro for this?
