### ISSUE TITLE
Support for dapr sidecar on Azure Container Apps

### ISSUE THREAD

**Issue by thara0402** [microsoft/reverse-proxy#1411] opened 2021-11-26 12:15 UTC
I deployed Reverse Proxy with YARP on Azure Container Apps.
Microservices Application leverage the YARP as an API gateway.
I want to YARP forwards the request to back-end service via dapr sidecar.

| YARP -> Dapr sidecar | -> | Dapr sidecar -> back-end service |

Do you have any plans to support it?

**Comment by Tratcher** [comment] 2021-11-29 16:46
#967 is another dapr issue, but I don't know enough about dapr to say if they're related.

**Comment by mayoatte** [comment] 2021-12-09 00:45
+1 for interest in this integration. This would be amazing.

**Comment by samsp-msft** [comment] 2022-01-04 18:38
Duplicate of #967

**Closed by samsp-msft** 2022-01-04 18:38 UTC
Labels: Type: Idea
