### ISSUE TITLE
Wildcard/subdomain not working

### ISSUE THREAD

**Issue by masaanli** [microsoft/reverse-proxy#1230] opened 2021-09-03 11:36 UTC
### Describe the bug
Rule not being fired.

What I want is that all subdomain traffic is being proxied from *.domainname1.com/api/* to domainname2.com/api/*.

But the code below I've written is not being fired at all.

### To Reproduce
```
 "ReverseProxy": {
    "Routes": {
      "test-route": {
        "ClusterId": "production",
        "Match": {
          "Hosts": [ "{*any}.domainname1.com" ],
          "Path": "/api/{*any}"
        }
      }
    },
    "Clusters": {
      "production": {
        "Destinations": {
          "test-online": {
            "Address": "https://domainname2.com/"
          }
        }
      }
    }
  }
```

### Further technical details

- Package version: 1.0.0-preview.11.21223.5
- The platform tested on MacOS/Linux/Windows

**Comment by Kahbazi** [comment] 2021-09-03 14:05
I think the problem is with `"Hosts": [ "{*any}.domainname1.com" ],`. In ASP.NET Core the syntax for host matching and route matching are slightly different.
Try `"Hosts": [ "*.domainname1.com" ],`.

**Comment by Tratcher** [comment] 2021-09-03 15:41
Yeah, the path matching syntax enables you to capture named parameters into the route values dictionary. The host matching syntax is a more standard wildcard subdomain syntax without captures.

**Comment by adityamandaleeka** [comment] 2021-09-14 18:11
Triage: closing as this appears to be answered.

**Closed by adityamandaleeka** 2021-09-14 18:11 UTC
Labels: Type: Bug
