### ISSUE TITLE
Partial Failure policy that routes affinitized requests to existing backends

### ISSUE THREAD

**Issue by wasabii** [microsoft/reverse-proxy#2335] opened 2023-11-21 04:47 UTC
It is a pretty common requirement (at least in my parts) to have stateful services using session affinity, where a partial failure mode of a node does not effect how affinitized requests are routed, until the service is fully failed.

For instance, imagine Blazor Server. You want affinitized connections. You want zero down time deployments. To do this requires that you stop routing new sessions to old node versions, but continue routing requests from existing sessions to nodes which are "shutting down". Until such time as the node detects it has no more active connections (either due to the users disconnecting, or timing out).

In IIS/ARR this was pretty easy: https://learn.microsoft.com/en-us/iis/extensions/configuring-application-request-routing-arr/http-load-balancing-using-application-request-routing#step-4---disallow-new-connections

>Disallowing new connections on a server is a graceful way of taking the server out of the server farm environment. It is more meaningful when the client affinity feature is in use, because Application Request Routing will honor the existing sessions when disallowing new connections. That is, when a client is affinitized to the server that is disallowing new connections, the client will continue to be routed to the same server and, therefore, there is no impact on the client. However, no new clients will be routed to the server that is disallowing new connections.

It looks to me though that this requires maintaining more than Health/Unhealthy for a node though. But also a Disallow status of some kind.

**Comment by Tratcher** [comment] 2023-11-21 16:32
This is similar to https://github.com/microsoft/reverse-proxy/issues/2071 (Degraded health)

**Comment by karelz** [comment] 2023-11-28 18:37
Affinity comment added to the issue #2071. Thanks!

**Comment by karelz** [comment] 2023-11-28 18:37
Duplicate of #2071

**Closed by karelz** 2023-11-28 18:37 UTC
Labels: Type: Idea
