### ISSUE TITLE
An error occurred while sending the request.

### ISSUE THREAD

**Issue by grounzero** [microsoft/reverse-proxy#711] opened 2021-02-05 01:06 UTC
If I refresh a page particularly if it is still loading I get a 502 error.  Is there any way I can capture exceptions and prevent the 502 from being seen in the browser?  The errors can be any of these:

```
System.Net.Http.HttpRequestException: An error occurred while sending the request.
 ---> System.IO.IOException: The request was aborted.
 ---> System.IO.IOException: The response ended prematurely while waiting for the next frame from the server.
   at System.Net.Http.Http2Connection.<ReadFrameAsync>g__ThrowMissingFrame|48_1()

```

```
System.Threading.Tasks.TaskCanceledException: The operation was canceled.
 ---> System.IO.IOException: Unable to read data from the transport connection: The I/O operation has been aborted because of either a thread exit or an application request..
 ---> System.Net.Sockets.SocketException (995): The I/O operation has been aborted because of either a thread exit or an application request.
```

```
Request: An error was encountered before receiving a response.
System.Net.Http.HttpRequestException: An error occurred while sending the request.
 ---> System.InvalidOperationException: Stream was already consumed.
   at Microsoft.ReverseProxy.Service.Proxy.StreamCopyHttpContent.SerializeToStreamAsync(Stream stream, TransportContext context)
```

_Originally posted by @grounzero in https://github.com/microsoft/reverse-proxy/discussions/710_

**Comment by grounzero** [comment] 2021-02-05 01:11
One way I have managed to supress it is by changing the EndPointDefaults in the Kestrel config on the destination to Http1

`
    "EndpointDefaults": {
      "Protocols": "Http1"
    },
`

**Comment by samsp-msft** [comment] 2021-02-05 05:47
Issue created from discussion #710

**Comment by Tratcher** [comment] 2021-02-06 07:35
I'm not able to reproduce this. The client reports an aborted request, it does not receive the 502 response. A 502 is what we'd return if the proxy request failed before the response started, but a client browser refresh aborts the client request so the 502 response is never received.

Let's get some baseline data.
What version of YARP are you using?
What version of .NET Core is this?
What kind of request is in progress, and what is it doing that's taking long enough for you to refresh the browser before it's done loading?
Can you simplify your config to only the relevant settings?
Please share the proxy logs, turned up to Debug for everything.

**Comment by grounzero** [comment] 2021-02-08 23:58
Using YARP 1.0.0-preview.8.21065.1

Framework version net5.0

I found out it's not actually caused by a browser refresh (though doing this does cause a 502 aproximately half of the time though I did not press refresh at all this time round). 

Behind YARP is a web application built using React with Apollo GraphQL client talking through YARP to consume an authenticated GraphQL Api.

Both the application and api are hosted in Kestrel.  Apollo client is set to poll graphQL for changes every 2 seconds and this works fine when I remove YARP and go directly to the destination endpoint and also works  via YARP if I configure Kestrel to explicitly use Http1.

I simplified the YARP config by removing header stuff from the Route transforms.

This is the Kestrel config I have on the GraphQL Api.

```
  "Kestrel": {
    "Limits": {
      "MaxRequestBodySize": null, // 10240 = 10KB. Default is 30MB. Use [RequestSizeLimit(100000000)] attribute to use more.
      "MaxRequestHeaderCount": 20 // Default is 100
    },
    "EndpointDefaults": {
      "Protocols": "Http1AndHttp2" <---- Changing this to "Http1" seems to make the issue go away.
    },
    "EndPoints": {
      "Https": {
        "Url": "https://*:9999",
        "Certificate": {
          "Subject": "vmx0007223",
          "Store": "My",
          "Location": "LocalMachine",
          "AllowInvalid": true
        }
      },
      "Http": {
        "Url": "http://*:9090"
      }
    }
  }
```
Here's the full debug log from YARP up until the exception is caught.

```
2021-02-08 08.43:23,872 - INFO:  Starting MyApplication.Proxy
2021-02-08 08.43:24,056 - INFO: Microsoft.AspNetCore.DataProtection.KeyManagement.XmlKeyManager User profile is available. Using '"C:\Users\groundsm\AppData\Local\ASP.NET\DataProtection-Keys"' as key repository and Windows DPAPI to encrypt keys at rest.
2021-02-08 08.43:24,156 - INFO: Microsoft.ReverseProxy.Configuration.ConfigurationConfigProvider Loading proxy data from config.
2021-02-08 08.43:24,331 - INFO: Microsoft.Hosting.Lifetime Now listening on: "http://[::]:8080"
2021-02-08 08.43:24,333 - INFO: Microsoft.Hosting.Lifetime Now listening on: "https://[::]:8443"
2021-02-08 08.43:24,399 - INFO: Microsoft.ReverseProxy.Service.HealthChecks.ActiveHealthCheckMonitor Probing destination `"sync/destination01"` on cluster `"sync"` completed with the response code `200`.
2021-02-08 08.43:24,399 - INFO: Microsoft.ReverseProxy.Service.HealthChecks.ActiveHealthCheckMonitor Probing destination `"ui/destination01"` on cluster `"ui"` completed with the response code `200`.
2021-02-08 08.43:24,399 - INFO: Microsoft.ReverseProxy.Service.HealthChecks.ActiveHealthCheckMonitor Probing destination `"api/destination01"` on cluster `"api"` completed with the response code `200`.
2021-02-08 08.43:24,414 - INFO: Microsoft.ReverseProxy.Service.HealthChecks.DestinationHealthUpdater Active health state of destination `"api/destination01"` on cluster `"api"` is set to 'Healthy'.
2021-02-08 08.43:24,414 - INFO: Microsoft.ReverseProxy.Service.HealthChecks.DestinationHealthUpdater Active health state of destination `"sync/destination01"` on cluster `"sync"` is set to 'Healthy'.
2021-02-08 08.43:24,414 - INFO: Microsoft.ReverseProxy.Service.HealthChecks.DestinationHealthUpdater Active health state of destination `"ui/destination01"` on cluster `"ui"` is set to 'Healthy'.
2021-02-08 08.43:29,959 - INFO: Microsoft.AspNetCore.Hosting.Diagnostics Request starting HTTP/2 POST https://vmx0007223:8443/api/graphql application/json 406
2021-02-08 08.43:29,959 - INFO: Microsoft.AspNetCore.Hosting.Diagnostics Request starting HTTP/2 POST https://vmx0007223:8443/api/graphql application/json 569
2021-02-08 08.43:29,995 - INFO: Microsoft.AspNetCore.Cors.Infrastructure.CorsService CORS policy execution successful.
2021-02-08 08.43:29,995 - INFO: Microsoft.AspNetCore.Cors.Infrastructure.CorsService CORS policy execution successful.
2021-02-08 08.43:30,686 - INFO: Microsoft.AspNetCore.Authentication.JwtBearer.JwtBearerHandler Successfully validated the token.
2021-02-08 08.43:30,686 - INFO: Microsoft.AspNetCore.Authentication.JwtBearer.JwtBearerHandler Successfully validated the token.
2021-02-08 08.43:30,701 - INFO: Microsoft.AspNetCore.Authorization.DefaultAuthorizationService Authorization was successful.
2021-02-08 08.43:30,701 - INFO: Microsoft.AspNetCore.Authorization.DefaultAuthorizationService Authorization was successful.
2021-02-08 08.43:30,710 - INFO: Microsoft.AspNetCore.Routing.EndpointMiddleware Executing endpoint '"MyApplication.Api"'
2021-02-08 08.43:30,710 - INFO: Microsoft.AspNetCore.Routing.EndpointMiddleware Executing endpoint '"MyApplication.Api"'
2021-02-08 08.43:30,739 - INFO: Microsoft.ReverseProxy.Service.Proxy.HttpProxy Proxying to "https://vmx0007223:9999/graphql"
2021-02-08 08.43:30,739 - INFO: Microsoft.ReverseProxy.Service.Proxy.HttpProxy Proxying to "https://vmx0007223:9999/graphql"
2021-02-08 08.43:30,757 - INFO: Microsoft.ReverseProxy.Service.Proxy.HttpProxy Request: "An error was encountered before receiving a response."
System.Net.Http.HttpRequestException: An error occurred while sending the request.
 ---> System.InvalidOperationException: Stream was already consumed.
   at Microsoft.ReverseProxy.Service.Proxy.StreamCopyHttpContent.SerializeToStreamAsync(Stream stream, TransportContext context)
   at System.Net.Http.Http2Connection.Http2Stream.SendRequestBodyAsync(CancellationToken cancellationToken)
   at System.Net.Http.Http2Connection.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at System.Net.Http.Http2Connection.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.SendWithRetryAsync(HttpRequestMessage request, Boolean async, Boolean doRequestAuth, CancellationToken cancellationToken)
   at Microsoft.ReverseProxy.Service.Proxy.HttpProxy.ProxyAsync(HttpContext context, String destinationPrefix, HttpMessageInvoker httpClient, RequestProxyOptions requestOptions, HttpTransformer transformer)
2021-02-08 08.43:30,757 - INFO: Microsoft.ReverseProxy.Service.Proxy.HttpProxy Request: "An error was encountered before receiving a response."
System.Net.Http.HttpRequestException: An error occurred while sending the request.
 ---> System.IO.IOException: The request was aborted.
 ---> System.IO.IOException: The response ended prematurely while waiting for the next frame from the server.
   at System.Net.Http.Http2Connection.<ReadFrameAsync>g__ThrowMissingFrame|48_1()
   at System.Net.Http.Http2Connection.ReadFrameAsync(Boolean initialFrame)
   at System.Net.Http.Http2Connection.ProcessIncomingFramesAsync()
   --- End of inner exception stack trace ---
   at System.Net.Http.Http2Connection.ThrowRequestAborted(Exception innerException)
   at System.Net.Http.Http2Connection.Http2Stream.CheckResponseBodyState()
   at System.Net.Http.Http2Connection.Http2Stream.TryEnsureHeaders()
   at System.Net.Http.Http2Connection.Http2Stream.ReadResponseHeadersAsync(CancellationToken cancellationToken)
   at System.Net.Http.Http2Connection.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at System.Net.Http.Http2Connection.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.SendWithRetryAsync(HttpRequestMessage request, Boolean async, Boolean doRequestAuth, CancellationToken cancellationToken)
   at Microsoft.ReverseProxy.Service.Proxy.HttpProxy.ProxyAsync(HttpContext context, String destinationPrefix, HttpMessageInvoker httpClient, RequestProxyOptions requestOptions, HttpTransformer transformer)
2021-02-08 08.43:30,785 - INFO: Microsoft.AspNetCore.Routing.EndpointMiddleware Executed endpoint '"MyApplication.Api"'
2021-02-08 08.43:30,800 - INFO: Microsoft.AspNetCore.Routing.EndpointMiddleware Executed endpoint '"MyApplication.Api"'
2021-02-08 08.43:30,812 - INFO: Microsoft.AspNetCore.Hosting.Diagnostics Request finished HTTP/2 POST https://vmx0007223:8443/api/graphql application/json 406 - 502 0 - 855.5222ms
2021-02-08 08.43:30,812 - INFO: Microsoft.AspNetCore.Hosting.Diagnostics Request finished HTTP/2 POST https://vmx0007223:8443/api/graphql application/json 569 - 502 0 - 855.5235ms
2021-02-08 08.43:30,907 - INFO: Microsoft.AspNetCore.Hosting.Diagnostics Request starting HTTP/2 POST https://vmx0007223:8443/api/graphql application/json 501
2021-02-08 08.43:30,907 - INFO: Microsoft.AspNetCore.Hosting.Diagnostics Request starting HTTP/2 POST https://vmx0007223:8443/api/graphql application/json 754
2021-02-08 08.43:30,910 - INFO: Microsoft.AspNetCore.Cors.Infrastructure.CorsService CORS policy execution successful.
2021-02-08 08.43:30,910 - INFO: Microsoft.AspNetCore.Cors.Infrastructure.CorsService CORS policy execution successful.
2021-02-08 08.43:30,913 - INFO: Microsoft.AspNetCore.Authentication.JwtBearer.JwtBearerHandler Successfully validated the token.
2021-02-08 08.43:30,913 - INFO: Microsoft.AspNetCore.Authentication.JwtBearer.JwtBearerHandler Successfully validated the token.
2021-02-08 08.43:30,915 - INFO: Microsoft.AspNetCore.Authorization.DefaultAuthorizationService Authorization was successful.
2021-02-08 08.43:30,916 - INFO: Microsoft.AspNetCore.Authorization.DefaultAuthorizationService Authorization was successful.
2021-02-08 08.43:30,918 - INFO: Microsoft.AspNetCore.Routing.EndpointMiddleware Executing endpoint '"MyApplication.Api"'
2021-02-08 08.43:30,919 - INFO: Microsoft.AspNetCore.Routing.EndpointMiddleware Executing endpoint '"MyApplication.Api"'
2021-02-08 08.43:30,921 - INFO: Microsoft.ReverseProxy.Service.Proxy.HttpProxy Proxying to "https://vmx0007223:9999/graphql"
2021-02-08 08.43:30,922 - INFO: Microsoft.ReverseProxy.Service.Proxy.HttpProxy Proxying to "https://vmx0007223:9999/graphql"
2021-02-08 08.43:30,931 - INFO: Microsoft.ReverseProxy.Service.Proxy.HttpProxy Request: "An error was encountered before receiving a response."
System.Net.Http.HttpRequestException: An error occurred while sending the request.
 ---> System.IO.IOException: The request was aborted.
 ---> System.IO.IOException: The response ended prematurely while waiting for the next frame from the server.
   at System.Net.Http.Http2Connection.<ReadFrameAsync>g__ThrowMissingFrame|48_1()
   at System.Net.Http.Http2Connection.ReadFrameAsync(Boolean initialFrame)
   at System.Net.Http.Http2Connection.ProcessIncomingFramesAsync()
   --- End of inner exception stack trace ---
   at System.Net.Http.Http2Connection.ThrowRequestAborted(Exception innerException)
   at System.Net.Http.Http2Connection.Http2Stream.CheckResponseBodyState()
   at System.Net.Http.Http2Connection.Http2Stream.TryEnsureHeaders()
   at System.Net.Http.Http2Connection.Http2Stream.ReadResponseHeadersAsync(CancellationToken cancellationToken)
   at System.Net.Http.Http2Connection.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at System.Net.Http.Http2Connection.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.SendWithRetryAsync(HttpRequestMessage request, Boolean async, Boolean doRequestAuth, CancellationToken cancellationToken)
   at Microsoft.ReverseProxy.Service.Proxy.HttpProxy.ProxyAsync(HttpContext context, String destinationPrefix, HttpMessageInvoker httpClient, RequestProxyOptions requestOptions, HttpTransformer transformer)
2021-02-08 08.43:30,937 - INFO: Microsoft.ReverseProxy.Service.Proxy.HttpProxy Request: "An error was encountered before receiving a response."
System.Net.Http.HttpRequestException: An error occurred while sending the request.
 ---> System.InvalidOperationException: Stream was already consumed.
   at Microsoft.ReverseProxy.Service.Proxy.StreamCopyHttpContent.SerializeToStreamAsync(Stream stream, TransportContext context)
   at System.Net.Http.Http2Connection.Http2Stream.SendRequestBodyAsync(CancellationToken cancellationToken)
   at System.Net.Http.Http2Connection.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at System.Net.Http.Http2Connection.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.SendWithRetryAsync(HttpRequestMessage request, Boolean async, Boolean doRequestAuth, CancellationToken cancellationToken)
   at Microsoft.ReverseProxy.Service.Proxy.HttpProxy.ProxyAsync(HttpContext context, String destinationPrefix, HttpMessageInvoker httpClient, RequestProxyOptions requestOptions, HttpTransformer transformer)
2021-02-08 08.43:30,951 - INFO: Microsoft.AspNetCore.Routing.EndpointMiddleware Executed endpoint '"MyApplication.Api"'
2021-02-08 08.43:30,963 - INFO: Microsoft.AspNetCore.Routing.EndpointMiddleware Executed endpoint '"MyApplication.Api"'
2021-02-08 08.43:30,964 - INFO: Microsoft.AspNetCore.Hosting.Diagnostics Request finished HTTP/2 POST https://vmx0007223:8443/api/graphql application/json 501 - 502 0 - 56.7773ms
2021-02-08 08.43:30,965 - INFO: Microsoft.AspNetCore.Hosting.Diagnostics Request finished HTTP/2 POST https://vmx0007223:8443/api/graphql application/json 754 - 502 0 - 58.2100ms
2021-02-08 08.43:32,905 - INFO: Microsoft.AspNetCore.Hosting.Diagnostics Request starting HTTP/2 POST https://vmx0007223:8443/api/graphql application/json 754
2021-02-08 08.43:32,906 - INFO: Microsoft.AspNetCore.Cors.Infrastructure.CorsService CORS policy execution successful.
2021-02-08 08.43:32,908 - INFO: Microsoft.AspNetCore.Authentication.JwtBearer.JwtBearerHandler Successfully validated the token.
2021-02-08 08.43:32,909 - INFO: Microsoft.AspNetCore.Authorization.DefaultAuthorizationService Authorization was successful.
2021-02-08 08.43:32,911 - INFO: Microsoft.AspNetCore.Routing.EndpointMiddleware Executing endpoint '"MyApplication.Api"'
2021-02-08 08.43:32,912 - INFO: Microsoft.AspNetCore.Hosting.Diagnostics Request starting HTTP/2 POST https://vmx0007223:8443/api/graphql application/json 501
2021-02-08 08.43:32,913 - INFO: Microsoft.ReverseProxy.Service.Proxy.HttpProxy Proxying to "https://vmx0007223:9999/graphql"
2021-02-08 08.43:32,914 - INFO: Microsoft.AspNetCore.Cors.Infrastructure.CorsService CORS policy execution successful.
2021-02-08 08.43:32,918 - INFO: Microsoft.AspNetCore.Authentication.JwtBearer.JwtBearerHandler Successfully validated the token.
```

**Comment by Tratcher** [comment] 2021-02-09 01:01
```
 ---> System.InvalidOperationException: Stream was already consumed.
   at Microsoft.ReverseProxy.Service.Proxy.StreamCopyHttpContent.SerializeToStreamAsync
```
https://github.com/microsoft/reverse-proxy/blob/9dec286992967e0dc159f7db04254262f2364e74/src/ReverseProxy/Service/Proxy/StreamCopyHttpContent.cs#L118-L125

There's nothing in the YARP code that should cause this to be called twice. @ManickaP Are there any conditions in SocketsHttpHandler where it will call HttpContent.SerializeToStreamAsync twice? We should have redirects any other cases disabled.

**Comment by ManickaP** [comment] 2021-02-10 12:12
It could be in auth, for instance here:
https://github.com/dotnet/runtime/blob/master/src/libraries/System.Net.Http/src/System/Net/Http/SocketsHttpHandler/AuthenticationHelper.Digest.cs#L154

Though I'm not familiar with auth (neither in `HttpClient` nor in general). If you want me to dig deeper into this, I'll need detailed `HttpClient` logs or a local repro. However, I still don't see how switching to HTTP/1.1 could "fix" this...

**Comment by grounzero** [comment] 2021-02-12 10:06
The websocket auth was not authenticating via YARP so I set `"AuthorizationPolicy": "Anonymous"`, to cut out some moving parts.  The Api has an authentication scheme specifically for sockets and a handler event to tell it where to find the token.

If I wanted websocket auth to work via YARP would I have to duplicate the socket auth scheme in the proxy project as well?

**Comment by Tratcher** [comment] 2021-02-12 17:19
If the websockets need a different kind of auth from your other routes then they will need their own route setup in the proxy. It's up to you if you want the proxy or destination to handle the authentication for that route.

**Comment by karelz** [comment] 2021-02-16 19:47
Triage: We still need more info on the scenario -- ideally a repro, to investigate.

**Comment by simonthum** [comment] 2021-03-17 13:59
I've stubled on this issue because I got the same symptoms in a gRPC Service. The cause, in my case, was a "too high" http/2 ping frequency (System.Net.Http.SocketsHttpHandler.KeepAlivePingDelay was below 60 seconds). I did not fully track it down, but gRPC seems to send a "enhance your calm" message which I suppose causes the above errors.

**Comment by grounzero** [comment] 2021-03-20 08:38
I've tried stripping it down to get a simple repro project without success. I haven't been able to spend as much time on this as I would like to.  I think in my case it may be the websocket Auth and the "upgrade" request.   Downgrading the graphql service to http1 seems to be a sticky plaster fix for the moment.

**Comment by karelz** [comment] 2021-03-22 19:10
Triage: Looks like it is not actionable at this moment, without repro. Let's close it and wait for a repro in future.

@simonthum your description seems to be unrelated to this one. Please open a new issue with details if you still have troubles. Thanks!

**Closed by karelz** 2021-03-22 19:10 UTC
Labels: Triage: Info Needed

**Comment by simonthum** [comment] 2021-04-10 18:07
@karelz I do think they might be related. I suspect that my ping frequency was leading the server to send me a GOAWAY: https://tools.ietf.org/html/rfc7540#section-6.8

That gets me this stack:  ---> System.IO.IOException: The request was aborted.
 ---> System.IO.IOException: The response ended prematurely while waiting for the next frame from the server.
   at System.Net.Http.Http2Connection.<ReadFrameAsync>g__ThrowMissingFrame|48_1()
   at System.Net.Http.Http2Connection.ReadFrameAsync(Boolean initialFrame)
   at System.Net.Http.Http2Connection.ProcessIncomingFramesAsync()
   --- End of inner exception stack trace ---
   at System.Net.Http.Http2Connection.ThrowRequestAborted(Exception innerException)
   at System.Net.Http.Http2Connection.Http2Stream.CheckResponseBodyState()
   at System.Net.Http.Http2Connection.Http2Stream.TryReadFromBuffer(Span`1 buffer, Boolean partOfSyncRead)
   at System.Net.Http.Http2Connection.Http2Stream.ReadDataAsync(Memory`1 buffer, HttpResponseMessage responseMessage, CancellationToken cancellationToken)

which led me here. It seems to me that the behaviour is a client implementation of GOAWAY that is probably fine from a protocol point of view ;)

If you want to give it a shot, be sure to check GOAWAY.

**Comment by grounzero** [comment] 2021-06-04 18:18
I finally managed to get chance to look at this in more detail and found the cause to be a missing replyUri / tokenRefreshUri in the authentication server.  Error messages around auth can be misleading.

Thank you @ManickaP @Tratcher for pointing me in the right direction.  

> It could be in auth, for instance here:
> https://github.com/dotnet/runtime/blob/master/src/libraries/System.Net.Http/src/System/Net/Http/SocketsHttpHandler/AuthenticationHelper.Digest.cs#L154
> 
> Though I'm not familiar with auth (neither in `HttpClient` nor in general). If you want me to dig deeper into this, I'll need detailed `HttpClient` logs or a local repro. However, I still don't see how switching to HTTP/1.1 could "fix" this...
