### ISSUE TITLE
Configure HTTP/2 prior knowledge per destination

### ISSUE THREAD

**Issue by ericwj** [microsoft/reverse-proxy#363] opened 2020-08-08 05:49 UTC
### What should we add or change to make your life better?

Consider adding a configuration option per destination or per cluster to enable HTTP/2 prior knowledge.

### Why is this important to you?

I think HTTP/2 is a fine improvement over HTTP/1.1 almost regardless of the application and it is beneficial to still do HTTPS termination at the proxy - besides the performance benefits, already if it were only to get rid of certificate management.

### How did you get the idea?

I managed to get rid of the delays I reported in #355 by configuring the downstream Kestrels with

```json
"Kestrel": { "EndpointDefaults": { "Protocols": "Http2" } },
```

but to get that working I needed this in the proxy:

```C#
AppContext.SetSwitch("System.Net.Http.SocketsHttpHandler.Http2UnencryptedSupport", true);
```

However now my proxy doesn't proxy to another HTTP/1 backend anymore. I basically have to choose which half of the downstream servers are going to respond with an empty body.

### How can this be done?

I don't know. Reverse proxy doesn't let me choose the HTTP version that is set on the request certainly, but I don't know whether that even matters - whether there is a way in .NET to let the proxy be selective about which servers to send HTTP/2 requests to. Although I can hardly believe that `AppContext` swhitch just globally makes every outbound request HTTP/2?

**Comment by Tratcher** [comment] 2020-08-08 13:06
This requires #137 and #282. Then you'd be able to control this on a per cluster basis. Do you think that would be granular enough?

**Comment by ericwj** [comment] 2020-08-08 14:23
For me yes.

**Comment by karelz** [comment] 2020-08-11 18:26
Duplicate of #137

**Closed by karelz** 2020-08-11 18:26 UTC
Labels: Type: Idea
