### ISSUE TITLE
ResponseHeader Prepend?

### ISSUE THREAD

**Issue by amweiss** [microsoft/reverse-proxy#372] opened 2020-08-19 23:17 UTC
### What should we add or change to make your life better?

Currently, you can define a ResponseHeader Transform to set or append, I have a use case where prepend would be helpful.

### Why is this important to you?

A service we proxy is returning a `301` with a relative URL as the `Location` in the response, so when YARP sends this back, the client will attempt to follow the redirect on the proxy server instead of the destination server. This leads to a `404` in our case, but could have been a different route entirely. If we can do a transform to prepend the matching `Route` and `Path`, we could send back the correct address that would be the equivalent `Location` through the proxy.

**Comment by Tratcher** [comment] 2020-08-19 23:33
Prepend would help with relative redirects, but it's still broken for absolute redirects. All links emended content would also still be broken.

What is the destination app? Have you considered fixing up the url generation on that side?
https://docs.microsoft.com/en-us/aspnet/core/host-and-deploy/proxy-load-balancer?view=aspnetcore-3.1#deal-with-path-base-and-proxies-that-change-the-request-path

**Comment by Tratcher** [comment] 2020-08-19 23:35
See also https://microsoft.github.io/reverse-proxy/articles/transforms.html#x-forwarded X-Forwarded-PathBase

**Comment by amweiss** [comment] 2020-08-19 23:39
We can make that request, but we can't fix it ourselves. Thanks for the helpful context though.

**Comment by karelz** [comment] 2020-09-08 18:28
Triage: Custom transforms should cover it (once we have them).

**Comment by karelz** [comment] 2020-09-08 18:28
Duplicate of #60

**Closed by karelz** 2020-09-08 18:28 UTC
Labels: Type: Idea
