### ISSUE TITLE
Active health checks are not enabled after configuration reload

### ISSUE THREAD

**Issue by PieterBoeren** [microsoft/reverse-proxy#1134] opened 2021-07-01 11:19 UTC
### Describe the bug
Active health checks are not enabled after configuration reload, only after a full restart. Strange thing is that the disabling seems to work, only the enabling doesn't

### To Reproduce

1. Create a config with a cluster with an active health check, but disabled (Enabled = false)
2. Start the proxy
3. While running the proxy, change and save the config, setting the health check to enabled=true
4. Watch the reload of the config happening, but the health checks calls don't appear in the logs

### Further technical details

- Yarp preview 12
- Windows

**Comment by MihaZupan** [comment] 2021-07-01 12:01
Thanks for reporting this

Presumably the issue is here:
https://github.com/microsoft/reverse-proxy/blob/05ea85f48d6079aaf7eadaf18c592367c0a1e7e6/src/ReverseProxy/Health/ActiveHealthCheckMonitor.cs#L81-L92

We try to update an existing entry even if it was never added, so we just no-op.

From looking at the ActiveHealthCheckMonitor code, there are a few race conditions / potential memory leaks as well.

**Comment by MihaZupan** [comment] 2021-07-02 12:46
Regarding the race conditions/memory leaks:
The main issue is in `ScheduleEntity` where it will register the timer (autostart) before adding it to the dictionary.

A few scenarios:

1.
- Thread A calls ScheduleEntity and autostart is false
- Thread B calls Start, switching autostart to true
- Thread B enumerates the dictionary and enables all timers
- Thread A adds the unscheduled entry to the dictionary, where it will live forever taking up memory and never firing

2.
- Thread A calls ScheduleEntity and autostart is true
- The timer we just created fires and the callback is invoked
- Thread B executes the timer callback
- Thread A adds the entry into the dictionary
- Since the timer callback never saw the entry in the dictionary, it will never remove it from it. Any timer that isn't "runOnce" will never be re-scheduled.

May be more but these 2 are simple to reason about

**Comment by alnikola** [comment] 2021-07-02 13:15
This issue happens because we omitted the call to Start on a config reload. Currently, Start is called only during the initial configuration load. We will fix it.
It's unrelated to the race conditions described above.

**Comment by alnikola** [comment] 2021-07-02 13:23
Race conditions will be addressed by #1136

**Closed** 2021-08-17 12:37 UTC
Labels: Type: Bug
