### ISSUE TITLE
Rewriting request URL for downstream service

### ISSUE THREAD

**Issue by jmezach** [microsoft/reverse-proxy#207] opened 2020-05-26 18:52 UTC
I've been looking into YARP to see if it can be used as an API gateway. We currently have one based on the [Ocelot](https://github.com/ThreeMammals/Ocelot) library but since it seems that might be deprecated in favor of YARP I figured I could take a look and see if I can achieve the same thing.

One of the things I'm able to do with Ocelot and which I haven't been able to achieve with YARP yet is the ability to rewrite the downstream request path. For example, let's say that I want to proxy the upstream URL https://somewhere.example.com/someapi/<the-rest> to the downstream URL https://localhost:5003/<the-rest>.

I would expect this to work, however currently I'm seeing request to https://localhost:5003/someapi/<the-rest> instead. Here's the config I'm using:

```json
"ReverseProxy": {
  "Routes": [
    {
      "RouteId": "someapi",
      "BackendId": "EchoService",
      "Match": {
        "Methods": [ "GET", "POST" ],
        "Host": "somewhere.example.com",
        "Path": "/someapi/{**catchall}"
      }
    }
  ],
  "Backends": {
    "EchoService": {
      "LoadBalancing": {
        "Mode": "Random"
      },
      "Destinations": {
        "backend_destination1": {
          "Address": "https://localhost:5003/"
        }
      }
    }
  }
},
```

Is this something that's supported, or planned to be supported?

**Comment by jmezach** [comment] 2020-05-26 20:14
After looking through the issues already here I guess that this could be achieved using what's being proposed in #21, although that looks like more than want I really need.

**Comment by Tratcher** [comment] 2020-05-26 20:26
> We currently have one based on the Ocelot library but since it seems that might be deprecated in favor of YARP

Deprecating Ocelot or deprecating your usage of it?

Yes, #21 should cover this scenario. I've started work on it so we should have something to demonstrate for the next preview.

**Comment by jmezach** [comment] 2020-05-27 10:03
Well, it looks like the plan is to deprecate Ocelot itself (see https://github.com/ThreeMammals/Ocelot/pull/1234#issuecomment-633068823), although that will probably be some time off. But since we aren't currently using that much functionality of Ocelot I figured I might as well give YARP a try.

Looking forward to trying out the new preview. If you need some early feedback I'd be more than happy to give it a try sooner if possible.

**Comment by samsp-msft** [comment] 2020-05-27 17:43
Duplicate of #21

**Closed by samsp-msft** 2020-05-27 17:43 UTC
Labels: Type: Discussion

**Comment by vip32** [comment] 2020-10-15 22:43
https://microsoft.github.io/reverse-proxy/articles/transforms.html
