### ISSUE TITLE
Use HttpClientHandler for Proxy

### ISSUE THREAD

**Issue by Kahbazi** [microsoft/reverse-proxy#149] opened 2020-05-08 22:16 UTC
### What should we add or change to make your life better?
Use `HttpClientHandler` for proxy instead of `SocketsHttpHandler`
https://github.com/microsoft/reverse-proxy/blob/bc9298322206f35e7d658183464cdf806280143f/src/ReverseProxy.Core/Service/Proxy/Infra/ProxyHttpClientFactory.cs#L33-L42

### Why is this important to you?
`HttpClientHandler` creates a [`DiagnosticsHandler`](https://github.com/dotnet/runtime/blob/4b03513e20e0caf9ee34817eb74356903f1bb33e/src/libraries/System.Net.Http/src/System/Net/Http/DiagnosticsHandler.cs) which adds `Request-Id` header and writes diagnostic events.

**Comment by karelz** [comment] 2020-05-08 22:42
Is that a good idea for the proxy to automatically add additional headers without explicit opt-in from the proxy dev?

Also note that `SocketsHttpHandler` provides bunch of useful customizations which `HttpClientHandler` does not and we are even adding more (Connection abstractions, connection pool API) which won't be exposed in `HttpClientHandler`.

I would rather view this as duplicate of https://github.com/dotnet/runtime/issues/31261 -- `SocketsHttpHandler` should have ability to opt-in into additional DiagnosticsHandler logging (or some similar solution to the end-to-end problem).

**Comment by karelz** [comment] 2020-05-14 18:54
Duplicate of https://github.com/dotnet/runtime/issues/31261

**Closed by karelz** 2020-05-14 18:54 UTC
Labels: Type: Idea
