### ISSUE TITLE
LoadBalancing allowing drain stop of service

### ISSUE THREAD

**Issue by grahamehorner** [microsoft/reverse-proxy#213] opened 2020-05-30 12:20 UTC
Create a secured LoadBalancer management endpoint to allow the drain stopping of a service as part of a automated deployment scenario of services.

**Comment by Tratcher** [comment] 2020-05-30 14:31
What level of draining are you looking for here?
- a single destination server instance
- a whole backend cluster
- the whole proxy server

**Comment by grahamehorner** [comment] 2020-05-30 21:10
I was thinking that a drain stop should be initially a single server destination within a load balanced cluster; this would allow the server to be updated with zero down item of a service. 
may be additional functionality can be built on top of this where servers in a load balanced cluster can have grouped and the group  drain stopped to allow updates

**Comment by karelz** [comment] 2020-05-30 22:11
How is draining different from removing the server temporarily from the cluster?

**Comment by Tratcher** [comment] 2020-05-30 23:51
I think those are the same in our implementation and that this already works, it's just about verifying that active requests aren't disrupted when the configuration changes.

**Comment by grahamehorner** [comment] 2020-05-31 00:21
@karelz @Tratcher you wouldn't want to remove the server from the cluster, but simply not allow it to be selected for new requests, until indicated by bring it back online.

**Comment by davidfowl** [comment] 2020-05-31 00:29
Seems like rolling deployments is the feature being asked but that's not usually the load balancer on its own rather than in coordination with another orchestration system (this is built into k8s for example). So it seems like there's an end to end here and we need to figure out the pieces.

What would it look like to build a system that uses YARP to do zero downtime deployments e.g https://openmymind.net/Framework-Agnostic-Zero-Downtime-Deployment-With-Nginx/

That will motivate what features we need to add/improve to accomplish this.

**Comment by Tratcher** [comment] 2020-05-31 05:44
That's already being discussed over at https://github.com/microsoft/reverse-proxy/issues/126#issuecomment-632800093

**Comment by davidfowl** [comment] 2020-05-31 06:09
The title seems wrong then because this has nothing to do with A/B testing

**Comment by Tratcher** [comment] 2020-05-31 16:00
Sure, we identified the a/b testing scenario first, but rolling upgrades use the same mechanics.

**Comment by davidfowl** [comment] 2020-05-31 16:13
Rename the issue so it can be easily identified?

**Comment by Tratcher** [comment] 2020-05-31 18:28
"Design A/B testing and rolling upgrade strategies"

**Comment by samsp-msft** [comment] 2020-06-02 23:10
duplicate of #126

**Closed** 2020-06-02 23:09 UTC
Labels: Type: Idea
