### ISSUE TITLE
Simplify Config Values

### ISSUE THREAD

**Issue by rposener** [microsoft/reverse-proxy#762] opened 2021-02-19 02:58 UTC
### What should we add or change to make your life better?
Make config values simpler.  I deployed as test to Linux Web App in Azure, and quickly discovered that appsettings (e.g. ReverseProxy__Clusters__clientapi__Destinations__clientapi1__Address) kind of thing did not work.  It got cut-off and doesn't read the entire setting name.  A simpler Config setup as default would be nice.  Easy enough to work-around by setting my own config and using a fluent setup.

### Why is this important to you?
Just seems like it's a simper experience as default.

**Comment by Tratcher** [comment] 2021-02-19 05:33
You're trying to provide the config via environment variables? I can see how that'd get unwieldy. That structure was designed more fore appsettings.json files.

**Comment by karelz** [comment] 2021-03-22 19:22
Triage: Our config is way too complicated for full environment variables support (the flattening is rather ugly as you pointed out).
To replace destinations at runtime (post deployment), you should be able to use `IProxyConfigFilter` to replace symbolic names with real addresses of destinations.
We have a sample for using `IProxyConfigFilter`: https://github.com/microsoft/reverse-proxy/blob/main/samples/ReverseProxy.Config.Sample/CustomConfigFilter.cs

We should add doc for this.

**Comment by samsp-msft** [comment] 2021-03-26 21:37
The scenario of being able to more easily access and change config for app service hosting is a good one, and the current story is not great.

I think the improvement would be to update the config filter sample to fetch a value from a custom key, and then apply that to records in the proxy configuration. The problem is that would require there to be logic to know which values to pull from where to be replaced.

I am wondering if the sample could/should show a regex pattern match of looking for {{key}} or similar in the appsettings.json for  destinations or hosts in routes, and then do a lookup for the value?

@tratcher - I initially thought that the cancellation token was for the Filter to be able to say that the value is invalid, but it seems like its to cancel the async operation. Is there something like the token on a custom config provider to say that the values are now stale?

**Comment by karelz** [comment] 2021-03-29 19:03
Triage: Environment variables can't change during process runtime.

**Comment by samsp-msft** [comment] 2021-04-15 21:46
Resolved by #883 which shows how to use a filter to replace values in config as its loaded.

**Closed by samsp-msft** 2021-04-15 21:46 UTC
Labels: Type: Documentation
