### ISSUE TITLE
Poor performance and errors when proxying to https

### ISSUE THREAD

**Issue by jmezach** [microsoft/reverse-proxy#355] opened 2020-07-31 14:37 UTC
### Describe the bug
I've been running some benchmarks on my local machine for my API gateway that is currently using Ocelot, but that I'm in the process of migrating to YARP. To perform the benchmarks I've been using [Crank](https://github.com/dotnet/crank) from the .NET team, which is awesome by the way.

What I've seen so far is that if the downstream service I'm proxying to is using HTTP, YARP is much faster than Ocelot. For example, here are the results for my current gateway using Ocelot:

```
First Request (ms):   850
Requests:             18,068
Bad responses:        0
Mean latency (us):    214,006
Max latency (us):     499,452
Requests/sec:         1,181
Requests/sec (max):   7,272
```

While these are the results for a similar scenario, but using YARP:

```
First Request (ms):   1,205
Requests:             48,984
Bad responses:        0
Mean latency (us):    78,480
Max latency (us):     2,128,675
Requests/sec:         3,258
Requests/sec (max):   13,420
```

Those are not too shabby, although the max latency for YARP is interesting. Do note that my Ocelot based gateway is running on .NET Core 3.1, while my YARP gateway is running on .NET 5 Preview 7.

However, when I ran the same benchmark with the gateway proxying to the downstream service using HTTPS, I'm seeing very different results:

**Ocelot:**
```
First Request (ms):   1,088
Requests:             12,819
Bad responses:        0
Mean latency (us):    301,467
Max latency (us):     3,571,386
Requests/sec:         839
Requests/sec (max):   7,944
```

**YARP:**
```
First Request (ms):   1,631
Requests:             527
Bad responses:        515
Mean latency (us):    9,021,413
Max latency (us):     10,132,335
Requests/sec:         18
Requests/sec (max):   6,587
```

Obviously the number of bad responses triggered me, so I've looked into the logs to see if I can figure out what's going wrong. I see a lot of these exceptions:

```
[04:31:02.965] System.OperationCanceledException: The operation was canceled.
[04:31:02.965]    at System.Threading.CancellationToken.ThrowOperationCanceledException()
[04:31:02.965]    at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.ThrowException(SocketError error, CancellationToken cancellationToken)
[04:31:02.965]    at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.GetResult(Int16 token)
[04:31:02.965]    at System.Net.Security.SslStream.<FillHandshakeBufferAsync>g__InternalFillHandshakeBufferAsync|180_0[TIOAdapter](TIOAdapter adap, ValueTask`1 task, Int32 minSize)
[04:31:02.965]    at System.Net.Security.SslStream.ReceiveBlobAsync[TIOAdapter](TIOAdapter adapter)
[04:31:02.965]    at System.Net.Security.SslStream.ForceAuthenticationAsync[TIOAdapter](TIOAdapter adapter, Boolean receiveFirst, Byte[] reAuthenticationData, Boolean isApm)
[04:31:02.965]    at System.Net.Http.ConnectHelper.EstablishSslConnectionAsyncCore(Stream stream, SslClientAuthenticationOptions sslOptions, CancellationToken cancellationToken)
[04:31:02.965]    at System.Net.Http.HttpConnectionPool.ConnectAsync(HttpRequestMessage request, Boolean allowHttp2, CancellationToken cancellationToken)
[04:31:02.965]    at System.Net.Http.HttpConnectionPool.CreateHttp11ConnectionAsync(HttpRequestMessage request, CancellationToken cancellationToken)
[04:31:02.965]    at System.Net.Http.HttpConnectionPool.GetHttpConnectionAsync(HttpRequestMessage request, CancellationToken cancellationToken)
[04:31:02.965]    at System.Net.Http.HttpConnectionPool.SendWithRetryAsync(HttpRequestMessage request, Boolean doRequestAuth, CancellationToken cancellationToken)
[04:31:02.965]    at Microsoft.ReverseProxy.Service.Proxy.HttpProxy.NormalProxyAsync(HttpContext context, HttpRequestMessage upstreamRequest, Transforms transforms, HttpMessageInvoker httpClient, ProxyTelemetryContext proxyTelemetryContext, CancellationToken shortCancellation, CancellationToken longCancellation)
[04:31:02.965]    at Microsoft.ReverseProxy.Telemetry.TextOperationLogger`1.ExecuteAsync(String operationName, Func`1 action)
[04:31:02.965]    at Microsoft.ReverseProxy.Middleware.ProxyInvokerMiddleware.Invoke(HttpContext context)
[04:31:02.965]    at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
[04:31:02.965]    at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
[04:31:02.965]    at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)
```

That looks like it is somehow not able to complete the SSL handshake with the downstream service, but my Ocelot based gateway doesn't have that same problem and both are going to the exact same service. That service is running on ASP.NET Core 3.1 by the way.

### To Reproduce

So far I've followed the basic guide for setting up a reverse proxy with YARP. I'm using the following configuration:

```json
"ReverseProxy": {
  "Routes": [
    {
        "RouteId": "realization",
        "ClusterId": "EchoService",
        "Match": {
          "Methods": [ "GET", "POST" ],
          "Hosts": [ "localhost" ],
          "Path": "/realization/{*remainder}"
        },
        "Transforms": [
            { "PathSet": "/api/values" }
        ]
     }
  ],
  "Clusters": {
    {
      "EchoService": {
        "LoadBalancing": {
          "Mode": "Random"
        },
        "Destinations": {
          "backend_destination1": {
            "Address": "https://localhost:5003/"
          }
        }
   }
}
  }
}
```

Changing `backend_destination1`'s `Address` to `http://localhost:5002/` fixes the issue.

### Further technical details

- Include the version of the packages you are using: **1.0.0-preview.3**
- The platform (Linux/macOS/Windows): macOS

**Comment by Tratcher** [comment] 2020-07-31 15:42
- How many concurrent requests are you issuing with crank?
- Does the destination server have HTTP/2 enabled?

YARP defaults to proxying via HTTP/2 when https is used, if the destination has it enabled. There's a known issue with HTTP/2 being limited to one connection and commonly 100 concurrent streams on that connection. If you're issuing more than 100 concurrent requests they may get backlogged and time out. This should be fixed by https://github.com/dotnet/runtime/pull/39439 in 5.0.0 RC1.

Mitigations:
- Raise the HTTP/2 concurrent stream limit on the destination server.
- Lower the concurrency count on crank.

**Comment by Tratcher** [comment] 2020-07-31 15:43
Nevermind, I hadn't actually read the middle of that stack trace...

**Comment by jmezach** [comment] 2020-08-03 06:48
I was using the default out of the box Bombardier job, which seems to use 256 concurrent connections.I'll try to see if I can lower that to see what happens then. Is there some way with YARP to control which protocol is used for the downstream request?

**Comment by jmezach** [comment] 2020-08-03 07:17
I ran another benchmark with 100 concurrent connections, and that seems to fix my issue. Here are the results for that:

```
First Request (ms):   1,643
Requests:             18,694
Bad responses:        0
Mean latency (us):    80,288
Max latency (us):     2,516,643
Requests/sec:         1,262
Requests/sec (max):   5,649
```

**Comment by davidfowl** [comment] 2020-08-03 07:37
cc @sebastienros

**Comment by samsp-msft** [comment] 2020-08-04 18:27
@scalablecory can you validate that the callstack is actually using http2. Chris is worried about:

[04:31:02.965]    at System.Net.Http.HttpConnectionPool.ConnectAsync(HttpRequestMessage request, Boolean allowHttp2, CancellationToken cancellationToken)
**[04:31:02.965]    at System.Net.Http.HttpConnectionPool.CreateHttp11ConnectionAsync(HttpRequestMessage request, CancellationToken cancellationToken)**
[04:31:02.965]    at System.Net.Http.HttpConnectionPool.GetHttpConnectionAsync(HttpRequestMessage request, CancellationToken cancellationToken)

**Comment by scalablecory** [comment] 2020-08-04 21:51
> @scalablecory can you validate that the callstack is actually using http2.

The call stack shows HTTP/1. The exception indicates the remote server is timing out.

**Comment by ericwj** [comment] 2020-08-06 20:49
I'm seeing comparable results when I hit a `https` endpoint on the proxy and it is proxying to `http`. 

I don't need benchmarks to see that there is something weird going on. This is obvious from running a slightly non-trivial ASP.NET website and trying both the `http` and `https` endpoints on the proxy.

It appears some kind of latency of about 2000ms is hidden somewhere. The home page loads in a varying number of 2 second delays.

I've modified the configuration of `ReverseProxy.Sample` for the occasion, instead of rambling here about the reverse proxy that I had written myself, renaming the endpoint for `RouteId: route2` from `localhost` to `localhost2` and replacing the match on `localhost` with:
```json
"Clusters": { "cluster3": { "Destinations": { "c3d1": { "Address": "http://localhost:64010" } } } }
"Routes": [ { "RouteId": "route3", "ClusterId": "cluster3", "Match": { "Hosts": [ "localhost" ] } } ]
```
also configuring the proxy to use ports 6080/6443 instead of the overused 5000/5001. Hitting `http://localhost:6080` or `http://localhost:64010` are both very reasonably fast, but `https://localhost:6443` is wicked slow. Excerpts from `ReverseProxy.Sample.exe` logs (in-order, incomplete):
```
Request finished HTTP/2 GET https://localhost:6443/js/site.js?v=Rdzd6PuqFqgP4ws4ghSlsmdMTpoZGnX1oinqI1rIgvg - - - 200 2501 application/javascript 9.9278ms
Request finished HTTP/2 GET https://localhost:6443/vendor/jquery-easing/jquery.easing.js - - - 200 4213 application/javascript 10.2005ms
Request finished HTTP/2 GET https://localhost:6443/vendor/scrollreveal/scrollreveal.js - - - 200 44264 application/javascript 10.4186ms
Request finished HTTP/2 GET https://localhost:6443/vendor/magnific-popup/jquery.magnific-popup.js - - - 200 43589 application/javascript 25.7918ms
Request finished HTTP/2 GET https://localhost:6443/vendor/bootstrap/js/bootstrap.bundle.js - - - 200 217110 application/javascript 27.0797ms
Request finished HTTP/2 GET https://localhost:6443/vendor/fontawesome-free/webfonts/fa-solid-900.woff2 - - - 200 74316 font/woff2 7.5093ms
Request finished HTTP/2 GET https://localhost:6443/img/header.jpg - - - 200 125976 image/jpeg 8.8118ms
Request finished HTTP/2 GET https://localhost:6443/img/projects/thumbnails/3.jpg - - - 200 48228 image/jpeg 2047.9398ms
Request finished HTTP/2 GET https://localhost:6443/img/projects/thumbnails/1.jpg - - - 200 63788 image/jpeg 2048.1958ms
Request finished HTTP/2 GET https://localhost:6443/img/logo-title.svg - - - 200 6816 image/svg+xml 2048.5128ms
Request finished HTTP/2 GET https://localhost:6443/img/projects/thumbnails/5.jpg - - - 200 62334 image/jpeg 2047.8151ms
Request finished HTTP/2 GET https://localhost:6443/img/logo.svg - - - 200 520 image/svg+xml 2085.0220ms
Request finished HTTP/2 GET https://localhost:6443/img/projects/thumbnails/4.jpg - - - 200 49055 image/jpeg 2084.3430ms
Request finished HTTP/2 GET https://localhost:6443/img/projects/thumbnails/2.jpg - - - 200 48101 image/jpeg 2084.5715ms
Request finished HTTP/2 GET https://localhost:6443/img/references/thumbnails/1.svg - - - 200 15832 image/svg+xml 2084.1440ms
Request finished HTTP/2 GET https://localhost:6443/favicon.ico - - - 200 52206 image/x-icon 1.7098ms
```

And from another console window I harvest, for example:
```
 Microsoft.AspNetCore.StaticFiles.StaticFileMiddleware[2]
      Sending file. Request path: '/img/projects/thumbnails/2.jpg'. Physical path: 'C:\Users\Eric\Source\Repos\...\wwwroot\img\projects\thumbnails\2.jpg'
info: Microsoft.AspNetCore.Hosting.Diagnostics[2]
      Request finished in 7.3538ms 200 image/jpeg
```

**Comment by karelz** [comment] 2020-08-11 18:32
@jmezach would you be able to try it with 5.0 RC1 (or daily build) please?
We think that @alnikola's change to enable multiple HTTP/2 connections would help here.

**Comment by jmezach** [comment] 2020-08-12 09:31
I can give that a shot yes, just need to figure out how I get the RC1 bits. Those aren't publicly available yet right? Also, would the fix be in the client (ie. do I run my YARP proxy on RC1) or in the server (ie. do I run my downstream service on RC1)?

**Comment by jmezach** [comment] 2020-08-16 20:02
I just ran the benchmark again on my local machine with Crank's channel setting set to `latest` for my YARP proxy which gives me the following versions:

SDK: **5.0.100-rc.1.20379.10**
.NET Runtime: **5.0.0-rc.1.20415.1**
ASP.NET Runtime: **5.0.0-rc.1.20415.5**

Initially that gave me a small boost in numbers, but then I realized I didn't increase the number of concurrent connections. As soon as I did that, I'm getting a lot of bad responses again:

```
| load                |            |
| ------------------- | ---------- |
| Build Time (ms)     |      3,348 |
| Start Time (ms)     |      2,353 |
| Published Size (KB) |     72,766 |
| First Request (ms)  |      1,135 |
| Requests            |        513 |
| Bad responses       |        512 |
| Mean latency (us)   |  9,909,972 |
| Max latency (us)    | 10,580,132 |
| Requests/sec        |         18 |
| Requests/sec (max)  |      6,213 |
```

Here is a stack trace for a failing request:

```
[09:49:16.747] [21:49:16 ERR] An unhandled exception has occurred while executing the request.
[09:49:16.747] System.OperationCanceledException: The operation was canceled.
[09:49:16.747]    at System.Threading.CancellationToken.ThrowOperationCanceledException()
[09:49:16.747]    at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.ThrowException(SocketError error, CancellationToken cancellationToken)
[09:49:16.747]    at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.GetResult(Int16 token)
[09:49:16.747]    at System.Net.Security.SslStream.<FillHandshakeBufferAsync>g__InternalFillHandshakeBufferAsync|182_0[TIOAdapter](TIOAdapter adap, ValueTask`1 task, Int32 minSize)
[09:49:16.747]    at System.Net.Security.SslStream.ReceiveBlobAsync[TIOAdapter](TIOAdapter adapter)
[09:49:16.747]    at System.Net.Security.SslStream.ForceAuthenticationAsync[TIOAdapter](TIOAdapter adapter, Boolean receiveFirst, Byte[] reAuthenticationData, Boolean isApm)
[09:49:16.747]    at System.Net.Http.ConnectHelper.EstablishSslConnectionAsyncCore(Boolean async, Stream stream, SslClientAuthenticationOptions sslOptions, CancellationToken cancellationToken)
[09:49:16.747]    at System.Net.Http.HttpConnectionPool.ConnectAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
[09:49:16.747]    at System.Net.Http.HttpConnectionPool.CreateHttp11ConnectionAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
[09:49:16.747]    at System.Net.Http.HttpConnectionPool.GetHttpConnectionAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
[09:49:16.747]    at System.Net.Http.HttpConnectionPool.SendWithRetryAsync(HttpRequestMessage request, Boolean async, Boolean doRequestAuth, CancellationToken cancellationToken)
[09:49:16.747]    at Microsoft.ReverseProxy.Service.Proxy.HttpProxy.NormalProxyAsync(HttpContext context, HttpRequestMessage upstreamRequest, Transforms transforms, HttpMessageInvoker httpClient, ProxyTelemetryContext proxyTelemetryContext, CancellationToken shortCancellation, CancellationToken longCancellation)
[09:49:16.747]    at Microsoft.ReverseProxy.Telemetry.TextOperationLogger`1.ExecuteAsync(String operationName, Func`1 action)
[09:49:16.747]    at Microsoft.ReverseProxy.Middleware.ProxyInvokerMiddleware.Invoke(HttpContext context)
[09:49:16.747]    at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
[09:49:16.747]    at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
[09:49:16.747]    at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)
```

Just for the fun of it (and because Crank makes it almost effortless ;)) I also ran the benchmark with my downstream service targetting .NET 5.0 RC 1 as well. Unfortunately I'm still getting similar results with that setup:

```
| load                |            |
| ------------------- | ---------- |
| Build Time (ms)     |      4,603 |
| Start Time (ms)     |      4,365 |
| Published Size (KB) |     72,766 |
| First Request (ms)  |      2,203 |
| Requests            |        556 |
| Bad responses       |        508 |
| Mean latency (us)   |  8,755,657 |
| Max latency (us)    | 10,807,915 |
| Requests/sec        |         20 |
| Requests/sec (max)  |      3,259 |
```

And the stacktrace looks pretty similar as well:

```
[09:59:42.979] [21:59:42 ERR] An unhandled exception has occurred while executing the request.
[09:59:42.979] System.OperationCanceledException: The operation was canceled.
[09:59:42.979]    at System.Threading.CancellationToken.ThrowOperationCanceledException()
[09:59:42.979]    at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.ThrowException(SocketError error, CancellationToken cancellationToken)
[09:59:42.979]    at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.GetResult(Int16 token)
[09:59:42.979]    at System.Net.Security.SslStream.<FillHandshakeBufferAsync>g__InternalFillHandshakeBufferAsync|182_0[TIOAdapter](TIOAdapter adap, ValueTask`1 task, Int32 minSize)
[09:59:42.979]    at System.Net.Security.SslStream.ReceiveBlobAsync[TIOAdapter](TIOAdapter adapter)
[09:59:42.979]    at System.Net.Security.SslStream.ForceAuthenticationAsync[TIOAdapter](TIOAdapter adapter, Boolean receiveFirst, Byte[] reAuthenticationData, Boolean isApm)
[09:59:42.979]    at System.Net.Http.ConnectHelper.EstablishSslConnectionAsyncCore(Boolean async, Stream stream, SslClientAuthenticationOptions sslOptions, CancellationToken cancellationToken)
[09:59:42.979]    at System.Net.Http.HttpConnectionPool.ConnectAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
[09:59:42.979]    at System.Net.Http.HttpConnectionPool.CreateHttp11ConnectionAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
[09:59:42.979]    at System.Net.Http.HttpConnectionPool.GetHttpConnectionAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
[09:59:42.979]    at System.Net.Http.HttpConnectionPool.SendWithRetryAsync(HttpRequestMessage request, Boolean async, Boolean doRequestAuth, CancellationToken cancellationToken)
[09:59:42.979]    at Microsoft.ReverseProxy.Service.Proxy.HttpProxy.NormalProxyAsync(HttpContext context, HttpRequestMessage upstreamRequest, Transforms transforms, HttpMessageInvoker httpClient, ProxyTelemetryContext proxyTelemetryContext, CancellationToken shortCancellation, CancellationToken longCancellation)
[09:59:42.979]    at Microsoft.ReverseProxy.Telemetry.TextOperationLogger`1.ExecuteAsync(String operationName, Func`1 action)
[09:59:42.979]    at Microsoft.ReverseProxy.Middleware.ProxyInvokerMiddleware.Invoke(HttpContext context)
[09:59:42.979]    at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
[09:59:42.979]    at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
[09:59:42.979]    at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)
```

**Comment by davidfowl** [comment] 2020-08-17 04:33
Can you share the crank scenario?

**Comment by jmezach** [comment] 2020-08-17 05:55
Sure thing, here's my Crank YAML:

```yml
imports:
    - https://raw.githubusercontent.com/dotnet/crank/master/src/Microsoft.Crank.Jobs.Bombardier/bombardier.yml

jobs:
  gateway:
    source:
      localFolder: .
      project: ApiGateway/ApiGateway.csproj
    readyStateText: Application started.
  echoService:
    source:
      localFolder: .
      project: echoService/EchoService.csproj
    readyStateText: Application started.

scenarios:
  # This scenario covers the gateway simply passing the request through to the downstream service
  no-gateway-auth:
    gateway:
      job: gateway
    echoService:
      job: echoService
    load:
      job: bombardier
      variables:
        serverPort: 5000
        path: /realization
        #connections: 100

profiles:
  local:
    variables:
      serverUri: http://localhost
    jobs: 
      gateway:
        endpoints: 
          - http://localhost:5010
      echoService:
        endpoints:
          - http://localhost:5010
      load:
        endpoints: 
          - http://localhost:5010
```

When I uncomment the `connections` variable for the `bombardier` job it works just fine.

**Comment by jmezach** [comment] 2020-09-12 07:51
Any updates on this?

**Comment by karelz** [comment] 2021-03-29 18:27
@alnikola can you please check if we have this covered in our perf suite?
Or is it another scenario we should look at? (should it be v1 or later)

**Comment by alnikola** [comment] 2021-03-31 11:42
@jmezach Could you please confirm that you are using HTTPS on **HTTP 1.1** protocol between client and proxy and between proxy and server?

We haven't seen any similar issues in our performance tests of HTTPS - HTTP and HTTPS - HTTPS on *HTTP 1.1* scenarios. However, since it fails with a timeout exception, it could be somehow related to YARP's timeouts. Could you please try adding an explicit request timeout parameter as shown below?
```JSON
      "EchoService": {
        "LoadBalancing": {
          "Mode": "Random"
        },
        "HttpRequest": {
          "Timeout": "00:01:00"
        }
      }
```

**Comment by jmezach** [comment] 2021-04-02 06:35
I just re-ran the benchmark with the latest bits (.NET 5.0.4, YARP preview 10) and I'm still seeing the same behaviour in the scenario where I'm doing request to my YARP proxy using HTTP and then proxying to a downstream service using HTTPS. Interestingly @Tratcher mentioned [here](https://github.com/microsoft/reverse-proxy/issues/355#issuecomment-667188674) that YARP defaults to HTTP/2 when proxying to HTTPS, but that is not what I'm seeing in the logs currently. Requests to my downstream service are made using HTTP/1.1. As far as I know I don't have to do anything special for an ASP.NET Core 5.0 service to enable HTTP/2, correct?

Adding the timeout as suggested by @alnikola also doesn't seem to help in this scenario as I'm getting similar results. For reference, here are the results I'm seeing with the default number of concurrent connections for the bombardier job in the HTTP -> HTTPS scenario:

```
| load                   |            |
| ---------------------- | ---------- |
| Start Time (ms)        | 130        |
| First Request (ms)     | 1,881      |
| Requests               | 512        |
| Bad responses          | 512        |
| Mean latency (us)      | 9,549,326  |
| Max latency (us)       | 10,040,422 |
| Requests/sec           | 17         |
| Requests/sec (max)     | 6,392      |
| Read throughput (MB/s) | 0.00       |
```

Limiting the number of connections to 100 I'm seeing the following:

```
| load                   |         |
| ---------------------- | ------- |
| Start Time (ms)        | 111     |
| First Request (ms)     | 1,532   |
| Requests               | 16,469  |
| Bad responses          | 0       |
| Mean latency (us)      | 91,122  |
| Max latency (us)       | 275,196 |
| Requests/sec           | 1,121   |
| Requests/sec (max)     | 6,321   |
| Read throughput (MB/s) | 0.30    |
```

Please note that I'm running these benchmarks on my development machine.

**Comment by Tratcher** [comment] 2021-04-02 15:50
> Interestingly @Tratcher mentioned [here](https://github.com/microsoft/reverse-proxy/issues/355#issuecomment-667188674) that YARP defaults to HTTP/2 when proxying to HTTPS, but that is not what I'm seeing in the logs currently. Requests to my downstream service are made using HTTP/1.1. As far as I know I don't have to do anything special for an ASP.NET Core 5.0 service to enable HTTP/2, correct?

You're running on MacOS? Kestrel does not support HTTP/2 over HTTPS on MacOS due to platform limitations (https://github.com/dotnet/runtime/issues/27727).

**Comment by jmezach** [comment] 2021-04-02 17:56
Yes, I am running on MacOS. So I guess that explains why I'm not seeing HTTP/2 requests to my downstream service. Question is, does it also explain the poor performance?

**Comment by Tratcher** [comment] 2021-04-02 18:09
It might explain why the number of incoming connections affects it. Do your tests have a warm-up period?

HTTP/2 (until recently) defaulted to using a single connection for all requests to the destination. HTTP/1.1 will spin up as many connections as there are active requests, and will only start re-using connections after they became free. Starting 512 HTTPS connections ends up being more expensive than starting 100, queuing other requests, and then re-using the connections.

**Comment by alnikola** [comment] 2021-04-06 09:24
YARP doesn't queue HTTP 1.1 requests, so if client simultaneously sends 512 requests on 512 connections to the same downstream, YARP will try to open 512 connections to the downstream. It seems that in this case server cannot respond in time to 512 HTTPS connect requests, thus the connect operations time out. Increasing the connect timeout could help here, but YARP currently doesn't expose `SocketsHttpHandler.ConnectTimeout` as a configuration parameter. However, you can implement a custom `IProxyHttpClientFactory` where this property can be set directly.

**Comment by davidfowl** [comment] 2021-04-06 09:45
This seems like something we should handle better.

**Comment by Tratcher** [comment] 2021-04-06 23:20
@davidfowl how so? Any burst of traffic would be subject to this kind of issue, and the costs are mainly on the destination. The best the proxy can do is limit request concurrency with settings like MaxConnectionsPerServer.

I've occasionally suggested that the HttpClient create connections more like the threadpool, only injecting new ones slowly after a certain minimum. That would help mitigate bursts like this. It can be faster to wait for an existing connection to free up than to create a new one.

**Comment by davidfowl** [comment] 2021-04-08 02:47
Spoke to @Tratcher offline. @alnikola I think we need to do something to address this scenario on in YARP. Can we setup a benchmark that will show this behavior, I'm convinced it's bad enough that we need to do something to make sure performance is stable.

**Comment by alnikola** [comment] 2021-04-12 15:28
If I understood correctly, the issue is caused by a slow server which cannot complete SSL handshakes in the given timeout. I think we can setup a benchmark environment for this, but it will require some research first to understand how to properly slow down the server. Though, I'm not fully understand what **performance** metrics we want to measure here. It seems to be more about a missing feature in traffic management area than performance.

**Comment by Tratcher** [comment] 2021-04-12 21:12
Theory: When the destination server has slow handshakes it's faster to queue some requests than to keep making new connections.

Benchmark: Send a burst of 1000(?) requests to the proxy, see how long it takes all of them to complete, and if any fail.
- What destination handshake latency should we simulate? This could be artificially induced using a connection middleware in the destination's Kestrel server.

**Comment by alnikola** [comment] 2021-04-13 08:04
OK. It's clear now. I will add it to the performance backlog.

**Comment by karelz** [comment] 2021-07-20 18:20
Triage: This should be now improved in 6.0 by https://github.com/dotnet/runtime/issues/44818
Closing for now.

**Closed by karelz** 2021-07-20 18:20 UTC
Labels: Triage: Info Needed, Type: Bug, tenet-performance
