### ISSUE TITLE
POST/PUT fails with statuscode 415 in .net core 3.1

### ISSUE THREAD

**Issue by SParekh** [microsoft/reverse-proxy#281] opened 2020-07-01 19:40 UTC
# Description
Reverse proxy for POST/PUT requests where  Http Feature - IsUpgradableRequest is true, upstream system receives empty request body. This results in error 415 returned in response. 

https://github.com/microsoft/reverse-proxy/blob/ea33e9cffd7723d2895cde9f851d7d5033b76400/src/ReverseProxy/Service/Proxy/HttpProxy.cs#L277

a. Cloned the repo locally
b. Updated method (UpgradableProxyAsync) to add SetupCopyBodyUpstream before "step 3" 
c. requests to PUT/POST are processed successfully.

# Who is the bug affecting?
.net core 3.1 apps as default to HTTP/1.1 for proxying upgradable requests 

# When does this occur?
reverse proxy for POST/PUT requests

# How to replicate the issue?
a. Setup .net core 3.1 api with microsoft.reverseproxy setup
b. Setup routing for put/post to upstream system
c. Client app or Postman to invoke PUT/POST request

**Comment by Tratcher** [comment] 2020-07-01 19:41
Duplicate of https://github.com/microsoft/reverse-proxy/issues/255. Note this only happens in IIS/Express.

**Closed by Tratcher** 2020-07-01 19:41 UTC
Labels: Type: Bug
