### ISSUE TITLE
View routes at runtime ala OpenAPI/Swagger

### ISSUE THREAD

**Issue by amweiss** [microsoft/reverse-proxy#1107] opened 2021-06-23 00:02 UTC
### What should we add or change to make your life better?
Add a way to hook in something like https://github.com/domaindrivendev/Swashbuckle.AspNetCore to produce a consumable view of the routes at runtime.

It seems like if there's a way to expose the configured routes to `ApiExplorer`, the above package might just work?

### Why is this important to you?
This would allow us to produce API documentation that can link to the connected systems including the route through YARP to use to access them.

**Comment by Tratcher** [comment] 2021-06-23 03:33
We do have these ConfigureEndpoint callbacks that would let you add metadata to routes.
https://github.com/microsoft/reverse-proxy/blob/fe59a44d3241b35ec175470939077897ffb3e5b3/src/ReverseProxy/Routing/ReverseProxyConventionBuilder.cs#L78

@halter73 what would we need to add to routes for Swagger light up?

That said, I'd expect a swagger doc for the proxy routes to be misleading since they usually include wildcards that map to multiple routes on the destination system?

**Comment by amweiss** [comment] 2021-06-23 10:05
I agree it's not perfect and would be open to anything that makes sense. Even just an option to spit back out a sanitized serialized config at runtime for some basics would work. Swagger seemed like it might be close enough, but yes, it might be misleading.

**Comment by samsp-msft** [comment] 2021-06-24 18:27
@amweiss - can we step back a moment. What are you trying to accomplish here? Do you need swagger as the output format, or is what you are looking for a way to get a dumping of the route table?

> ### Why is this important to you?
> This would allow us to produce API documentation that can link to the connected systems including the route through YARP to use to access them.

Unless you are extremely specific in your route definitions, YARP is not going to know much about the endpoints for your app(s). So getting a dumping of the routes is not going to tell you what the API names and parameters are. You will really only get that information from the destination servers.

Depending on how you have configured the URL transformation in YARP - you may need to transform the data from swashbuckle for the destinations. If its using relative URLs then you should be able to set the `RoutePrefix`, and the API infomation is generated [relative to that.](https://github.com/domaindrivendev/Swashbuckle.AspNetCore#working-with-virtual-directories-and-reverse-proxies)

**Comment by amweiss** [comment] 2021-06-24 18:39
@samsp-msft the request was:

> produce a consumable view of the routes at runtime.

So all I'm looking for is a way to view the routes at runtime over http. This could be combined with our service swagger to allow for developers to know how to reach the endpoints they want to call.

**Comment by samsp-msft** [comment] 2021-06-24 18:45
Thanks, seems to be along the same lines as #124 and #1069

**Comment by amweiss** [comment] 2021-06-24 19:46
Ah yeah, happy to close this in favor of more votes for #125 (and subsequently #124)

**Comment by karelz** [comment] 2021-06-25 10:07
Duplicate of #124

**Closed by karelz** 2021-06-25 10:07 UTC
Labels: Type: Idea
