### ISSUE TITLE
HTTP/2 connection to YARP with HTTP/1.1 to backend fails

### ISSUE THREAD

**Issue by devbeard** [microsoft/reverse-proxy#583] opened 2020-11-29 16:34 UTC
### Describe the bug
I have set up a sample application with routing from https://localhost:5001 to a docker container that echoes all received headers. The container is running on http://localhost:8080. It responds with a connection=keep-alive, causing f.ex. curl to complain as this is not valid in the http/2 context.

```
* http2 error: Invalid HTTP header field was received: frame type: 1, stream: 1, name: [connection], value: [keep-alive]
* HTTP/2 stream 1 was not closed cleanly: PROTOCOL_ERROR (err 1)
```

**Question:** Is this a supported scenario - i.e. going from a secured, HTTP/2 channel with a HTTP/1.1 backend? Is it the client  (which has no knowledge of this) or proxy that is responsible of adhering to the protocol change?

### To Reproduce
Run some image on a non-HTTPS binding. Example:
`docker run -p 8080:8080 brndnmtthws/nginx-echo-headers`

Run a simple YARP instance pointing all traffic to http://localhost:8080
`dotnet run ReverseProxySample`

From WSL or similar, do a curl
`curl --insecure -v https://localhost:5001`

### Further technical details

- Include the version of the packages you are using
`1.0.0-preview.7.*`

- The platform (Linux/macOS/Windows)
`Linux and Windows`

**Comment by Tratcher** [comment] 2020-11-29 23:07
Yes HTTP/2 -> Http/1.1 is supported, but there are certainly gaps like this we need to address. This was likely caused by a gap in Kestrel that wasn't enforcing protocol specific headers like this, it was just fixed in the .NET 6.0 branch (https://github.com/dotnet/aspnetcore/pull/24543). We'll need to work around it in YARP for .NET 3.1 and 5.0.

The relevant code is here:
https://github.com/microsoft/reverse-proxy/blob/5291514a487f8ccb3866d94b541674c964367db8/src/ReverseProxy/Service/Proxy/HttpProxy.cs#L708-L713

Also related: https://github.com/microsoft/reverse-proxy/issues/439

**Comment by Tratcher** [comment] 2020-11-29 23:11
Mitigation: Response header transforms can remove unwanted headers.
https://microsoft.github.io/reverse-proxy/articles/transforms.html#responseheader

```
{
  "ResponseHeader": "Connection",
  "Set": "",
  "When": "Always"
}
```

**Comment by devbeard** [comment] 2020-11-30 12:46
Thanks @Tratcher. I'll give the workaround a go.

**Comment by samsp-msft** [comment] 2020-12-08 19:41
Traige: Need to fix for preview 8 as its a mainline scenario

**Closed** 2021-01-15 14:38 UTC
Labels: Type: Bug
