### ISSUE TITLE
Timeout configure not work

### ISSUE THREAD

**Issue by CwjXFH** [microsoft/reverse-proxy#2581] opened 2024-08-22 06:47 UTC
Hi, 

I configured the timeout as described in [the documentation](https://microsoft.github.io/reverse-proxy/articles/timeouts.html), but it didn't work.

Environment:
|sdk|yarp version|
|---|---|
|.NET 8 |2.2.0-preview.1.24266.1|

My configuration and code are as follows:
```json
{
  "ReverseProxy": {
    "Routes": {
      "test_header_route": {
        "ClusterId": "test_cluster",
        "Timeout": "00:00:01",
        // "TimeoutPolicy": "basicPolicy",
        "Match": {
          "Hosts": [
            "*"
          ],
          "Headers": [
            {
              "Name": "X-Custome-Id",
              "Values": [
                "666"
              ],
              "Mode": "ExactHeader"
            }
          ]
        }
      }
    },
    "Clusters": {
      "test_cluster": {
        "Destinations": {
          "node1": {
            "Address": "https://www.google.com",
            "Methods": [
              "POST",
              "GET"
            ]
          }
        }
      }
    }
  }
}
```

```c#
var builder = WebApplication.CreateBuilder(args);

builder.Services
	// .AddRequestTimeouts(opt => opt.DefaultPolicy = new Microsoft.AspNetCore.Http.Timeouts.RequestTimeoutPolicy { Timeout = TimeSpan.FromSeconds(1) }) work
        //.AddRequestTimeouts(opt => opt.AddPolicy("basicPolicy", TimeSpan.FromMilliseconds(1000))) not work
	.AddRequestTimeouts() // not work
	.AddReverseProxy()
	.LoadFromConfig(builder.Configuration.GetSection("ReverseProxy"));

var app = builder.Build();
app.UseRequestTimeouts();
app.MapReverseProxy();
await app.RunAsync();
```

The `Timeout` configuration is not working. I sent a request, and it takes about 15s to return 504 Gateway Timeout.

**Comment by MihaZupan** [comment] 2024-08-22 16:44
I can't reproduce that.

Note that request timeouts do not apply when you have a debugger attached.
Are you seeing the same behavior without one?

**Comment by CwjXFH** [comment] 2024-08-23 05:50
Hi,

I changed Timeout from **00:00:01** to **00:00:1** and it works, strange.

But when the request timed out, it returned a 400 instead of a 504.

**Comment by MihaZupan** [comment] 2024-08-27 13:33
> I changed Timeout from 00:00:01 to 00:00:1 and it works, strange.

Both are parsed to the same value when reading the configuration file and as such behave exactly the same way. Are you sure you did not make any other changes?

Are you able to create a minimal runnable repro for the issue?

> But when the request timed out, it returned a 400 instead of a 504.

When a timeout is hit, you're effectively terminating the request from the client as far as YARP is concerned.

If you were seeing that in a browser, it's possible that you're seeing a manufactured error the browser came up with when the request failed.

Since the timeout can occur at any point during a request/response, it's also possible that YARP already responded with a status code, but the request was canceled while we were copying data back to the client. At that point, the status code has already been sent, so it can't change.

**Comment by karelz** [comment] 2024-09-10 17:43
Triage: Closing as answered. Let us know if we missed anything.

**Closed by karelz** 2024-09-10 17:43 UTC
Labels: Type: Bug, needs more info

**Comment by alekseikhripunov** [comment] 2024-11-20 12:26
Hello,

Confirming the same behavior on the 2.2.0 release, but let me add more details.
> But when the request timed out, it returned a 400 instead of a 504.

Trying to configure timeouts with [`ForwarderRequestConfig.ActivityTimeout`](https://microsoft.github.io/reverse-proxy/articles/http-client-config.html#httprequest) on a cluster and [`Timeout/TimeoutPolicy`](https://microsoft.github.io/reverse-proxy/articles/timeouts.html#configuration) on a route, but results are different: the first configuration returns `504 Gateway Timeout`, second - returns `400 Bad Request`. Shouldn't the results be the same?

@MihaZupan, created a [repository](https://github.com/alekseikhripunov/yarp-timeouts-playground), please have a look.
> Are you able to create a minimal runnable repro for the issue?

**Comment by alekseikhripunov** [comment] 2024-11-20 14:03
Hello,

Confirming the same behavior on the 2.2.0 release, but let me add more details.
> But when the request timed out, it returned a 400 instead of a 504.

Trying to configure timeouts with [`ForwarderRequestConfig.ActivityTimeout`](https://microsoft.github.io/reverse-proxy/articles/http-client-config.html#httprequest) on a cluster and [`Timeout/TimeoutPolicy`](https://microsoft.github.io/reverse-proxy/articles/timeouts.html#configuration) on a route, but results are different: the first configuration returns `504 Gateway Timeout`, second - `400 Bad Request`. Shouldn't the results be the same?

@MihaZupan, created a [repository](https://github.com/alekseikhripunov/yarp-timeouts-playground), please have a look.
> Are you able to create a minimal runnable repro for the issue?

**Comment by MihaZupan** [comment] 2024-11-21 14:03
See #2662
