### ISSUE TITLE
Replace Metadata IDictionary with a more user friendly type

### ISSUE THREAD

**Issue by Tratcher** [microsoft/reverse-proxy#121] opened 2020-04-28 21:15 UTC
Backend, BackendEndpoint, and ProxyRoute all have `IDictionary<string, string> Metadata` collections for passing in extra data from the data source (config, DB, etc.). 

Pros:
- IDictionary can be easily cloned as part of the atomic config swap infrastructure.
- `IDictionary<string, string>` automatically binds from config.

Cons:
- IDictionary is not a user friendly type. Compare to IConfiguration.
- Config can't bind when there are nested structures, only a flat key-value list.

We want something more user friendly like IConfiguration, but that can still be bound from config and cloned.

RE: https://github.com/microsoft/reverse-proxy/pull/47#discussion_r416230018

**Comment by guibirow** [comment] 2020-05-02 16:21
I was about to open an issue asking something similar and saw this that is pretty much the same.

I've noticed the configuration was based on the code and not the other way around, this why the config didn't make much sense to me when I read the first time.

The first thought I had was, regarding the original configuration structure, below
```
"ReverseProxy": {
  "Backends": {
    "backend1": {
      "Endpoints": {
        "Green": {
          "Address": "https://localhost:10001
        }
      }
    }
  },
```

Shouldn't  the `Backends` and the `Endpoints` be an array? Like below
```
{
  "ReverseProxy":{
    "Backends":[
      {
        "name":"backend1",
        "Endpoints":[
          {
            "Name":"vm1",
            "Address":"https://10.0.0.1:10001/"
          },
          {
            "Name":"vm2",
            "Address":"https://10.0.0.2:10001/"
          }
        ]
      },
      {
        "name":"backend2",
        "Endpoints":[ ]
      }
    ]
  },
  "Routes": [ ]
}
```
The second was about the route structure, I thought a bit convoluted and limited, I've opened the issue #134  to talk about it.

**Comment by Tratcher** [comment] 2020-05-02 18:07
@guibirow this issue is specific to the ProxyRoute.Metadata property. We are having a similar discussion about backends and endpoints being arrays over at https://github.com/microsoft/reverse-proxy/issues/9#issuecomment-622606808.

**Comment by karelz** [comment] 2021-03-24 19:43
Triage: Will be part of API review soon

**Comment by samsp-msft** [comment] 2021-03-24 19:46
Duplicate of #87

**Closed by samsp-msft** 2021-03-24 19:46 UTC
Labels: Type: Enhancement
