### ISSUE TITLE
Request returns forbidden if first candidate requires a failing AuthorizationPolicy

### ISSUE THREAD

**Issue by jurgyy** [microsoft/reverse-proxy#2069] opened 2023-03-14 08:13 UTC
### Describe the bug
In a situation where multiple candidate routes are configured leading to the same endpoint. If the more specific or lower order (higher priority) candidate requires an AuthorizationPolicy that is not statisfied by the request, the API returns a forbidden response even if the lower priority candidate doesn't require any authorization and would succeed.

### To Reproduce

Considering the following configuration:

```json
{
 "AllowedHosts": "*",
 "ReverseProxy": {
   "Routes": {
     "lowerPriority": {
       "ClusterId": "cluster1",
       "Match": {
         "Path": "a/route/{**catch-all}"
       },
       "Order": 999 
     },
     "highPriority": {
       "ClusterId": "cluster1",
       "Match": {
         "Path": "{**catch-all}"
       },
       "Order": 0,
       "AuthorizationPolicy": "customPolicy",
     }
   },
   "Clusters": {
     "cluster1": {
       "Destinations": {
         "cluster1/destination1": {
           "Address": "https://localhost:5001/"
         }
       }
     }
   }
 }
}
```

Note the `Order` properties and the `AuthorizationPolicy` in the `highPriority` route.

In ASP.NET Core the policy can be added in the startup `ConfigureServices` method as follows, though I don't think it's required for the reproduction.

```C#
            services.AddAuthorization(options =>
            {
                options.AddPolicy("customPolicy", policy => policy.RequireClaim("aClaim"));
            });
```

Now sending a request to `https://localhost:5001/a/route/foo` would find both routes as a candidate and since the `highPriority` route has a lower order value would be the preferred route but since the authorization policy fails the server immediately returns a 403 Forbidden response without checking the other candidate while I would argue that the other route candidate should be checked as well.

### Further technical details

- YARP version 2.0.0  
- ASP .NET Core 6.0.0
- Hosted on Azure Kubernetes using base image `mcr.microsoft.com/dotnet/aspnet:6.0.0-bullseye-slim`

### Logs

The logs might be of interest: 

```
2 candidate(s) found for the request path '/a/route/foo'

Endpoint 'highPriority' with route pattern '/a/route/{**catch-all}' is valid for the request path '/a/route/foo'

Endpoint 'lowerPriority' with route pattern '{**catch-all}' is valid for the request path '/a/route/foo'

Request matched endpoint 'highPriority'

Authorization failed. These requirements were not met:  
ClaimsAuthorizationRequirement:Claim.Type=aClaim
```

**Comment by samsp-msft** [comment] 2023-03-14 18:16
@javiercn - is auth considered as part of routing, or is the route resolved first then auth rules are applied?

**Comment by Tratcher** [comment] 2023-03-15 19:31
Authz happens after routing and cannot be used as a route selection criteria. Note this isn't YARP specific, these are AspNetCore behaviors.

**Comment by karelz** [comment] 2023-03-23 17:40
Triage: By Design ASP.NET behavior, closing.

**Closed by karelz** 2023-03-23 17:40 UTC
Labels: Type: Bug
