### ISSUE TITLE
Allow RequestHeader (And/or other transforms) per Cluster

### ISSUE THREAD

**Issue by rafael-herscovici-cko** [microsoft/reverse-proxy#1228] opened 2021-09-03 08:25 UTC
Currently, to access multiple routes on one API,  a `RequestHeader` transform needs to be added for each route.

```
Routes:
[
{ "ClusterId": "my-cluster", "Transforms": [ { "RequestHeader": "X-API-KEY", "Set": "MySecretKey" }],
{ "ClusterId": "my-cluster", "Transforms": [ { "RequestHeader": "X-API-KEY", "Set": "MySecretKey" }],
{ "ClusterId": "my-cluster", "Transforms": [ { "RequestHeader": "X-API-KEY", "Set": "MySecretKey" }],
{ "ClusterId": "my-cluster", "Transforms": [ { "RequestHeader": "X-API-KEY", "Set": "MySecretKey" }],
]
```

Allowing to set a `RequestHeader` on the Cluster, Would allow to specify the `RequestHeader` once, for all calls to the cluster.

**Comment by Kahbazi** [comment] 2021-09-03 08:31
Possible duplicate of https://github.com/microsoft/reverse-proxy/issues/164.

**Comment by rafael-herscovici-cko** [comment] 2021-09-03 08:49
@Kahbazi Indeed a duplicate, sorry about that, couldnt find the others.

**Comment by karelz** [comment] 2021-09-03 09:04
Duplicate of #164

**Comment by karelz** [comment] 2021-09-03 09:05
Thanks @Kahbazi for your help with triage as well! Appreciate it!

**Closed by karelz** 2021-09-03 09:04 UTC
Labels: Type: Idea
