### ISSUE TITLE
Forwarding GET request to downstream SSRS server is failing.

### ISSUE THREAD

**Issue by nstratton-lfa** [microsoft/reverse-proxy#1739] opened 2022-05-27 04:14 UTC
### Describe the bug
Forwarding GET request to downstream SSRS server is failing.

### To Reproduce
Similar to [1476](https://github.com/microsoft/reverse-proxy/issues/1476) I am unable to connect to a downstream service with auth. Although that issue related to a POST request.

I have a 2016 SSRS server that I need to make a JavaScript fetch to. 2016 doesn't have the CORS attributes to set AllowControlAllowOrigin but rather than purchase SQL Server 2019, I would like YARP to proxy the request. I can rewrite the request using http but it fails when using https. I can't use https on my development machine and can only test in IIS. 

Code:

```c#
builder.Services.AddCors(p => p.AddPolicy("corsapp", builder =>
{
    builder.WithOrigins("*").AllowAnyMethod();
}));

builder.Services.AddReverseProxy().ConfigureHttpClient((_, handler) =>
{
    handler.Credentials = CredentialCache.DefaultCredentials;
    handler.PreAuthenticate = true;
}).LoadFromConfig(builder.Configuration.GetSection("ReverseProxy"));
```

### Further technical details

I receive a 502 when using IIS but I am not sure how to find the relevant .net errors that describe what is happening. The IIS W3SVC logs only show a 502 and no details. Failed Request Tracing doesn't appear to have any details either.

This is the SSRS URL I am trying to access. It renders and downloads the report without any interaction from the user.

https://ssrs.myserver.com/Reportserver/Pages/ReportViewer.aspx?/Reports/MyNiceReport&rs:Command=Render&rs:ClearSession=true&rs:Format=PDF&ID=2019

Not sure if http 1.1 is an issue Chrome shows the protocol as http/1.1 when browsing to https://ssrs.myserver.com/Reportserver

1427 added a transform but the content is null in my case.

```c#
.AddTransforms(context =>{
context.AddRequestTransform(async transformContext => {
await transformContext.ProxyRequest.Content.LoadIntoBufferAsync();
});
});
```

Running IIS on Windows 2019.

Any help is greatly appreciated.

**Comment by samsp-msft** [comment] 2022-05-27 06:14
Is the downstream using Kerberos / Windows Auth as YARP explicitly disables those, as they are connection based protocols, which don't work for pool connections which is the basis for YARP.

**Comment by nstratton-lfa** [comment] 2022-05-27 06:41
It's Windows Auth. Is there a way to do this with YARP?

**Comment by Tratcher** [comment] 2022-05-27 17:01
Are you trying to flow the user identity from the client, through the proxy, to the destination? YARP explicitly does not support that.
Or are you trying to authenticate only between the proxy and the destination? That should work.

Logs should be available using these tools:
https://docs.microsoft.com/en-us/aspnet/core/fundamentals/logging/?view=aspnetcore-6.0#configure-logging

**Comment by nstratton-lfa** [comment] 2022-05-28 03:03
Hi Tratcher,
I'm able to take the credentials of the IIS Application pool as DefaultCredentials shown in the code. It's an on-prem, edge case I need to handle, I don't need to proxy every user request, just the js fetch. 
FYI applicationSettings.Json does have "UseDefaultCredentials": "true"
Thanks for the logging info, I'll check that out.

**Comment by nstratton-lfa** [comment] 2022-06-06 03:03
Hello,
A question. I've added this test message

app.Logger.Log(LogLevel.Warning, "This is a SSRS Proxy test message");
app.MapReverseProxy();
app.Run();

When I run the project on my local box, I get this error output because I have self certs.

warn: SSRSProxy[0]
      This is a SSRS Proxy test message
info: Yarp.ReverseProxy.Configuration.ConfigProvider.ConfigurationConfigProvider[1]
      Loading proxy data from config.
info: Yarp.ReverseProxy.Forwarder.HttpForwarder[48]
      Request: An error was encountered before receiving a response.
      System.Net.Http.HttpRequestException: An error occurred while sending the request.
       ---> System.IO.IOException: The request was aborted.
       ---> System.Net.Http.Http2StreamException: The HTTP/2 server reset the stream. HTTP/2 error code 'HTTP_1_1_REQUIRED' (0xd).
         --- End of inner exception stack trace ---

When I run it on the server's IIS I get the test message in the Event Viewer but no helpful stack trace.

My logging section looks like this.

  "Logging": {
    "LogLevel": {
      "Default": "Information",
      "Microsoft": "Warning",
      "Microsoft.Hosting.Lifetime": "Information"
    }
  },
  "EventSource": { // EventSource provider
    "LogLevel": {
      "Default": "Warning" // All categories of EventSource provider.
    }
  },

Can I get that kind of stack trace detail in IIS and where would it be? I don't see it in any of the W3SVC log files.

**Comment by nstratton-lfa** [comment] 2022-06-06 23:16
It will be Client Cert Auth but I included it only as a sample of what I'm looking for.

Where do I find the kind of .net trace I see in the console output on my local box, on the server running IIS? Just don't know where to find it or how to configure it to send the stack trace to the Event Viewer.

**Comment by Tratcher** [comment] 2022-06-07 00:13
See https://docs.microsoft.com/en-us/aspnet/core/test/troubleshoot-azure-iis?view=aspnetcore-6.0#aspnet-core-module-stdout-log-iis

**Comment by nstratton-lfa** [comment] 2022-06-08 21:49
Thank you, I've got the logs. 

When I forward requests to the http SSRS site, I am logged in as the identity running the IIS Application pool. When I use the https site, it looks like I'm getting a 401. Is this a credential issue? The code is exactly as posted at the start of the thread.  

info: Yarp.ReverseProxy.Forwarder.HttpForwarder[56]
      Received HTTP/2.0 response 401.
info: Yarp.ReverseProxy.Forwarder.HttpForwarder[9]
      Proxying to https://ssrs.lifeflight.org.au/Reports/browse/ HTTP/2 RequestVersionOrLower no-streaming
info: Yarp.ReverseProxy.Forwarder.HttpForwarder[48]
      Request: An error was encountered before receiving a response.
      System.Net.Http.HttpRequestException: An error occurred while sending the request.
       ---> System.IO.IOException: The request was aborted.
       ---> System.Net.Http.Http2StreamException: The HTTP/2 server reset the stream. HTTP/2 error code 'HTTP_1_1_REQUIRED' (0xd).
         --- End of inner exception stack trace ---
         at System.Net.Http.Http2Connection.ThrowRequestAborted(Exception innerException)
         at System.Net.Http.Http2Connection.Http2Stream.CheckResponseBodyState()
         at System.Net.Http.Http2Connection.Http2Stream.TryEnsureHeaders()
         at System.Net.Http.Http2Connection.Http2Stream.ReadResponseHeadersAsync(CancellationToken cancellationToken)
         at System.Net.Http.Http2Connection.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
         --- End of inner exception stack trace ---
         at System.Net.Http.Http2Connection.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
         at System.Net.Http.HttpConnectionPool.SendWithVersionDetectionAndRetryAsync(HttpRequestMessage request, Boolean async, Boolean doRequestAuth, CancellationToken cancellationToken)
         at System.Net.Http.AuthenticationHelper.SendWithAuthAsync(HttpRequestMessage request, Uri authUri, Boolean async, ICredentials credentials, Boolean preAuthenticate, Boolean isProxyAuth, Boolean doRequestAuth, HttpConnectionPool pool, CancellationToken cancellationToken)
         at System.Net.Http.DiagnosticsHandler.SendAsyncCore(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
         at Yarp.ReverseProxy.Forwarder.HttpForwarder.SendAsync(HttpContext context, String destinationPrefix, HttpMessageInvoker httpClient, ForwarderRequestConfig requestConfig, HttpTransformer transformer)
info: Microsoft.Hosting.Lifetime[0]
      Application is shutting down...

Here are the appsettings

{
  "Logging": {
    "LogLevel": {
      "Default": "Information",
      "Microsoft": "Warning",
      "Microsoft.Hosting.Lifetime": "Information"
    }
  },
  "AllowedHosts": "*",
  "ReverseProxy": {
    "Routes": {
      "route1": {
        "ClusterId": "httpscluster",
        "Match": {
          "Path": "{**catch-all}",
          "Hosts": [ "pri-node-01.mydomain.local:8443", "localhost:7027" ]
        }
      },
      "route2": {
        "ClusterId": "httpcluster",
        "Match": {
          "Path": "{**catch-all}",
          "Hosts": [ "pri-node-01.mydomain.local:8080", "localhost:5027" ]
        }
      }
    },
    "Clusters": {
      "httpscluster": {
        "Destinations": {
          "destination1": {
            "Address": "https://ssrs.myserver.org.au/"
          }
        },
        "UseDefaultCredentials": "true"
      },
      "httpcluster": {
        "Destinations": {
          "destination1": {
            "Address": "http://ssrs.myserver.org.au/"
          }
        },
        "UseDefaultCredentials": "true"
      }
    }
  }
}

**Comment by karelz** [comment] 2022-06-14 18:20
Triage: We have seen customers running into `HTTP/2 error code 'HTTP_1_1_REQUIRED'` on several occasions, incl. in ASP.NET repo. This is because Windows Auth requires HTTP/1.1. We should add guide how to troubleshoot such cases, so that it is searchable on the internet.

**Comment by nstratton-lfa** [comment] 2022-06-14 22:15
That would be fantastic. This is giving me grief because it's blocking a project I need to complete!

**Comment by samsp-msft** [comment] 2022-06-14 23:21
A quick summary of the issue is that your outbound connections are happening on Http/2 which does not support NTLM etc, as they are connection based protocols. You will need to do a custom configuration for HttpClient, https://microsoft.github.io/reverse-proxy/articles/http-client-config.html#httprequest to specify to use Http1.1 as the RequestVersion.

@Tratcher can add some more color when he's back from Vacation.

**Comment by Tratcher** [comment] 2022-06-15 19:35
It works on HTTP because without encryption the protocol defaults to HTTP/1.1 which works with Windows Auth. When you use HTTPS it negotiates to use HTTP/2 which does not work with Windows Auth, hence the HTTP_1_1_Required error. Sam's suggestion above to change the default protocol for outgoing requests to 1.1 is the best approach here.

**Comment by nstratton-lfa** [comment] 2022-06-15 22:49
That was it. Connection is made. 

The funny thing is I'm back to square one. I was trying to add CORS to my SSRS server so I can do a fetch from JavaScript. I've added this proxy in an attempt to provide CORS but js sees the redirect, detects the final source has no CORS and blocks the call. :)

      "httpscluster": {
        "HttpRequest": {
          "Version": "1.1",
          "VersionPolicy": "RequestVersionExact"
        },
        "Destinations": {
          "destination1": {
            "Address": "https://ssrs.myserver.org.au/"
          }
        },
        "UseDefaultCredentials": "true"
      },

**Comment by Tratcher** [comment] 2022-06-15 22:56
Redirect?

**Comment by nstratton-lfa** [comment] 2022-06-15 22:59
This is the error from js

Access to fetch at 'https://ssrs.myserver.org.au/ReportServer?/FlightOpsReports/FW_ABFInwards…t&rs:Command=Render&rs:ClearSession=true&rs:Format=PDF&FlightSectorID=2019' (**redirected** from 'https://pri-node-01.mydomain.local:8443/Reportserver/Pages/ReportViewer.as…t&rs:Command=Render&rs:ClearSession=true&rs:Format=PDF&FlightSectorID=2019') from origin 'https://myserver-dev.onk2.com' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.

**Comment by Tratcher** [comment] 2022-06-15 23:01
Side note: `UseDefaultCredentials` is not a cluster level setting, that's likely being ignored in your config. That option only exists under the Cluster/HttpClient/WebProxy node.

**Comment by Tratcher** [comment] 2022-06-15 23:05
Interesting. That redirect wasn't directly caused by the proxy, the backend did that, you'd need to figure out why it did that. Is the host the only part of the redirected url that's different?

**Comment by karelz** [comment] 2022-06-23 16:46
Triage: Not enough information to make it actionable. Closing. Feel free to reopen if we missed anything, or if there is additional info available. Thanks!

**Closed by karelz** 2022-06-23 16:46 UTC
Labels: Type: Bug, needs more info
