### ISSUE TITLE
No Multi Path Static File Mapper

### ISSUE THREAD

**Issue by lixiaoqiang** [microsoft/reverse-proxy#2228] opened 2023-08-28 10:17 UTC
Doc so we can close it

_Originally posted by @samsp-msft in https://github.com/microsoft/reverse-proxy/issues/187#issuecomment-989546302_
            
I want to use yarp in some senaros like :
| path | MapTo|
|:------|:-------|
| /{**catch-all} |  a static file folder with some static files, if provider "/" only map to index.html file |
| /apps/{**catch-all}| a static file folder with some static files, if provider "/apps" only map to index.html file. <br/> eg. <br/> /app map to index.html under the folder <br/> /app/index.html to index.html too. |
| /api/{**catch-all}| a backend service may be http://192.168.0.1:8080/ |
|/api-mobile/{**catch-all}| a backend service may be http://192.168.0.2:8080/ |

The backend proxy is easy to config. But I've no idea for two static folder map ("/" and "/apps").

**Comment by karelz** [comment] 2023-08-29 17:26
Duplicate of #187

**Closed by karelz** 2023-08-29 17:26 UTC

**Comment by lixiaoqiang** [comment] 2023-09-05 01:38
For first aid to my project. I  provider a rough temp solution to this problem. May be usefull for other users.
* Provider a composite file provider. for each detail file provider in this composite provider a url prefix to match the Folder.
  And use this file provider fo UseStaticFile method.

* Provider a DefaultFileMiddleware.  I also provider a url and default file mapping. When a GET request hit no endpoint use the mapping to match , if match file return file to response. 
```csharp

    public Task Invoke(HttpContext context)
    {
        if (context.GetEndpoint()?.RequestDelegate is null &&
            IsGetOrHeadMethod(context.Request.Method) &&
            MatchFile(context, out var matchFile))
        {
            context.Request.Path = matchFile;
        }
        return _next(context);
    }

    private bool MatchFile(HttpContext context, out PathString matchFile)
    {
        var path = context.Request.Path;
        if (!(path.HasValue && path.Value!.EndsWith("/")))
        {
            path += new PathString("/");
        }
        
        var config = _configs.FirstOrDefault(it => it.RequestPath == path);
        if (config == null)
        {
            matchFile = PathString.Empty;
            return false;
        }
        var relativePath = path.ToString()[config.RequestPath.ToString().Length..];
        var dictContents = config.FileProvider.GetDirectoryContents(relativePath);
        if (dictContents.Exists)
        {
            for (int matchIndex = 0; matchIndex < config.Files.Count; matchIndex++)
            {
                var defaultFile = config.Files[matchIndex];
                var file = config.FileProvider.GetFileInfo(relativePath + defaultFile);
                if (file.Exists)
                {
                    matchFile = path + defaultFile;
                    return true;
                }
            }
        }
        matchFile = PathString.Empty;
        return false;
    }
```
