### ISSUE TITLE
[Tracking] Early filtering SSL 

### ISSUE THREAD

**Issue by samsp-msft** [microsoft/reverse-proxy#53] opened 2020-04-15 17:45 UTC
Be able to filter connections at SSL connection time to prevent DoS attacks

**Comment by anurse** [comment] 2020-04-16 16:21
Specifically, this involves being able to filter connections based on information contained in the ClientHello TLS frame. Examples include:

* Cipher Suite selection
* Protocol Version
* Server Name Indication (SNI)
* Application-Level Protocol Negotiation (ALPN; used for HTTP/2 and HTTP/3)

**Comment by karelz** [comment] 2020-05-07 18:39
Duplicate of #16

**Closed by karelz** 2020-05-07 18:39 UTC
Labels: Type: Tracking
