### ISSUE TITLE
make public docker image available in dockerhub with some common configurations

### ISSUE THREAD

**Issue by jkone27** [microsoft/reverse-proxy#2390] opened 2024-02-02 11:29 UTC
### What should we add or change to make your life better?

would be greate to have a simple aspnetcore with only reverse proxy easilly configurable as docker image, to be used easilly in docker or docker compose! possibly using appsettings.json configuration to configure the proxy capabilities and environment variables 

### Why is this important to you?

can be easilly used by infra engineers also who do not have knowledge of .net just configuring some json and variables in docker

**Comment by witskeeper** [comment] 2024-02-06 03:28
I have made a template project and a ingress controller project  for yarp.
Maybe these two projects are helpful.
See: 
<https://github.com/netcorepal/netcorepal-ingress-controller>
<https://github.com/netcorepal/netcorepal-yarp-template>

**Comment by MihaZupan** [comment] 2024-02-06 09:01
Duplicate of #247

**Closed by MihaZupan** 2024-02-06 09:01 UTC
Labels: Type: Idea
