### ISSUE TITLE
Random 502 errors when client cancels request

### ISSUE THREAD

**Issue by alkampfergit** [microsoft/reverse-proxy#2070] opened 2023-03-14 14:03 UTC
### Random 502 errors when ui cancels the request.
We have an Angular UI application that talks to an ASP.NET webservice hosted in IIS and proxyed with YARP. 
The backend only works with HTTP1.1 not HTTP/2
The error happens only if YARP uses HTTP/2, so the error happens only when YARP needs to proxy HTTP/2 traffic to a HTTP1.1 backend.
The application works as usual and we have some custom ui logic that cancels some of the requests, when the requests is cancelled YARP returns 502.

### To Reproduce
I had not created a reproducible working scenario but I think that it is enough to issue a request then immediately cancels. From the browser I can see that the request has content-lenght of some bytes (49 in the above example) but the request was cancelled before the first byte of the content was transmitted so YARP complained.

```
2023-03-14 14:52:36.832 +01:00 [INF] Proxying to http://localhost/api/v1/omnisearch/view-config HTTP/2 RequestVersionOrLower no-streaming
2023-03-14 14:52:36.836 +01:00 [INF] "Request": An error was encountered before receiving a response.
System.Net.Http.HttpRequestException: Sent 0 request content bytes, but Content-Length promised 49.
   at System.Net.Http.HttpConnection.SendRequestContentAsync(HttpRequestMessage request, HttpContentWriteStream stream, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnection.SendAsyncCore(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnection.SendAsyncCore(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.SendWithVersionDetectionAndRetryAsync(HttpRequestMessage request, Boolean async, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.DiagnosticsHandler.SendAsyncCore(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at Yarp.ReverseProxy.Forwarder.HttpForwarder.SendAsync(HttpContext context, String destinationPrefix, HttpMessageInvoker httpClient, ForwarderRequestConfig requestConfig, HttpTransformer transformer, CancellationToken cancellationToken)
``` 

### Further technical details

- Latest YARP packages, on .NET 7 windows environment.

**Comment by samsp-msft** [comment] 2023-03-14 18:13
What are you expecting instead? 

If you cancel a request, then the proxy isn't getting the information that it expects, so it returns an error.

**Comment by alkampfergit** [comment] 2023-03-15 10:21
Actually without the proxy, the ui cancels the request and the user has no visual indication that the query was canceled. In chrome developer toolbar I only see the request as Canceled while with the proxy the call receives a 502 error code.

Since from angular point of view the call is not canceled but the server returned an error it triggers our catch error routine that in turn shows to the user a "call failed message", resulting in a puzzled user because everything works as expeceted but he is seeing random "call errors".

**Comment by alkampfergit** [comment] 2023-03-15 10:27
Another suggestion is: As you can see the error gets logged as INF

```
2023-03-14 14:52:36.836 +01:00 [INF] "Request": An error was encountered before receiving a response.
```

I really like this kind of message to be logged at least in WARN, am I wrong?

**Comment by MihaZupan** [comment] 2023-03-15 16:21
> the ui cancels the request and the user has no visual indication that the query was canceled
> Since from angular point of view the call is not canceled

How is it canceled, but not considered canceled? Can you share a runnable repro js script we could use that demonstrates that?

> I really like this kind of message to be logged at least in WARN, am I wrong?

You're in luck, this was just recently changed to warning in main: #2044

**Comment by alkampfergit** [comment] 2023-03-15 17:19
I'll try to reproduce the error in the next days (tomorrow I have a conference and I'll be busy). Actually it does not happens all the time and seems to be related to cancellation before the client sent all the payload. 

The only thing I've noticed is that, if I disable HTTP/2 protocol on proxy the error never happens.

**Comment by Schaeri** [comment] 2023-03-16 10:02
Hello @MihaZupan Hello @alkampfergit

We have encountered the same problem in our environment. The problem has been found with update to Yarp 2.0.

But here with a Blazor Wasm client, SingalR and GRPC.  The problem seems to occur only with Kestrel. In an IIS environment the problem seems to occur less often. 

Attached you can find a sample application consisting of a WASM client which opens a SignalR connection and then makes a GRPC call. Then the SignalR connection is closed and another GRPC call is made. This is done in a loop until the error occurs. 
[ProblemDemo.zip](https://github.com/microsoft/reverse-proxy/files/10989273/ProblemDemo.zip)

With Yarp, the error occurs after about 120 runs:
`System.IO.IOException: The client reset the request stream.
         at System.IO.Pipelines.Pipe.GetReadResult(ReadResult& result)
         at System.IO.Pipelines.Pipe.ReadAsync(CancellationToken token)
         at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http2.Http2MessageBody.ReadAsync(CancellationToken cancellationToken)
         at System.Runtime.CompilerServices.PoolingAsyncValueTaskMethodBuilder`1.StateMachineBox`1.System.Threading.Tasks.Sources.IValueTaskSource<TResult>.GetResult(Int16 token)
         at Grpc.AspNetCore.Server.Internal.PipeExtensions.ReadSingleMessageAsync[T](PipeReader input, HttpContextServerCallContext serverCallContext, Func`2 deserializer)
fail: Grpc.AspNetCore.Server.ServerCallHandler[6]
      Error when executing service method 'SampleCall'.
      System.IO.IOException: The client reset the request stream.
         at System.IO.Pipelines.Pipe.GetReadResult(ReadResult& result)
         at System.IO.Pipelines.Pipe.ReadAsync(CancellationToken token)
         at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http2.Http2MessageBody.ReadAsync(CancellationToken cancellationToken)
         at System.Runtime.CompilerServices.PoolingAsyncValueTaskMethodBuilder`1.StateMachineBox`1.System.Threading.Tasks.Sources.IValueTaskSource<TResult>.GetResult(Int16 token)
         at Grpc.AspNetCore.Server.Internal.PipeExtensions.ReadSingleMessageAsync[T](PipeReader input, HttpContextServerCallContext serverCallContext, Func`2 deserializer)
         at Grpc.AspNetCore.Server.Internal.CallHandlers.UnaryServerCallHandler`3.HandleCallAsyncCore(HttpContext httpContext, HttpContextServerCallContext serverCallContext)
         at Grpc.AspNetCore.Server.Internal.CallHandlers.ServerCallHandlerBase`3.<HandleCallAsync>g__AwaitHandleCall|8_0(HttpContextServerCallContext serverCallContext, Method`2 method, Task handleCall)`

![ClientError](https://user-images.githubusercontent.com/15650359/225582440-99e81b57-f7bf-4e34-8a32-2ff416ac2d31.png)

Without Yarp the whole thing runs stable:
![NoError](https://user-images.githubusercontent.com/15650359/225580384-e876dd67-4897-4703-8766-9750f4f3bee2.png)

What's even more interesting is that the client then can't make any calls to the server at all. After the error the problem occurs immediately. This can also be reproduced. By pressing the start button again after the error in the sample application. It then aborts after one execution. If you wait about 30 seconds, the system recovers and several calls are possible again. 
Also, the problem can be reproduced more quickly in Chrome than in Firefox. 

Why exactly the problem with GRPC in conjunction with SignalR, we could not exactly identify. We just know that this way the problem is reproducible. And does not occur without Yarp.

**Comment by alkampfergit** [comment] 2023-03-17 07:58
I can add that in our situation we have two different outcome after the first error, 
1. The error occours, then it seems to happen more frequently
2. the error is sistematic, we were not able to do any more call (each one results in the error) until we refresh the page.
Situation 2 happens more rarely than situation 1

**Comment by karelz** [comment] 2023-03-28 17:27
Triage: Thanks for the repro @Schaeri! We're a bit busy, it might take a week or two before we get to it.

**Comment by renatosc** [comment] 2023-04-05 07:56
I am getting similar error here ("Sent 0 request content bytes, but Content-Length promised 29."). I started getting that error after moving my code from the Program.cs to be inside a controller. So for now I will leave it outside of the controller.

**Comment by benjaminpetit** [comment] 2023-04-06 15:57
@Schaeri I was not able to reproduce locally the error with your sample. Is there anything special to setup to trigger the issue?

**Comment by Schaeri** [comment] 2023-04-06 17:42
@benjaminpetit: There are two applications in the ProblemDemo. The server, which contains all GRPC and SingalR endpoints and also delivers the client. The launchSettings.json defines the following URL for the application: https://localhost:7124. The application runs behind the gateway on the URL https://localhost:6001. See lanchSettins.json from the gateway. It is important that gateway and server are started and the application is called via the gateway (https://localhost:6001). Then I have the problem after maximal 200 runs. On Linux I tested with the browser Firefox and Chrome. On Windows only with Chrome.

**Comment by benjaminpetit** [comment] 2023-04-19 14:18
Sorry for not coming back sooner.

If I do launch the demo with `dotnet run --project ...` I see the exception. If I run the dlls directly with `dotnet xxx.dll` the repro doesn't work (not sure why I tried first that way).

We should be able to do a workaround for this issue soon.

Thanks again for the repro.

**Comment by benjaminpetit** [comment] 2023-04-27 14:42
Could you try this fix and see if it behaves like you expected? https://github.com/benjaminpetit/reverse-proxy/tree/fix/extended-connect

I still see failures, but at least the connection isn't botched.

**Comment by Schaeri** [comment] 2023-04-28 06:44
@benjaminpetit Thanks for the help. Unfortunately I am not able to compile the code. We are using .Net 7.0 and I get the following build error:

'Severity	Code	Description	Project	File	Line	Suppression State
Error	CS1061	'string' does not contain a definition for 'IsExtendedConnect' and no accessible extension method 'IsExtendedConnect' accepting a first argument of type 'string' could be found (are you missing a using directive or an assembly reference?)	Yarp.ReverseProxy (net7.0)	C:\Users\rs\Desktop\reverse-proxy\src\ReverseProxy\Forwarder\HttpForwarder.cs	518	N/A
'
HttpForwarder.cs
'#if NET7_0_OR_GREATER
            var connectFeature = request.HttpContext.Features.Get<IHttpExtendedConnectFeature>();
            if (connectFeature?.Protocol?.IsExtendedConnect) // here is the error
            {
                hasBody = false;
            }
#endif'

**Comment by benjaminpetit** [comment] 2023-04-28 12:46
Sorry I merged it a bit fast, it should be ok now

**Comment by Schaeri** [comment] 2023-04-28 14:49
@benjaminpetit: Thank you very much. I was able to test the changes. It seems that our problem is solved. 
The sample now behaves the same with and without the proxy. I have also integrated the new proxy into our applications and there too the problems we had have disappeared. That is very nice. We would be happy if there would be a release soon :smile:

**Closed** 2023-05-02 17:13 UTC
Labels: Type: Bug
