### ISSUE TITLE
HeaderMatchMode.ExactHeader doesn't use List<string> correct

### ISSUE THREAD

**Issue by BlackByteDE** [microsoft/reverse-proxy#1999] opened 2023-01-17 15:22 UTC
### Describe the bug
I generate a config via code and if i deliver a List<string> with more than one entry the matching doesnt work.

### To Reproduce
Some snippets from my code:

`// moduleName = "someName"`
`// clusterId = "someGeneratedName"`
`// header = "someName"`
`// valueList = new List<string>() { "A","B","C" }`
`	routes.Add(new RouteConfig()`
`	{`
`	  RouteId = clusterId,`
`	  ClusterId = clusterId,`
`	  Order = 2,`
`	  Match = new RouteMatch`
`	  {`
`		 Path = $"{moduleName}/" + "{**catch-all}",`
`		 Headers = new[]`
`		 {`
`			new RouteHeader()`
`			{`
`			   Name = header,`
`			   Values = valueList,`
`			   Mode = HeaderMatchMode.ExactHeader`
`			}`
`		 }`
`	  },`

This doesn't work well, with only one entry in the List it works, but after i add one more entry it doesn't match anymore.

i've done a workaround the generate a single entry for each valueList entry this will work but it's ugly.

### Further technical details
Using YARP 1.1.1 in a linux container running in kubernetes enviroment.

**Comment by BlackByteDE** [comment] 2023-01-17 15:45
I use only a single header. For example i want to route a request with a header "someName" value "A" . And after that i would like route a different request with a header "someName" value "B".

At the config i would like to use only a single RouteMatch entry with header="someName", values ={"A","B"}.

**Comment by MihaZupan** [comment] 2023-01-17 16:00
That is how the `ExactHeader` mode behaves.

For a config like
```c#
new RouteHeader()
{
    Name = "SomeName",
    Values = new[] { "A", "B" },
    Mode = HeaderMatchMode.ExactHeader
}
```

It will match requests like
```HTTP
SomeName: A
```
or
```HTTP
SomeName: B
```
or
```HTTP
SomeName: A, B, C
```

> But it doesn't work this way.

How are you testing this? I just double-checked the above with Postman.
Can you share the full configuration?

**Comment by BlackByteDE** [comment] 2023-01-17 16:23
I've tested it with the application. At the moment there is only the config with the workaroud. 
`route =
  {
    "routeId": "affinity_server_1_clientId_0cc2dc49-520b-4356-8747-9c93a6eb2cfd",
    "match": {
      "methods": null,
      "hosts": null,
      "path": "server/{**catch-all}",
      "queryParameters": null,
      "headers": [
        {
          "name": "clientId",
          "values": [
            "0cc2dc49-520b-4356-8747-9c93a6eb2cfd"
          ],
          "mode": 0,
          "isCaseSensitive": false
        }
      ]
    },
    "order": 2,
    "clusterId": "affinity_server_1_clientId",
    "authorizationPolicy": "",
    "corsPolicy": null,
    "metadata": null,
    "transforms": [
      {
        "PathRemovePrefix": "/server"
      },
      {
        "X-Forwarded": "Set",
        "For": "Off",
        "Proto": "Set",
        "Prefix": "Off",
        "HeaderPrefix": "X-Forwarded-"
      },
      {
        "RequestHeader": "X-Forwarded-Prefix",
        "Set": "/server"
      },
      {
        "RequestHeader": "X-Forwarded-Proto",
        "Set": "https"
      }
    ]
  },
  {
    "routeId": "affinity_server_2_clientId_813aabab-3d17-4764-b41f-e4512d574827",
    "match": {
      "methods": null,
      "hosts": null,
      "path": "server/{**catch-all}",
      "queryParameters": null,
      "headers": [
        {
          "name": "clientId",
          "values": [
            "813aabab-3d17-4764-b41f-e4512d574827"
          ],
          "mode": 0,
          "isCaseSensitive": false
        }
      ]
    },
    "order": 2,
    "clusterId": "affinity_server_2_clientId",
    "authorizationPolicy": "",
    "corsPolicy": null,
    "metadata": null,
    "transforms": [
      {
        "PathRemovePrefix": "/server"
      },
      {
        "X-Forwarded": "Set",
        "For": "Off",
        "Proto": "Set",
        "Prefix": "Off",
        "HeaderPrefix": "X-Forwarded-"
      },
      {
        "RequestHeader": "X-Forwarded-Prefix",
        "Set": "/server"
      },
      {
        "RequestHeader": "X-Forwarded-Proto",
        "Set": "https"
      }
    ]
  },
  {
    "routeId": "affinity_server_2_clientId_9954080a-0673-498e-8e40-f6381401562e",
    "match": {
      "methods": null,
      "hosts": null,
      "path": "server/{**catch-all}",
      "queryParameters": null,
      "headers": [
        {
          "name": "clientId",
          "values": [
            "9954080a-0673-498e-8e40-f6381401562e"
          ],
          "mode": 0,
          "isCaseSensitive": false
        }
      ]
    },
    "order": 2,
    "clusterId": "affinity_server_2_clientId",
    "authorizationPolicy": "",
    "corsPolicy": null,
    "metadata": null,
    "transforms": [
      {
        "PathRemovePrefix": "/server"
      },
      {
        "X-Forwarded": "Set",
        "For": "Off",
        "Proto": "Set",
        "Prefix": "Off",
        "HeaderPrefix": "X-Forwarded-"
      },
      {
        "RequestHeader": "X-Forwarded-Prefix",
        "Set": "/server"
      },
      {
        "RequestHeader": "X-Forwarded-Proto",
        "Set": "https"
      }
    ]
  },`

`cluster =  {
    "clusterId": "affinity_server_1_clientId",
    "loadBalancingPolicy": null,
    "sessionAffinity": null,
    "healthCheck": null,
    "httpClient": null,
    "httpRequest": null,
    "destinations": {
      "clientId": {
        "address": "http://10.50.4.150:45537",
        "health": null,
        "metadata": null
      }
    },
    "metadata": null
  },
  {
    "clusterId": "affinity_server_2_clientId",
    "loadBalancingPolicy": null,
    "sessionAffinity": null,
    "healthCheck": null,
    "httpClient": null,
    "httpRequest": null,
    "destinations": {
      "clientId": {
        "address": "http://10.50.4.107:44609",
        "health": null,
        "metadata": null
      }
    },
    "metadata": null
  },
  {
    "clusterId": "default_server",
    "loadBalancingPolicy": null,
    "sessionAffinity": null,
    "healthCheck": {
      "passive": null,
      "active": {
        "enabled": true,
        "interval": "00:00:10",
        "timeout": "00:00:10",
        "policy": "ConsecutiveFailures",
        "path": "/Healthcheck"
      },
      "availableDestinationsPolicy": null
    },
    "httpClient": null,
    "httpRequest": null,
    "destinations": {
      "server_1": {
        "address": "http://10.50.4.150:45537",
        "health": null,
        "metadata": null
      },
      "server_2": {
        "address": "http://10.50.4.107:44609",
        "health": null,
        "metadata": null
      }
    },
    "metadata": {
      "ConsecutiveFailuresHealthPolicy.Threshold": "1"
    }
  },`

**Comment by MihaZupan** [comment] 2023-01-17 19:30
> I've tested it with the application.

Can you create a minimal project that reproduces the unexpected behavior? As it stands I am unable to reproduce the issue.

**Comment by BlackByteDE** [comment] 2023-01-18 10:32
I've tried to recreate the problem with a new simple project but it didn't appear. I will investigate further.
Thanks for your efforts so far, i'll hope i could made a test project or find my mistake.

**Comment by adityamandaleeka** [comment] 2023-01-24 18:42
Not much we can do here without a repro, so I'll close this issue for now.

**Closed by adityamandaleeka** 2023-01-24 18:42 UTC
Labels: Type: Bug

**Comment by BlackByteDE** [comment] 2023-01-27 09:25
I've found the bug. In the original sources i have a own collection where i build the config from. There was a direct reference from one element to the yarp element (the values in RouteHeader). I had to make a ToArray() call to fix this (my Dataelement was a List<string>). Now it's working like expected.
