### ISSUE TITLE
Proxy route endpoint swagger 

### ISSUE THREAD

**Issue by grahamehorner** [microsoft/reverse-proxy#1181] opened 2021-08-13 12:31 UTC
The reserve proxy should be able to aggregate swagger documents from multiple endpoints/routes and present them with/without its swagger document  so api are discoverable with minimal effort and api clients can be generated using standard tooling.

**Comment by samsp-msft** [comment] 2021-08-13 18:47
I would suggest that the ability to morph swagger documents goes against the separation of concerns principal of software design. The core of the proxy is the ability to efficiently marshal requests, translating swagger is something that, by comparison, would be infrequently used, and therefore probably doesn't belong **in** the proxy.
That being said, it would be an interesting tool to have to be able to manipulate swagger documents based on the url mapping of a proxy, but I would suggest its probably more of a command line thing, rather then being built into the core of the proxy.

**Comment by amweiss** [comment] 2021-08-16 12:22
This seems similar to my request of #1107 to have a way to view the endpoints at runtime, and in this case the upstream swagger docs themselves as well. This may be possible via some extension work where you define/lookup the swagger dock of the destination so it can be provided to the URLs parameter of something like [Swashbuckle](https://github.com/domaindrivendev/Swashbuckle.AspNetCore).

https://github.com/domaindrivendev/Swashbuckle.AspNetCore#list-multiple-swagger-documents

**Comment by samsp-msft** [comment] 2021-08-19 16:46
Duplicate of #1107

**Comment by samsp-msft** [comment] 2021-08-19 16:47
The overall problem of fetching route info at runtime via an API is covered by #124. #1107 is the extension to project that into swagger.

Not a feature for YARP 1.0

**Closed by samsp-msft** 2021-08-19 16:47 UTC
Labels: Type: Idea
