### ISSUE TITLE
Add HealthChecks for IHealthChecksBuilder

### ISSUE THREAD

**Issue by Kahbazi** [microsoft/reverse-proxy#127] opened 2020-04-29 00:01 UTC
Add `IHealthCheck` on top of `IHealthChecksBuilder`. Here are some options that this could have:

- YARP is healthy if all endpoints of all backends are healthy.
- YARP is healthy if at least one endpoint of each backend is healthy.
- Determine which backends to do the check for.

**Comment by rynowak** [comment] 2020-04-29 01:37
What kinds of things do you think would consume this data? 

I think a lot more design would be needed to make this actionable, because you'd actually want to return a more sophisticated data payload than just pass/fail/warning.

There's a big philosophical difference between health check usage by a monitoring/alerting system VS an orchestrator:
- monitors usually want some *data* in addition to health
- orchestrators will *restart* your service if it's unhealthy

So the kind of health described here doesn't seem useful for an orchestrator, because it would reboot your proxy if anything goes down 😆 

I can see this being useful for the monitor case, because the proxy is the *keeper of knowledge* about what backends exist. Determining health *from the proxy's point of view* would be useful to a monitoring/alerting system 👍

**Comment by samsp-msft** [comment] 2020-04-29 18:19
+1 to @rynowak's comments. I would suggest rather than having a pass/fail, we focus on what stats would a dashboard or monitoring agent want from the proxy.

- RPS
- Latency info
  - Median
  - Mean
  - P95 / P99
  - Queue sizes
- Failure rates (something went wrong with proxying a request/response
- Throughput B/s
- Same for each Route & Backend

Ideally this can be pulled by listening to Eventsoure / EventCounters internally to the proxy as well as publishing the events to EventPipe for other monitoring tools.

**Comment by davidfowl** [comment] 2020-04-29 19:47
I’d suggest looking at I.M. how to integrate with existing systems for metrics (like promethues)

**Comment by karelz** [comment] 2020-05-14 18:37
Duplicate of #125

**Closed by karelz** 2020-05-14 18:37 UTC
Labels: Type: Idea

**Comment by Kahbazi** [comment] 2020-05-14 18:44
Why is this a duplicate of #125? as @rynowak said this could be useful for monitoring.

> I can see this being useful for the monitor case, because the proxy is the keeper of knowledge about what backends exist. Determining health from the proxy's point of view would be useful to a monitoring/alerting system

**Comment by Tratcher** [comment] 2020-05-14 19:10
#125 is about making sure the proxy infrastructure exposes the right APIs and data to monitor health state. That should provide all of the information needed to build something for IHealthChecksBuilder, and we'll decide at that point if a IHealthChecksBuilder based implementation should be included in-box.

**Comment by samsp-msft** [comment] 2020-05-14 21:28
Duplicate was probably the wrong term; subsumed into #125 would probably be better phrasing.

**Comment by rwkarg** [comment] 2020-05-18 19:54
Metrics would be the most useful way to get status information (ingest to prom, w/e and create alerts off of Routes with no healthy Destinations). The same information that drives #125 would drive these metrics.

Health checks are separate from status monitoring and useful for orchestration (liveness/restart instance or readiness/route traffic) or for a quick post-deployment smoke check.

Having backends down should neither restart the proxy nor remove it from an upstream LB (if you're running multiple proxies). It _should_ send traffic to the proxy so the proxy can return the appropriate response.

- YARP is healthy if it has valid configuration and it is able to respond to requests as configured.

**Comment by ezar** [comment] 2023-11-03 06:04
YARP is healthy if it has valid configuration and it is able to respond to requests as configured.


> Metrics would be the most useful way to get status information (ingest to prom, w/e and create alerts off of Routes with no healthy Destinations). The same information that drives #125 would drive these metrics.
> 
> Health checks are separate from status monitoring and useful for orchestration (liveness/restart instance or readiness/route traffic) or for a quick post-deployment smoke check.
> 
> Having backends down should neither restart the proxy nor remove it from an upstream LB (if you're running multiple proxies). It _should_ send traffic to the proxy so the proxy can return the appropriate response.
> 
> * YARP is healthy if it has valid configuration and it is able to respond to requests as configured.

Is there a method where I indicate the status of the proxy? With that, we can implement an IHealthCheck that tells us if it is working or not, or if it is degraded.

**Comment by Tratcher** [comment] 2023-11-06 21:58
What status? You can get the list of clusters and destinations, enumerate their health state, and report based on that. See IProxyStateLookup https://github.com/microsoft/reverse-proxy/blob/main/src/ReverseProxy/Management/IProxyStateLookup.cs
