### ISSUE TITLE
Missing Config reload when changes applied too fast

### ISSUE THREAD

**Issue by Kahbazi** [microsoft/reverse-proxy#1244] opened 2021-09-14 19:48 UTC
### Describe the bug
In `ProxyConfigManager` whenever `IProxyConfigProvider.GetConfig().ChangeToken` is triggered `ReloadConfigAsync` is called to check the new config and Create the new endpoints if necessary and register `ReloadConfigAsync` as a callback to `IProxyConfigProvider.GetConfig().ChangeToken`.

Now if the changes of the config happens too fast in a way that it happens before `ReloadConfigAsync` register a new callback, a change would be missed.

https://github.com/microsoft/reverse-proxy/blob/3d4957a7266cadd1d08790a31a7c52b2fbe2ac8e/src/ReverseProxy/Management/ProxyConfigManager.cs#L172-L210
### To Reproduce
I couldn't reproduce this bug with unit test! Since the callback to the config changes is happening on another thread I couldn't figure out a way to control the timing of the events.

**Comment by Tratcher** [comment] 2021-09-14 20:29
This is by design. It's ok to miss some updates because each update provides a full config, not an incremental state change.

Example:
- Load config A, subscribe for changes
- Config B becomes available and Config A's change token fires
- Start loading Config B
  - Config C becomes available and Config B's change token fires while still loading
  - Config D becomes available and Config C's change token fires 
- Finish loading Config B and subscribe to Config B's change token
  - Because it's already fired the callback is invoked immediately.
- Load Config D

Delaying the change token subscription should be OK because we should still be notified if we register after it's initially triggered.

Skipping Config C should be OK because Config D contains the full config and we diff that against the current state (Config B) and apply all changes.

Did I miss anything?

**Comment by Kahbazi** [comment] 2021-09-15 07:56
> each update provides a full config, not an incremental state change.

I'm aware of this, and I think the problem still remains.

>   - Config C becomes available and Config B's change token fires while still loading

This is where I think the behavior of `IChangeToken` is different. Note that I could be wrong 😀 
My understanding of `IChangeToken` was that we could register multiple callback to a single token, but once the token triggered we need to register all the callbacks again to the new token. Hence while loading a config no callback would be called because we haven't yet register the callback.

> Delaying the change token subscription should be OK because we should still be notified if we register after it's initially triggered.

I'm not sure about this part. In the following code I assume that I see `config["Name"]` in the console on every file save, but I won't see the second reload if I save the file twice in less than 5 seconds.

```csharp
var config = new ConfigurationBuilder()
    .AddJsonFile("data.json", optional: false, reloadOnChange: true)
    .Build();

var token = config.GetReloadToken();

token.RegisterChangeCallback(Reload, config);

while (true)
{

}

static async void Reload(object obj)
{
    var config = obj as IConfiguration;

    Console.WriteLine(config["Name"]);

    await Task.Delay(5000); // I assume IProxyFilter might take some time.

    var token = config.GetReloadToken();

    token.RegisterChangeCallback(Reload, config);
}
```

**Comment by alnikola** [comment] 2021-09-15 14:40
Hmm. It might be an issue. To my understanding, we won't observe any updates in the config which happens while the reload code goes [from line 174 to line 208](https://github.com/microsoft/reverse-proxy/blob/3d4957a7266cadd1d08790a31a7c52b2fbe2ac8e/src/ReverseProxy/Management/ProxyConfigManager.cs#L174-L208). It seems OK in case the config changes keep coming after we have again subscribed on line 208, but if the changes stop right before we execute the line 208, we won't see anything.

**Comment by Tratcher** [comment] 2021-09-15 16:39
@Kahbazi your example isn't comparable. In our case each config instance has its own change token indicating when that instance has expired, the two are always in sync. In your example you miss a change notification because you don't request a new token until after the change has already happened. A more comparable example would look like this:
```
static async void Reload(object obj)
{
    var config = obj as IConfiguration;

    // Get a token associated with the current config
    var token = config.GetReloadToken();
    Console.WriteLine(config["Name"]);

    await Task.Delay(5000); // I assume IProxyFilter might take some time.

    token.RegisterChangeCallback(Reload, config);
}
```

**Comment by Tratcher** [comment] 2021-09-15 17:04
The main place I see where we could hit an issue is if RegisterChangeCallback doesn't work after the token has fired. It's supposed to, but implementations may vary.

**Comment by Kahbazi** [comment] 2021-09-15 20:51
OK! I'm spending hours trying to wrap my head on what's going on here. I think I understand enough to know that I was wrong. Before I was only looking at `ProxyConfigManager` and not `ConfigurationConfigProvider` .Thanks for your explanation @Tratcher. Feel free to close this issue.

**Comment by karelz** [comment] 2021-09-16 17:27
Triage: Closing per comment above.
We are reasonably sure this is not an issue.

**Closed by karelz** 2021-09-16 17:27 UTC
Labels: Type: Bug, Triage: Info Needed
