### ISSUE TITLE
How to get online YARP stats

### ISSUE THREAD

**Issue by sergiobortsov** [microsoft/reverse-proxy#1148] opened 2021-07-08 11:44 UTC
### What should we add or change to make your life better?
it would be great to have the way to get some online YARP stats like current assigned requests per destination, queue (if there is some queue functionality), etc

### Why is this important to you?
I'm building the tool to analyze a load balancer stats and then managing the quantity of destinations based on that.

Thanks
Sergii

**Comment by Tratcher** [comment] 2021-07-08 15:49
See https://github.com/microsoft/reverse-proxy/discussions/1124. Once you get the destinations you can look here for request counts:
https://github.com/microsoft/reverse-proxy/blob/1f27ecf4e1b23fd44bc9106f6765c65944caa271/src/ReverseProxy/Model/DestinationState.cs#L54

YARP does not have a queue, though the underlying HttpClient might. I don't think that's visible anywhere.

**Comment by Tratcher** [comment] 2021-07-13 18:27
Duplicate of #125

**Closed by Tratcher** 2021-07-13 18:27 UTC
Labels: Type: Idea
