### ISSUE TITLE
SignalR OnDisconnectedAsync is not called on Hub when YARP is used

### ISSUE THREAD

**Issue by Schaeri** [microsoft/reverse-proxy#2248] opened 2023-09-08 08:34 UTC
## Description
We have encountered an issue with YARP 2.0.1 and SignalR. When using YARP, we have noticed that the OnDisconnectedAsync on the hub is not called when navigating away from the page, e.g. on www.domain.xy or when the browser is closed. However, the problem only occurs with **Chrome based browsers**. E.g. Edge and Chrome. With Firefox the handling works. 

We see the following YARP log when we navigate away from a page hosting a SignalR connection on Chrome or Edge or close the browser:

```
Yarp.ReverseProxy.Forwarder.HttpForwarder[48]
      UpgradeRequestCanceled: Copying the upgraded request body was canceled.
      System.IO.IOException: The client reset the request stream.
         at System.IO.Pipelines.Pipe.GetReadResult(ReadResult& result)
         at System.IO.Pipelines.Pipe.GetReadAsyncResult()
         at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http2.Http2MessageBody.ReadAsync(CancellationToken cancellationToken)
         at System.Runtime.CompilerServices.PoolingAsyncValueTaskMethodBuilder1.StateMachineBox1.System.Threading.Tasks.Sources.IValueTaskSource<TResult>.GetResult(Int16 token)
         at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpRequestStream.ReadAsyncInternal(Memory1 destination, CancellationToken cancellationToken)
         at System.Runtime.CompilerServices.PoolingAsyncValueTaskMethodBuilder1.StateMachineBox1.System.Threading.Tasks.Sources.IValueTaskSource<TResult>.GetResult(Int16 token)
         at Yarp.ReverseProxy.Forwarder.StreamCopier.CopyAsync(Stream input, Stream output, Int64 promisedContentLength, StreamCopierTelemetry telemetry, ActivityCancellationTokenSource activityToken, Boolean autoFlush, CancellationToken cancellation)
```

On Firefox we see the following log:

```
Yarp.ReverseProxy.Forwarder.HttpForwarder[48]
      RequestCanceled: The request was canceled before receiving a response.
      System.Threading.Tasks.TaskCanceledException: The operation was canceled.
         at System.Net.Http.Http2Connection.Http2Stream.<>c.<WaitForDataAsync>b__87_0(Object s, CancellationToken cancellationToken)
         at System.Threading.CancellationTokenSource.ExecuteCallbackHandlers(Boolean throwOnFirstException)
         at Yarp.ReverseProxy.Utilities.ActivityCancellationTokenSource.<>c.<.cctor>b__15_0(Object s)
         at System.Threading.CancellationTokenSource.ExecuteCallbackHandlers(Boolean throwOnFirstException)
         at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpProtocol.CancelRequestAbortedTokenCallback()
         at System.Threading.ThreadPoolWorkQueue.Dispatch()
         at System.Threading.PortableThreadPool.WorkerThread.WorkerThreadStart()
         at System.Threading.Thread.StartCallback()
      --- End of stack trace from previous location ---
         at System.Net.Http.Http2Connection.Http2Stream.System.Threading.Tasks.Sources.IValueTaskSource.GetResult(Int16 token)
         at System.Net.Http.Http2Connection.Http2Stream.ReadResponseHeadersAsync(CancellationToken cancellationToken)
         at System.Net.Http.Http2Connection.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
         at System.Net.Http.HttpConnectionPool.SendWithVersionDetectionAndRetryAsync(HttpRequestMessage request, Boolean async, Boolean doRequestAuth, CancellationToken cancellationToken)
         at System.Net.Http.DiagnosticsHandler.SendAsyncCore(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
         at Yarp.ReverseProxy.Forwarder.HttpForwarder.SendAsync(HttpContext context, String destinationPrefix, HttpMessageInvoker httpClient, ForwarderRequestConfig requestConfig, HttpTransformer transformer, CancellationToken cancellationToken
```

## To Reproduce
To reproduce the problem, I have created a demo app in which the behavior can be reproduced. The app contains an ASP.NET Core Server application and a Blazor WASM client. When a SignalR connection is established or closed, the connection counter is written to an InMemory cache. The counters are displayed on the client.

[ProblemDemo.zip](https://github.com/microsoft/reverse-proxy/files/12557251/ProblemDemo.zip)

### Steps for reproduction with Edge/Chrome
1.) Launch the demo app and navigate to https://localhost:6001 (the app runs behind YARP).

2.) Clicking the button "Connect SignalR Hub".
![1](https://github.com/microsoft/reverse-proxy/assets/15650359/2a203a76-1004-4f13-82fb-256760d6c997)
Now we have a SignalR connection.

3.) Navigating away from the page. E.G. www.microsoft.com
![2](https://github.com/microsoft/reverse-proxy/assets/15650359/9c971ee1-c612-4929-9fab-37bd17f31592)

4.) Navigation back to the demo app. (Back Button Browser). The disconnect was not detected. Connect counter is still at 1, Disconnect counter is at 0. Delta is 1. Expected behavior. Delta 0, both counters at 1.
![3](https://github.com/microsoft/reverse-proxy/assets/15650359/eed3cb0f-2c3d-4be7-90e5-a293df2648b8)

5.) Restarting the app and navigating to https://localhost:7124/ (app is called directly, no YARP).

6.) Click the button "Connect SignalR Hub".
Now we have a SignalR connection.
![4](https://github.com/microsoft/reverse-proxy/assets/15650359/5157fb8f-c248-4741-a30f-6fa3944bb481)

7.) Navigation away from the page. E.G. www.microsoft.com
![5](https://github.com/microsoft/reverse-proxy/assets/15650359/6b94d392-cc20-4338-9a15-6ded4c8891ca)

8.) Navigation back to the demo app. (Back Button Browser). The disconnect has been detected. The Connect and Disconnect counters are both at 1. The delta is 0. 
![6](https://github.com/microsoft/reverse-proxy/assets/15650359/51d40cb3-8ff7-401a-87f8-aa546ecaa8c8)

## Further technical details
- If the application is hosted in IIS the problem cannot be reproduced. It occurs only with Kestrel. 
- Possibly the problem is related to the error https://github.com/microsoft/reverse-proxy/issues/2070. Unfortunately, this fix has not been released in a NuGet package yet.

**Comment by Tratcher** [comment] 2023-09-08 22:00
> UpgradeRequestCanceled vs RequestCanceled

This tells us that Chrome & Edge are using WebSockets, but Firefox isn't, it's probably using log polling. Make sure all of the browsers are using the same mechanism and then see which works and which doesn't.

**Comment by Schaeri** [comment] 2023-09-09 13:33
@Tratcher:  Thanks for the feedback. 

The problem why this bug was created is that the behavior with and without gateway is not the same. 
Without gateway, navigating away to another domain immediately triggers the OnDisconnect on the hub. This happens with all browsers. 

With YARP, the OnDisconnect on the hub is not called directly when leaving the page to another domain in Edge/Chrome. In some cases, OnDisconnect is not triggered at all or only after a connection monitoring timeout from SignalR. This is about 30 to 45 seconds. The screenshots show how the behavior can be reproduced with the demo program.   

While testing, we noticed that Firefox behaves differently. There the OnDisconnect is called also with YARP like without YARP immediately when leaving the side. Firefox, Edge, Chrome all use web sockets.

The behavior is also different if the application is hosted in IIS. Then it works as expected.

**Comment by benjaminpetit** [comment] 2023-09-20 15:02
I am able to repro it with a build from main, so #2070 doesn't seems to be related

**Comment by benjaminpetit** [comment] 2023-10-03 17:57
I investigated a bit more today, and it seems that I do get `RequestCanceled: The request was canceled before receiving a response.` even on edge, but it's not immediate, I need to wait for a bit to see it.

I wonder if firefox is closing the socket properly while with edge/chrome the app just wait for a TCP timeout?

**Comment by Schaeri** [comment] 2023-10-12 19:36
Why it works with Firefox and not with Chromium-based browsers is more of a secondary question.

What I observe is that, for example, with Edge/Chrome, the connection loss is detected immediately without Yarp. With Yarp, the connection loss is only detected after a timeout. Could it be that the connection from the browser to Yarp terminates, but the connection loss is not correctly passed on? Does the connection with the system behind Yarp remain intact?

And is my assumption that it should behave exactly the same with and without Yarp even correct?

**Comment by karelz** [comment] 2023-10-19 16:37
Triage: @benjaminpetit was able to reproduce it and we are slowly investigating. We should fix it at minimum in next release.

**Comment by TimeWanderer** [comment] 2024-01-10 09:39
Any updates on this? This feels like a big issue for anyone who is working with signalr.

**Comment by MihaZupan** [comment] 2024-03-14 13:00
Sorry about the delay here.

This issue has been fixed in the latest servicing releases of .NET 7 and .NET 8:
- [7.0.17 (SDK 7.0.407)](https://dotnet.microsoft.com/en-us/download/dotnet/7.0)
- [8.0.3 (8.0.202)](https://dotnet.microsoft.com/en-us/download/dotnet/8.0)

**Closed by MihaZupan** 2024-03-14 13:00 UTC
Labels: Type: Bug
