### ISSUE TITLE
WebSocket error after upgrading from 1.0.0-preview.11.21223.5 to v1.0.0

### ISSUE THREAD

**Issue by rterekhov** [microsoft/reverse-proxy#1541] opened 2022-02-01 12:27 UTC
### Describe the bug
We use reverse-proxy to get access to Citect Anywhere application
that uses WebSocket (https://www.google.com/search?q=citect+anywhere). 

It worked well for us with 1.0.0-preview.11.21223.5 and 1.0.0-preview.12.21328.2 versjons,
but starting with 1.0.0-preview.12.21451.3 it stopped working.

WebSocket connection does not get established and we get an error:
WebSocket connection to 'wss://proxy.to.citect.anywhere.application/blaze' failed: 

What can we do for troubleshooting the problem?

### To Reproduce
The only thing we change is version to Yarp.ReverseProxy package and we have tried several version:

1.0.0                                            not working 
1.0.0-rc.1.21520.4                       not working 
1.0.0-preview.12.21451.3            not working 
1.0.0-preview.12.21328.2                   working (but deprecated)
1.0.0-preview.11.21223.5                   working 

### Further technical details
Windows Server 2019 Datacenter 1809 with all WIndows Updates
.NET Core 3.1.22
IIS

We had also problem with getting it to work in Azure App Service as well as on Windows Server 2016.
The only setup that worked for us is VM with Windows Server 2019 and version 1.0.0-preview.11.21223.5.

**Comment by MihaZupan** [comment] 2022-02-01 12:53
> 1.0.0-preview.12.21451.3 not working
> 1.0.0-preview.12.21328.2 working (but deprecated)

[`1.0.0-preview.12.21451.3`](https://github.com/microsoft/reverse-proxy/releases/tag/v1.0.0-preview12.21451.3) was a security patch and as such only had a single change on top of `12.21328.2`: #1220.

The difference is that we now remove the `Content-Length` header if the request contained both `Content-Length` and `Transfer-Encoding`.

You could try doing the reverse (remove `Transfer-Encoding`) and see if that solves your issue (noting the request smuggling security implications).

**Comment by Tratcher** [comment] 2022-02-01 17:56
Hmm, a WebSocket should never have a Content-Length or Transfer-Encoding header.

Start by collecting logs from the proxy to see what errors it reports.
https://microsoft.github.io/reverse-proxy/articles/diagnosing-yarp-issues.html

**Comment by rterekhov** [comment] 2022-02-08 13:10
Here are logs from the final release 1.0.0

```
2022-02-08T13:31:07.3994 [INF] Request starting HTTP/2.0 GET https://b2904d7666.proxy.test.mycompany.com/   (ca22a1cb)
2022-02-08T13:31:07.4027 [DBG] Wildcard detected, all requests with hosts will be allowed. (af1c1e85)
2022-02-08T13:31:07.4027 [VRB] All hosts are allowed. (2e40afda)
2022-02-08T13:31:07.4509 [DBG] 1 candidate(s) found for the request path '"/"' (9406aaa8)
2022-02-08T13:31:07.4560 [DBG] Endpoint '"b2904d7666"' with route pattern '"/{**catchall}"' is valid for the request path '"/"' (430aaaf2)
2022-02-08T13:31:07.4568 [DBG] Request matched endpoint '"b2904d7666"' (cbf60c4b)
2022-02-08T13:31:07.4810 [VRB] Performing unprotect operation to key {f6e72a7b-9cbd-4d59-abda-7b1db4848e14} with purposes "('MyWebApp', 'Microsoft.AspNetCore.Authentication.Cookies.CookieAuthenticationMiddleware', 'Identity.Application', 'v2')". (97369f67)
2022-02-08T13:31:07.4828 [DBG] AuthenticationScheme: "Identity.Application" was successfully authenticated. (1805f3b3)
2022-02-08T13:31:07.5026 [INF] Request finished in 106.5488ms 302  (791a596a)
2022-02-08T13:31:09.2699 [INF] Request starting HTTP/2.0 GET https://b2904d7666.proxy.test.mycompany.com/PlantSCADAAccessAnywhere/resources/blaze.txt?_=1644323469195   (ca22a1cb)
2022-02-08T13:31:09.2705 [VRB] All hosts are allowed. (2e40afda)
2022-02-08T13:31:09.2708 [DBG] 1 candidate(s) found for the request path '"/PlantSCADAAccessAnywhere/resources/blaze.txt"' (9406aaa8)
2022-02-08T13:31:09.2709 [DBG] Endpoint '"b2904d7666"' with route pattern '"/{**catchall}"' is valid for the request path '"/PlantSCADAAccessAnywhere/resources/blaze.txt"' (430aaaf2)
2022-02-08T13:31:09.2710 [DBG] Request matched endpoint '"b2904d7666"' (cbf60c4b)
2022-02-08T13:31:09.2719 [VRB] Performing unprotect operation to key {f6e72a7b-9cbd-4d59-abda-7b1db4848e14} with purposes "('MyWebApp', 'Microsoft.AspNetCore.Authentication.Cookies.CookieAuthenticationMiddleware', 'Identity.Application', 'v2')". (97369f67)
2022-02-08T13:31:09.2724 [DBG] AuthenticationScheme: "Identity.Application" was successfully authenticated. (1805f3b3)
2022-02-08T13:31:09.2736 [INF] Executing endpoint '"b2904d7666"' (500cc934)
2022-02-08T13:31:09.3233 [INF] Proxying to "https://10.10.10.20/PlantSCADAAccessAnywhere/resources/blaze.txt?_=1644323469195" "HTTP/2" "RequestVersionOrLower" "no-streaming" (d30b6879)
2022-02-08T13:31:09.3930 [INF] Request starting HTTP/2.0 GET https://b2904d7666.proxy.test.mycompany.com/PlantSCADAAccessAnywhere/resources/lang/dictionary.en-us.txt?_=1644323469196   (ca22a1cb)
2022-02-08T13:31:09.3931 [VRB] All hosts are allowed. (2e40afda)
2022-02-08T13:31:09.3932 [DBG] 1 candidate(s) found for the request path '"/PlantSCADAAccessAnywhere/resources/lang/dictionary.en-us.txt"' (9406aaa8)
2022-02-08T13:31:09.3933 [DBG] Endpoint '"b2904d7666"' with route pattern '"/{**catchall}"' is valid for the request path '"/PlantSCADAAccessAnywhere/resources/lang/dictionary.en-us.txt"' (430aaaf2)
2022-02-08T13:31:09.3934 [DBG] Request matched endpoint '"b2904d7666"' (cbf60c4b)
2022-02-08T13:31:09.4012 [VRB] Performing unprotect operation to key {f6e72a7b-9cbd-4d59-abda-7b1db4848e14} with purposes "('MyWebApp', 'Microsoft.AspNetCore.Authentication.Cookies.CookieAuthenticationMiddleware', 'Identity.Application', 'v2')". (97369f67)
2022-02-08T13:31:09.4207 [DBG] AuthenticationScheme: "Identity.Application" was successfully authenticated. (1805f3b3)
2022-02-08T13:31:09.4213 [INF] Executing endpoint '"b2904d7666"' (500cc934)
2022-02-08T13:31:09.4219 [INF] Proxying to "https://10.10.10.20/PlantSCADAAccessAnywhere/resources/lang/dictionary.en-us.txt?_=1644323469196" "HTTP/2" "RequestVersionOrLower" "no-streaming" (d30b6879)
2022-02-08T13:31:09.4923 [INF] Executed endpoint '"b2904d7666"' (99874f2b)
2022-02-08T13:31:09.4936 [INF] Request finished in 223.9351ms 200 text/plain (791a596a)
2022-02-08T13:31:09.4972 [INF] Executed endpoint '"b2904d7666"' (99874f2b)
2022-02-08T13:31:09.4974 [INF] Request finished in 104.3585ms 200 text/plain (791a596a)
2022-02-08T13:31:09.5829 [INF] Request starting HTTP/1.1 GET https://b2904d7666.proxy.test.mycompany.com/blaze   (ca22a1cb)
2022-02-08T13:31:09.5830 [VRB] All hosts are allowed. (2e40afda)
2022-02-08T13:31:09.5831 [DBG] 1 candidate(s) found for the request path '"/blaze"' (9406aaa8)
2022-02-08T13:31:09.5831 [DBG] Endpoint '"b2904d7666"' with route pattern '"/{**catchall}"' is valid for the request path '"/blaze"' (430aaaf2)
2022-02-08T13:31:09.5832 [DBG] Request matched endpoint '"b2904d7666"' (cbf60c4b)
2022-02-08T13:31:09.5834 [VRB] Performing unprotect operation to key {f6e72a7b-9cbd-4d59-abda-7b1db4848e14} with purposes "('MyWebApp', 'Microsoft.AspNetCore.Authentication.Cookies.CookieAuthenticationMiddleware', 'Identity.Application', 'v2')". (97369f67)
2022-02-08T13:31:09.5835 [DBG] AuthenticationScheme: "Identity.Application" was successfully authenticated. (1805f3b3)
2022-02-08T13:31:09.5839 [INF] Executing endpoint '"b2904d7666"' (500cc934)

2022-02-08T13:31:09.5863 [INF] Proxying to "https://10.10.10.20/blaze" "HTTP/1.1" "RequestVersionOrLower" "no-streaming" (d30b6879)
2022-02-08T13:31:09.5920 [INF] Executed endpoint '"b2904d7666"' (99874f2b)
2022-02-08T13:31:09.5921 [INF] Request finished in 9.2663ms 404  (791a596a)

2022-02-08T13:31:09.6666 [INF] Request starting HTTP/2.0 GET https://b2904d7666.proxy.test.mycompany.com/PlantSCADAAccessAnywhere/lz4w.js?_=1644323469544   (ca22a1cb)
2022-02-08T13:31:09.6668 [VRB] All hosts are allowed. (2e40afda)
2022-02-08T13:31:09.6669 [DBG] 1 candidate(s) found for the request path '"/PlantSCADAAccessAnywhere/lz4w.js"' (9406aaa8)
2022-02-08T13:31:09.6669 [DBG] Endpoint '"b2904d7666"' with route pattern '"/{**catchall}"' is valid for the request path '"/PlantSCADAAccessAnywhere/lz4w.js"' (430aaaf2)
2022-02-08T13:31:09.6669 [DBG] Request matched endpoint '"b2904d7666"' (cbf60c4b)
2022-02-08T13:31:09.6672 [VRB] Performing unprotect operation to key {f6e72a7b-9cbd-4d59-abda-7b1db4848e14} with purposes "('MyWebApp', 'Microsoft.AspNetCore.Authentication.Cookies.CookieAuthenticationMiddleware', 'Identity.Application', 'v2')". (97369f67)
2022-02-08T13:31:09.6673 [DBG] AuthenticationScheme: "Identity.Application" was successfully authenticated. (1805f3b3)
2022-02-08T13:31:09.6676 [INF] Executing endpoint '"b2904d7666"' (500cc934)
2022-02-08T13:31:09.6678 [INF] Proxying to "https://10.10.10.20/PlantSCADAAccessAnywhere/lz4w.js?_=1644323469544" "HTTP/2" "RequestVersionOrLower" "no-streaming" (d30b6879)
2022-02-08T13:31:09.6707 [INF] Executed endpoint '"b2904d7666"' (99874f2b)
2022-02-08T13:31:09.6708 [INF] Request finished in 4.2507ms 200 text/javascript (791a596a)
```

The destination app just loggs
```
22/02/08 13:57:07.516 |     4464 | [WEBSERV] ERROR: File '/blaze' not found.
```

May be there is something with transition between HTTP/2.0 and HTTP/1.1 protocols?

**Comment by rterekhov** [comment] 2022-06-01 14:00
Hi, now I used Wireshark to capture HTTP request on target server for the version that works (_1.0.0-preview.11.21223.5_) and the one that does not work (_1.0.0-preview.12.21328.2_). The only difference that I can see is the order of _Connection_ and _Upgrade_ headers. According to specification the order of headers should not matter, but it looks like it does in my case :-)

![wireshark](https://user-images.githubusercontent.com/5381279/171422643-4c376ade-a9f3-45e8-a1f9-b5c2a0c14c8d.png)

**Comment by Tratcher** [comment] 2022-06-01 14:20
Can you share those capture files so I can check for other subtle differences?

**Comment by MihaZupan** [comment] 2022-06-01 14:33
And these are requests from the proxy to the downstream server?

**Comment by rterekhov** [comment] 2022-06-01 14:43
Yes, these are requests from proxy to the downstream server.

[wireshark.zip](https://github.com/microsoft/reverse-proxy/files/8815184/wireshark.zip)

**Comment by rterekhov** [comment] 2022-06-02 08:34
Here is original request from browser to the proxy

![browser](https://user-images.githubusercontent.com/5381279/171589152-c394f381-c9a4-40d4-bcd6-e321c68ac6d4.png)

**Comment by greenEkatherine** [comment] 2022-07-14 12:35
@rterekhov sorry for the long delay. I compared requests that you provided and did not find any issues that could be YARP related.  The only difference is as you noticed -- the order of the headers. If it matters for server so that server handles requests differently, it means the issue is on the server side. 

Does not seem to be actionable for us, closing. Feel free to reopen if there is additional info available. Thanks!

**Closed by greenEkatherine** 2022-07-14 12:35 UTC
Labels: Type: Bug
