### ISSUE TITLE
How to: Certificate rotations

### ISSUE THREAD

**Issue by samsp-msft** [microsoft/reverse-proxy#993] opened 2021-05-11 04:41 UTC
How should certs be rotated with YARP without having to stop the service? Do we detect that cert store or files on disk have changed?

**Comment by Tratcher** [comment] 2021-05-11 06:16
Server certificates (incoming connections) or client certificates (outgoing connections)? Presumably both.

**Comment by samsp-msft** [comment] 2021-05-12 05:31
Yes both. Also how to associate the right certs with either routes (incoming) or clusters/destinations (outgoing).

**Comment by Tratcher** [comment] 2021-05-12 17:38
Incoming cert config is handled by the server, it's not a YARP concern. Barry is working on rotation guidance there.

For outgoing certs, see https://github.com/microsoft/reverse-proxy/issues/989#issuecomment-839366901.

**Comment by karelz** [comment] 2021-05-13 17:15
Duplicate of #989

**Closed by karelz** 2021-05-13 17:15 UTC
Labels: Type: Bug
