### ISSUE TITLE
Dynamic Routing

### ISSUE THREAD

**Issue by chaseaucoin** [microsoft/reverse-proxy#353] opened 2020-07-29 17:26 UTC
### What should we add or change to make your life better?
For a few of my projects I have endpoints that are inherently ephemeral and addressable only via internal subnets. I would like the ability to have a route provider that is not based on IConfiguration and can change during the lifetime of the application. 

### Why is this important to you?
Having the ability to change routes during the lifetime of the proxy enables a few different scenarios:

1: Ephemeral endpoints especially usefully in orchestrated environments where lists of objects like containers can be gathered and then used to feed cluster information.

2: Service Registration: By being able to have a provider for routes it enables for services coming online to be able to register with the proxy using custom logic creating looser coupling and reconfiguration without redeployment.

**Comment by samsp-msft** [comment] 2020-07-29 18:19
Please see #8 and #46, as we have planned 2 levels of dynamic routing:
#8 - having an API to create and modify routes on the fly
#46 - having a callback so that routes can be queried from an external source on a per-request basis.

I suspect from your description above that #8 would be sufficient.

**Comment by Tratcher** [comment] 2020-07-29 18:33
> and can change during the lifetime of the application.

Note the IConfiguration implementation also supports live reload if the config files change.

**Comment by chaseaucoin** [comment] 2020-07-29 18:37
That would most definitely be sufficient. Does the team need any help for it and/or are you accepting PRs?

**Comment by Tratcher** [comment] 2020-07-29 18:41
I'll be working on #8 next. It's a pretty large work item so I wouldn't recommend a PR for it. Thanks for the offer.

**Comment by chaseaucoin** [comment] 2020-07-29 18:44
Well if you got a buymeacoffee or equivalent I'm happy to send a few bucks as a thank you.

**Comment by Tratcher** [comment] 2020-07-29 18:49
Generous, but not necessary. What I will need your help for is testing the implementation when it's ready. Subscribe to #8 and check back when it's done.

**Comment by samsp-msft** [comment] 2020-07-30 18:28
Duplicate of #8

**Closed** 2020-07-30 18:28 UTC
Labels: Resolution: Duplicate, Type: Idea
