### ISSUE TITLE
YARP RC1 has issues proxying back certain response to the client

### ISSUE THREAD

**Issue by jmezach** [microsoft/reverse-proxy#1337] opened 2021-10-29 09:30 UTC
### Describe the bug
As I mentioned in #1314 we've recently tried to upgrade our production deployment using YARP this morning with .NET 6 (RC2) and YARP RC1. Unfortunately we quickly saw an increase in 502 responses coming back, so we rolled back the deployment. Since then we've been trying to figure out by looking at our logs. One thing we noticed is that during the time that the new version was deployed we are seeing the following message in our logs, including a stack trace:

```
ResponseHeaders: The destination returned a response that cannot be proxied back to the client.
System.IndexOutOfRangeException: Index was outside the bounds of the array.
   at System.Net.Http.Headers.HttpHeaders.ReadStoreValues[T](Span`1 values, Object storeValue, HttpHeaderParser parser, Int32& currentIndex)
   at System.Net.Http.Headers.HttpHeaders.GetStoreValuesAsStringOrStringArray(HeaderDescriptor descriptor, Object sourceValues, String& singleValue, String[]& multiValue)
   at System.Net.Http.Headers.HttpHeaders.GetStoreValuesAsStringArray(HeaderDescriptor descriptor, HeaderStoreItemInfo info)
   at System.Net.Http.Headers.HttpHeaders.GetEnumeratorCore()+MoveNext()
   at Yarp.ReverseProxy.Forwarder.HttpTransformer.CopyResponseHeaders(HttpHeaders source, IHeaderDictionary destination)
   at Yarp.ReverseProxy.Forwarder.HttpTransformer.TransformResponseAsync(HttpContext httpContext, HttpResponseMessage proxyResponse)
   at Yarp.ReverseProxy.Transforms.Builder.StructuredTransformer.TransformResponseAsync(HttpContext httpContext, HttpResponseMessage proxyResponse)
   at Yarp.ReverseProxy.Forwarder.HttpForwarder.SendAsync(HttpContext context, String destinationPrefix, HttpMessageInvoker httpClient, ForwarderRequestConfig requestConfig, HttpTransformer transformer)
```

Outside of the window that the new version was deployed we do not see these errors, which seems to suggest that it is related to the upgrade.

### To Reproduce
To be honest, we're not sure what triggers this. We haven't been able to reproduce this on our test environments so far, which suggests this is only triggered under load.

### Further technical details
YARP version: 1.0 RC1
.NET version: 6.0 RC2
Platform: Windows

**Comment by jmezach** [comment] 2021-11-01 12:53
I've been trying to produce some load on our test environment to see if I can trigger this so that I don't have to test this out in production, but unfortunately I haven't been able to achieve that so far. We're a bit hesitant to try it out in production again because of possible customer impact.

**Comment by Tratcher** [comment] 2021-11-04 22:16
Offline notes: This seems to be caused by a combination of reduced locking in HttpClient headers in 6.0 and some multi-threading in a 3rd party logging tool. It's not a YARP specific issue and updating from preview12 to RC1 should be fine.

We'll follow up on the locking change and the logging tool threading.

**Comment by jmezach** [comment] 2021-11-09 13:54
Is there an update on this issue, or is there an upstream issue somewhere I can follow for status updates? This is currently blocking us from upgrading to .NET 6.

**Comment by karelz** [comment] 2021-11-09 16:38
@jmezach we didn't create runtime issue yet, though we will likely create one soon.
We are still discussing our best options - potential fix, or marking it as by design and requiring violators to change their code.

The bottom line is that for now, YARP on .NET 6 is not compatible with New Relic. Downgrading to .NET 5.0 should be fine, or removing New Relic.
We plan to reach out to New Relic once we have consensus and clarity on the options.

**Comment by jmezach** [comment] 2021-11-09 17:42
@karelz Thanks for the reply, that makes sense. I guess we're stuck on .NET 5 for the time being then. Am I correct in assuming that the same issue could happen with any .NET 6 application that sends or receives HTTP requests, for example some service running behind YARP?

Congrats on the 1.0 release by the way :).

**Comment by Tratcher** [comment] 2021-11-09 17:52
Correct, there's nothing YARP specific here, the issue is a conflict between New Relic and HttpClient.

**Comment by jmezach** [comment] 2021-11-09 18:12
Thanks for clarifying. You mention the combination of New Relic and HttpClient, so if I have an ASP.NET Core Web API running on .NET 6 that doesn't use HttpClient we would be okay?

**Comment by Tratcher** [comment] 2021-11-09 18:14
Correct.

**Comment by MihaZupan** [comment] 2021-11-09 18:14
Yes. You would only hit the issue if you attempt to read headers from HttpClient's response message.

**Comment by samsp-msft** [comment] 2021-11-10 19:27
Issue has been reported to NewRelic and they are investigating. https://github.com/newrelic/newrelic-dotnet-agent/issues/803.

**Comment by adityamandaleeka** [comment] 2021-11-18 17:49
Closing this since the issue is tracked in https://github.com/newrelic/newrelic-dotnet-agent/issues/803 (fixed and pending release) and a new issue will be opened in dotnet/runtime for other mitigations for this.

**Closed by adityamandaleeka** 2021-11-18 17:49 UTC
Labels: Type: Bug, Triage: Info Needed

**Comment by MihaZupan** [comment] 2021-11-18 19:09
Runtime issue: https://github.com/dotnet/runtime/issues/61798

**Comment by MihaZupan** [comment] 2021-11-18 19:44
Looks like NewRelic released a new version of their .NET agent an hour ago: https://github.com/newrelic/newrelic-dotnet-agent/releases/tag/v9.2.0

**Comment by nr-ahemsath** [comment] 2021-11-19 17:28
@MihaZupan Yes, we released a new version of our agent with a fix for this issue yesterday.  I'd love for @jmezach to try it out and let us know if it fixes their issue.

**Comment by jmezach** [comment] 2021-11-19 17:59
@nr-ahemsath Thanks for the heads-up. We've updated our New Relic agents already and will be trying YARP on .NET 6 in production next week. I'll post an update here when we have the results.

**Comment by jmezach** [comment] 2021-11-22 14:01
@nr-ahemsath We've tried to go live with this today, but unfortunately we saw pretty much the same behaviour as before. However, it turned out there was also an issue with our logging, so I can't yet definitively say that it was indeed the same issue. Will post an update when I have one.

**Comment by jmezach** [comment] 2021-11-22 21:50
@nr-ahemsath Tried again this evening (at least for us ;)) at a quieter time to see if that had any bearing on the issue. Unfortunately we still saw the same errors. After further investigation though it turned out that we weren't yet running the 9.2.0 version of the New Relic .NET agent, although we thought we did. Not entirely sure how that happened, but it happened. So we will be rolling out the 9.2.0 version of the .NET agent and try again.

**Comment by jmezach** [comment] 2021-11-24 08:37
@nr-ahemsath I'm glad to say that we are now finally up and running with .NET 6, Yarp 1.0 and New Relic's .NET Agent 9.2.0 in production and we are no longer seeing this issue. Big thanks to everyone involved in making this happen! 🎉

**Comment by karelz** [comment] 2021-11-24 08:50
Awesome news, thanks for confirmation @jmezach. And thanks for quick fix turnaround to New Relic folks!

**Comment by john--** [comment] 2022-01-14 16:40
I'm using: 

.NET 6
YARP 1.0
NewRelic.Agent.Api 9.3.0

And every once in a while I'm seeing these same errors in my logs.

I've only recently upgraded from ProxyKit to YARP, while at the same time doing a .NET5 to .NET6 upgrade.
Unfortunately this means I have no baseline for how YARP worked in .NET 5.

Is there any chance this bug still exists, or am I barking up the wrong tree?

**Comment by Tratcher** [comment] 2022-01-14 16:42
@john-- are you also using NewRelic? That was the underlying cause in this case that was fixed. If not, you may be triggering the same error another way. Please open a new issue with the details for your scenario.

**Comment by john--** [comment] 2022-01-14 16:56
> ** Edit ** (too early to read...) @john-- This should have been fixed by the NewRelic update. Does it still repro if you remove NewRelic?

This is a great question. I haven't tried that yet.

**Comment by samsp-msft** [comment] 2022-01-14 18:20
@john-- this issue is not *exclusive* to NewRelic - it can occur when anything reads the HttpClient headers collection off-thread. NewRelic's telemetry collection was one example we found. It may be that you have your own code, or something else that is also reading the collection?

**Comment by john--** [comment] 2022-01-14 18:58
> @john-- this issue is not _exclusive_ to NewRelic - it can occur when anything reads the HttpClient headers collection off-thread. NewRelic's telemetry collection was one example we found. It may be that you have your own code, or something else that is also reading the collection?

Thanks. Good point. That could be possible, but it's a very small project that only serves as a proxy and I can't think of any code that would be doing that. In regards to New Relic, it didn't occur to me at the time that the NR Agent that runs on the webserver itself is the important part here. I had only updated the "NewRelic.Agent.Api" NPM package within the project itself to the latest version, and the server is running an ancient agent (say that ten times fast!). I suspect once the server's agent is updated then I'll be truly up to date.

**Comment by john--** [comment] 2022-02-14 19:12
In case anyone is wondering, upgrading the NR agent on the server resolved my issues.
